# Generated by Django 3.1.7 on 2025-11-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('brokers', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('priority', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, help_text='Alert priority level', max_length=20)),
                ('alert_type', models.CharField(help_text='Type of alert (SL_HIT, TARGET_HIT, DELTA_ALERT, CIRCUIT_BREAKER, etc.)', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('send_telegram', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('requires_action', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('action_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.brokeraccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='brokers.order')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='positions.position')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('channel', models.CharField(help_text='telegram, email, sms', max_length=20)),
                ('status', models.CharField(help_text='SUCCESS, FAILED, PENDING', max_length=20)),
                ('response', models.TextField(blank=True, help_text='Response from service')),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alerts.alert')),
            ],
            options={
                'db_table': 'alert_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['alert', 'channel'], name='alert_logs_alert_i_f9229f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority', '-created_at'], name='alerts_priorit_771cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['account', '-created_at'], name='alerts_account_41d0dd_idx'),
        ),
    ]
