# Generated by Django 3.1.7 on 2025-11-15 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('SL', 'Stop Loss'), ('SLM', 'Stop Loss Market')], help_text='Order type (MARKET, LIMIT, SL, SLM)', max_length=20)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('NEUTRAL', 'Neutral')], help_text='Order direction (LONG or SHORT)', max_length=10)),
                ('instrument', models.CharField(help_text='Instrument symbol', max_length=100)),
                ('exchange', models.CharField(default='NSE', help_text='Exchange (NSE, BSE, NFO)', max_length=20)),
                ('quantity', models.IntegerField(help_text='Order quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Order price (for LIMIT orders)', max_digits=15, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=2, help_text='Trigger price (for SL orders)', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('FILLED', 'Filled'), ('PARTIAL', 'Partially Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Order status', max_length=20)),
                ('broker_order_id', models.CharField(blank=True, help_text='Order ID from broker', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Status message from broker')),
                ('filled_quantity', models.IntegerField(default=0, help_text='Quantity filled')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, help_text='Average execution price', max_digits=15, null=True)),
                ('placed_at', models.DateTimeField(blank=True, help_text='When order was placed with broker', null=True)),
                ('filled_at', models.DateTimeField(blank=True, help_text='When order was fully filled', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When order was cancelled', null=True)),
                ('purpose', models.CharField(blank=True, help_text='Purpose (ENTRY, EXIT, AVERAGING, ADJUSTMENT)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes')),
                ('account', models.ForeignKey(help_text='Associated broker account', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.brokeraccount')),
                ('position', models.ForeignKey(blank=True, help_text='Associated position (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='positions.position')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('execution_id', models.CharField(help_text='Unique execution ID from broker', max_length=100, unique=True)),
                ('quantity', models.IntegerField(help_text='Quantity filled in this execution', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Execution price', max_digits=15)),
                ('exchange_timestamp', models.DateTimeField(help_text='Execution timestamp from exchange')),
                ('exchange', models.CharField(blank=True, help_text='Exchange where executed', max_length=20)),
                ('transaction_type', models.CharField(help_text='BUY or SELL', max_length=10)),
                ('order', models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Executions',
                'db_table': 'executions',
                'ordering': ['-exchange_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account', 'status'], name='orders_account_ca00e7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_order_id'], name='orders_broker__a04e54_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['order', 'exchange_timestamp'], name='executions_order_i_5ef1c4_idx'),
        ),
    ]
