# Generated by Django 4.2.7 on 2026-06-24 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("SELF", "Self"),
                            ("SPOUSE", "Spouse"),
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("CHILD", "Child"),
                            ("HUF", "HUF"),
                            ("TRUST", "Trust"),
                            ("OTHER", "Other"),
                        ],
                        default="SELF",
                        max_length=20,
                    ),
                ),
                (
                    "pan_masked",
                    models.CharField(
                        blank=True, help_text="e.g. AAXXXXXX1B", max_length=20
                    ),
                ),
                (
                    "pan_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 of uppercase PAN for dedup detection",
                        max_length=64,
                    ),
                ),
                ("email_masked", models.CharField(blank=True, max_length=100)),
                ("mobile_masked", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="e.g. HDFC Demat, SBI PPF, Flat in Pune",
                        max_length=200,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("DEMAT", "Demat Account"),
                            ("MF_FOLIO", "Mutual Fund Folio"),
                            ("SAVINGS_BANK", "Savings Bank"),
                            ("PPF", "PPF Account"),
                            ("EPF", "EPF / PF Account"),
                            ("NPS", "NPS Account"),
                            ("REAL_ESTATE", "Real Estate"),
                            ("PHYSICAL_GOLD", "Physical Gold"),
                            ("CUSTOM", "Other / Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution_name", models.CharField(blank=True, max_length=200)),
                ("account_number_masked", models.CharField(blank=True, max_length=50)),
                ("dp_id", models.CharField(blank=True, max_length=20)),
                ("client_id", models.CharField(blank=True, max_length=20)),
                (
                    "depository",
                    models.CharField(
                        blank=True, help_text="NSDL or CDSL", max_length=10
                    ),
                ),
                ("nominee_registered", models.BooleanField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("CAS", "CAS Upload"),
                            ("CSV", "CSV Import"),
                            ("MANUAL", "Manual Entry"),
                            ("SYSTEM", "System Generated"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "family_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="investments.familymember",
                    ),
                ),
            ],
            options={
                "ordering": ["account_name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("MUTUAL_FUND", "Mutual Fund"),
                            ("EQUITY", "Equity / Stock"),
                            ("FD", "Fixed Deposit"),
                            ("RD", "Recurring Deposit"),
                            ("SGB", "Sovereign Gold Bond"),
                            ("BOND", "Bond / Debenture"),
                            ("PPF", "PPF"),
                            ("EPF", "EPF / PF"),
                            ("NPS", "NPS"),
                            ("REAL_ESTATE", "Real Estate"),
                            ("PHYSICAL_GOLD", "Physical Gold"),
                            ("CRYPTO", "Crypto"),
                            ("CASH", "Cash / Liquid"),
                            ("SAVINGS", "Savings Account"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("isin", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("CAS", "CAS Upload"),
                            ("CSV", "CSV Import"),
                            ("MANUAL", "Manual Entry"),
                            ("SYSTEM", "System Generated"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "invested_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("as_of_date", models.DateField(blank=True, null=True)),
                (
                    "gain_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "xirr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product-type-specific fields (units, nav, interest_rate, etc.)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "investment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="investments.investmentaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-current_value"],
            },
        ),
        migrations.CreateModel(
            name="MutualFundScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("isin", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "scheme_code",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="MFAPI numeric scheme code",
                        null=True,
                    ),
                ),
                ("scheme_name", models.CharField(max_length=500)),
                ("amc", models.CharField(blank=True, max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("sub_category", models.CharField(blank=True, max_length=100)),
                (
                    "scheme_type",
                    models.CharField(
                        blank=True, help_text="Open/Close/Interval", max_length=50
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        blank=True, help_text="DIRECT or REGULAR", max_length=20
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        blank=True, help_text="GROWTH or IDCW", max_length=20
                    ),
                ),
                (
                    "expense_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "aum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("benchmark", models.CharField(blank=True, max_length=200)),
                ("launch_date", models.DateField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, max_length=30)),
                (
                    "latest_nav",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("nav_date", models.DateField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["scheme_name"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("FAMILY", "Full Family"),
                            ("RETIREMENT", "Retirement Corpus"),
                            ("TAX_SAVING", "Tax Saving"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="investments.familymember"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioHealthScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("score_date", models.DateField(db_index=True)),
                ("total_score", models.IntegerField(default=0, help_text="0–100")),
                ("diversification_score", models.IntegerField(default=0)),
                ("concentration_score", models.IntegerField(default=0)),
                ("expense_score", models.IntegerField(default=0)),
                ("risk_adjusted_score", models.IntegerField(default=0)),
                ("allocation_score", models.IntegerField(default=0)),
                ("tax_efficiency_score", models.IntegerField(default=0)),
                ("methodology", models.JSONField(blank=True, default=dict)),
                ("insights", models.JSONField(blank=True, default=list)),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scores",
                        to="investments.familymember",
                    ),
                ),
                (
                    "portfolio_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scores",
                        to="investments.portfoliogroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-score_date"],
            },
        ),
        migrations.CreateModel(
            name="EquityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("isin", models.CharField(db_index=True, max_length=20)),
                ("symbol", models.CharField(blank=True, max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=500)),
                ("date", models.DateField(db_index=True)),
                ("price", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "source",
                    models.CharField(blank=True, default="YAHOO", max_length=20),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["isin", "date"], name="investments_isin_d38a42_idx"
                    )
                ],
                "unique_together": {("isin", "date")},
            },
        ),
        migrations.CreateModel(
            name="CASUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "cas_type",
                    models.CharField(
                        choices=[
                            ("NSDL", "NSDL e-CAS"),
                            ("CAMS", "CAMS CAS"),
                            ("KFINTECH", "KFintech CAS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("statement_month", models.IntegerField(blank=True, null=True)),
                ("statement_year", models.IntegerField(blank=True, null=True)),
                ("original_filename", models.CharField(max_length=500)),
                ("encrypted_content", models.BinaryField(blank=True, null=True)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("parse_error", models.TextField(blank=True)),
                ("accounts_created", models.IntegerField(default=0)),
                ("products_created", models.IntegerField(default=0)),
                ("transactions_created", models.IntegerField(default=0)),
                (
                    "family_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cas_uploads",
                        to="investments.familymember",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investment_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("isin", models.CharField(blank=True, db_index=True, max_length=20)),
                ("security_name", models.CharField(blank=True, max_length=500)),
                ("transaction_date", models.DateField(db_index=True)),
                ("order_no", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase / Buy"),
                            ("SALE", "Sale / Redemption"),
                            ("PLEDGE", "Pledge"),
                            ("UNPLEDGE", "Pledge Closure"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("BONUS", "Bonus / Split"),
                            ("DIVIDEND", "Dividend"),
                            ("SIP", "SIP"),
                            ("SWP", "SWP"),
                            ("STP", "STP"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "units_debit",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "units_credit",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "units_balance",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rupee amount (available in CAMS CAS, not NSDL)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "nav_at_transaction",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "cas_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="investments.casupload",
                    ),
                ),
                (
                    "investment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="investments.investmentaccount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="investments.investmentproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["isin", "transaction_date"],
                        name="investments_isin_e64168_idx",
                    ),
                    models.Index(
                        fields=["investment_account", "transaction_date"],
                        name="investments_investm_38c9f2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductValuationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto (NAV / Price Feed)"),
                            ("MANUAL", "Manual Update"),
                            ("NAV_UPDATE", "NAV Update Task"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="investments.investmentproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                (
                    "total_invested",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "gain_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "gain_loss_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "xirr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("asset_allocation", models.JSONField(blank=True, default=dict)),
                (
                    "net_worth_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Value per product_type category",
                    ),
                ),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="investments.familymember",
                    ),
                ),
                (
                    "portfolio_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="investments.portfoliogroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["family_member", "snapshot_date"],
                        name="investments_family__4f5b2f_idx",
                    ),
                    models.Index(
                        fields=["portfolio_group", "snapshot_date"],
                        name="investments_portfol_a654d4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NAVHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("nav", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_history",
                        to="investments.mutualfundscheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["scheme", "date"], name="investments_scheme__ee4710_idx"
                    )
                ],
                "unique_together": {("scheme", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(
                fields=["isin", "is_active"], name="investments_isin_066617_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(
                fields=["product_type", "is_active"],
                name="investments_product_7e5d05_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="familymember",
            unique_together={("user", "pan_hash")},
        ),
    ]
