# Generated by Django 4.2.30 on 2026-06-25 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCASPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('label', models.CharField(blank=True, help_text='e.g. Self PAN, Spouse PAN', max_length=100)),
                ('password', models.CharField(help_text='CAS PDF password (usually PAN)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Try order — lower number tried first')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'password')},
            },
        ),
    ]
