# Generated by Django 4.2.7 on 2026-07-13 07:05

from django.db import migrations, models


def backfill_pan_hash(apps, schema_editor):
    import hashlib
    FamilyMember = apps.get_model("investments", "FamilyMember")
    for member in FamilyMember.objects.all():
        if member.pan_masked:
            member.pan_hash = hashlib.sha256(member.pan_masked.upper().strip().encode()).hexdigest()
        else:
            member.pan_hash = None
        member.save(update_fields=["pan_hash"])


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0002_add_user_cas_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="pan_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 of uppercase PAN for dedup detection",
                max_length=64,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_pan_hash, migrations.RunPython.noop),
    ]
