# Generated by Django 4.2.7 on 2026-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0003_make_pan_hash_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="casupload",
            name="products_updated",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="casupload",
            name="cas_type",
            field=models.CharField(
                choices=[
                    ("NSDL", "NSDL e-CAS"),
                    ("CAMS", "CAMS / KFintech CAS"),
                    ("KFINTECH", "KFintech CAS"),
                    ("PORTFOLIO", "Equity Portfolio"),
                ],
                max_length=10,
            ),
        ),
    ]
