# Generated by Django 4.2.7 on 2026-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0005_add_source_upload_and_member_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentproduct",
            name="investment_date",
            field=models.DateField(
                blank=True,
                help_text="Date capital was first deployed — used as the XIRR cash-flow date when no transaction history exists",
                null=True,
            ),
        ),
    ]
