# Generated by Django 4.2.7 on 2026-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0006_investmentproduct_investment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casupload",
            name="cas_type",
            field=models.CharField(
                choices=[
                    ("NSDL", "NSDL e-CAS"),
                    ("CAMS", "CAMS / KFintech CAS"),
                    ("KFINTECH", "KFintech CAS"),
                    ("MFCENTRAL", "MF Central CAS"),
                    ("PORTFOLIO", "Equity Portfolio"),
                ],
                max_length=10,
            ),
        ),
    ]
