# Generated by Django 3.1.7 on 2025-11-15 07:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('broker', models.CharField(choices=[('KOTAK', 'Kotak Securities'), ('ICICI', 'ICICI Securities')], help_text='Broker name (KOTAK or ICICI)', max_length=20)),
                ('account_number', models.CharField(help_text='Unique broker account number', max_length=50, unique=True)),
                ('account_name', models.CharField(help_text='Display name for this account', max_length=100)),
                ('allocated_capital', models.DecimalField(decimal_places=2, help_text='Total capital allocated to this account', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently active for trading')),
                ('is_paper_trading', models.BooleanField(default=True, help_text='Whether this account is in paper trading mode')),
                ('max_daily_loss', models.DecimalField(decimal_places=2, help_text='Maximum loss allowed per day (circuit breaker)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_weekly_loss', models.DecimalField(decimal_places=2, help_text='Maximum loss allowed per week (circuit breaker)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this account')),
            ],
            options={
                'verbose_name': 'Broker Account',
                'verbose_name_plural': 'Broker Accounts',
                'db_table': 'broker_accounts',
                'ordering': ['broker', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('consumer_key', models.CharField(help_text='API consumer key', max_length=200)),
                ('consumer_secret', models.CharField(help_text='API consumer secret (encrypted)', max_length=200)),
                ('access_token', models.CharField(blank=True, help_text='API access token (encrypted)', max_length=500)),
                ('refresh_token', models.CharField(blank=True, help_text='API refresh token (encrypted)', max_length=500)),
                ('mobile_number', models.CharField(blank=True, help_text='Mobile number (for Kotak)', max_length=20)),
                ('password', models.CharField(blank=True, help_text='Account password (encrypted)', max_length=200)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether credentials are currently valid')),
                ('last_authenticated', models.DateTimeField(blank=True, help_text='Last successful authentication timestamp', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True)),
                ('account', models.OneToOneField(help_text='Associated broker account', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='accounts.brokeraccount')),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
                'db_table': 'api_credentials',
            },
        ),
    ]
