# Generated by Django 4.2.7 on 2026-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_apicredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokeraccount",
            name="broker",
            field=models.CharField(
                choices=[
                    ("KOTAK", "Kotak Securities"),
                    ("ICICI", "ICICI Securities"),
                    ("PAPER", "Paper Trading"),
                ],
                help_text="Broker name (KOTAK or ICICI)",
                max_length=20,
            ),
        ),
    ]
