# Generated by Django 4.2.7 on 2026-04-10 04:21

from decimal import Decimal
from django.db import migrations


def create_paper_account(apps, schema_editor):
    BrokerAccount = apps.get_model('accounts', 'BrokerAccount')

    # Safety: set all existing accounts to is_paper_trading=False
    BrokerAccount.objects.filter(is_paper_trading=True).update(is_paper_trading=False)

    # Create paper trading account if it doesn't exist
    BrokerAccount.objects.get_or_create(
        account_number='PAPER-001',
        defaults={
            'broker': 'PAPER',
            'account_name': 'Paper Trading Account',
            'allocated_capital': Decimal('10000000'),  # 1 Cr
            'is_active': True,
            'is_paper_trading': True,
            'max_daily_loss': Decimal('500000'),
            'max_weekly_loss': Decimal('1500000'),
            'notes': 'Auto-created paper trading account for simulated trades',
        }
    )


def reverse_paper_account(apps, schema_editor):
    BrokerAccount = apps.get_model('accounts', 'BrokerAccount')
    BrokerAccount.objects.filter(account_number='PAPER-001').delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_brokeraccount_broker"),
    ]

    operations = [
        migrations.RunPython(create_paper_account, reverse_paper_account),
    ]
