# Generated by Django 4.2.7 on 2025-11-16 11:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("positions", "0004_alter_monitorlog_id_alter_position_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("kotak_strangle", "Kotak Strangle (Options)"),
                            ("icici_futures", "ICICI Futures"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[("OPTIONS", "Options"), ("FUTURES", "Futures")],
                        max_length=10,
                    ),
                ),
                ("instrument", models.CharField(max_length=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("LONG", "Long"),
                            ("SHORT", "Short"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "algorithm_reasoning",
                    models.JSONField(
                        default=dict,
                        help_text="Complete algorithm analysis including all calculations, filters, and scores",
                    ),
                ),
                (
                    "position_details",
                    models.JSONField(
                        default=dict,
                        help_text="Recommended position parameters (quantity, SL, target, margin, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Manually Approved"),
                            ("AUTO_APPROVED", "Auto Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approval_timestamp", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                (
                    "is_auto_trade",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was auto-approved based on configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_position",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_suggestion",
                        to="positions.position",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trade Suggestions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeSuggestionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Suggestion Created"),
                            ("APPROVED", "Approved by User"),
                            ("AUTO_APPROVED", "Auto-Approved"),
                            ("REJECTED", "Rejected by User"),
                            ("EXECUTED", "Executed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="trading.tradesuggestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trade Suggestion Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoTradeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("kotak_strangle", "Kotak Strangle"),
                            ("icici_futures", "ICICI Futures"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "auto_approve_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("95.00"),
                        help_text="For options: LLM confidence %. For futures: Composite score",
                        max_digits=5,
                    ),
                ),
                ("max_daily_positions", models.IntegerField(default=1)),
                (
                    "max_daily_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25000.00"),
                        help_text="Maximum loss allowed per day",
                        max_digits=15,
                    ),
                ),
                ("require_human_on_weekend", models.BooleanField(default=True)),
                ("require_human_on_high_vix", models.BooleanField(default=True)),
                (
                    "vix_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_trade_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Auto-Trade Configurations",
            },
        ),
        migrations.AddIndex(
            model_name="tradesuggestion",
            index=models.Index(
                fields=["user", "status"], name="trading_tra_user_id_229fa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradesuggestion",
            index=models.Index(
                fields=["strategy", "status"], name="trading_tra_strateg_ffd1b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradesuggestion",
            index=models.Index(
                fields=["created_at"], name="trading_tra_created_97e0b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="autotradeconfig",
            unique_together={("user", "strategy")},
        ),
    ]
