# Generated by Django 4.2.7 on 2025-11-19 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[("FUTURES", "Futures"), ("OPTIONS", "Options")],
                        max_length=10,
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=10
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=12)),
                ("target", models.DecimalField(decimal_places=2, max_digits=12)),
                ("lot_size", models.IntegerField()),
                ("strike", models.IntegerField(blank=True, null=True)),
                ("option_type", models.CharField(blank=True, max_length=2)),
                (
                    "available_margin",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "margin_per_lot",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("margin_source", models.CharField(max_length=10)),
                ("recommended_lots", models.IntegerField()),
                ("total_quantity", models.IntegerField()),
                (
                    "margin_required",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("max_loss", models.DecimalField(decimal_places=2, max_digits=15)),
                ("max_profit", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "risk_reward_ratio",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "averaging_data",
                    models.JSONField(
                        blank=True, help_text="Averaging down calculations", null=True
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(help_text="Complete position sizing calculation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXECUTED", "Executed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Auto-expire after this time", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_sizes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Position Sizes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="trading_pos_user_id_d70829_idx",
                    ),
                    models.Index(
                        fields=["symbol", "instrument_type"],
                        name="trading_pos_symbol_ed7e54_idx",
                    ),
                ],
            },
        ),
    ]
