# Generated by Django 4.2.7 on 2025-11-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_positionsize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradesuggestion",
            name="approval_notes",
        ),
        migrations.RemoveField(
            model_name="tradesuggestion",
            name="approval_timestamp",
        ),
        migrations.RemoveField(
            model_name="tradesuggestion",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="breakeven_lower",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="breakeven_upper",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="call_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="call_strike",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="closed_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When trade was closed", null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="days_to_expiry",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="entry_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="exit_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="margin_available",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="margin_per_lot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="margin_required",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="margin_utilization",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="max_loss",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="max_profit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="put_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="put_strike",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="realized_pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="recommended_lots",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="rejected_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When suggestion was rejected", null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="return_on_margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="ROM %", max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="risk_reward_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="spot_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="taken_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When user took the trade", null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="total_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="user_notes",
            field=models.TextField(
                blank=True, help_text="User's notes on why taken/rejected/closed"
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="vix",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tradesuggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUGGESTED", "Suggested"),
                    ("TAKEN", "Taken"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("SUCCESSFUL", "Successful"),
                    ("LOSS", "Loss"),
                    ("BREAKEVEN", "Breakeven"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SUGGESTED",
                max_length=20,
            ),
        ),
    ]
