# Generated by Django 4.2.7 on 2025-11-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_remove_tradesuggestion_approval_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderExecutionControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True to stop ongoing order execution",
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for cancellation (server stopped, error detected, user cancelled)",
                    ),
                ),
                (
                    "batches_completed",
                    models.IntegerField(
                        default=0, help_text="Number of batches/orders completed so far"
                    ),
                ),
                (
                    "total_batches",
                    models.IntegerField(
                        default=0, help_text="Total number of batches planned"
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time execution process checked in",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "suggestion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_control",
                        to="trading.tradesuggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Execution Control",
                "verbose_name_plural": "Order Execution Controls",
            },
        ),
    ]
