# Generated by Django 4.2.7 on 2026-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0004_orderexecutioncontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotradeconfig",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("kotak_strangle", "Kotak Strangle"),
                    ("kotak_broken_iron_condor", "Kotak Broken Iron Condor"),
                    ("icici_futures", "ICICI Futures"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tradesuggestion",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("kotak_strangle", "Kotak Strangle (Options)"),
                    ("kotak_broken_iron_condor", "Kotak Broken Iron Condor (Options)"),
                    ("icici_futures", "ICICI Futures"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(
                        help_text="Stock code from Breeze API", max_length=50
                    ),
                ),
                (
                    "exchange_code",
                    models.CharField(
                        help_text="Exchange code (NSE, NFO, etc.)", max_length=10
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("futures", "Futures"),
                            ("options", "Options"),
                            ("btst", "BTST"),
                            ("margin", "Margin"),
                        ],
                        help_text="Product type",
                        max_length=10,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Expiry date for F&O", null=True
                    ),
                ),
                (
                    "strike_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strike price for options",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "right",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("call", "Call"),
                            ("put", "Put"),
                            ("others", "Others"),
                        ],
                        help_text="Call/Put for options",
                        max_length=10,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1minute", "1 Minute"),
                            ("5minute", "5 Minutes"),
                            ("30minute", "30 Minutes"),
                            ("1day", "1 Day"),
                        ],
                        help_text="Candle interval",
                        max_length=10,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(help_text="Candle datetime from API"),
                ),
                ("open", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "open_interest",
                    models.BigIntegerField(
                        blank=True, help_text="For F&O instruments", null=True
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=0, help_text="Number of ticks in candle"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When data was fetched from API"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="Raw API response for reference",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Historical Data",
                "ordering": ["-datetime"],
                "indexes": [
                    models.Index(
                        fields=[
                            "stock_code",
                            "exchange_code",
                            "product_type",
                            "interval",
                            "-datetime",
                        ],
                        name="trading_his_stock_c_b1f983_idx",
                    ),
                    models.Index(
                        fields=["stock_code", "expiry_date", "strike_price"],
                        name="trading_his_stock_c_478b1e_idx",
                    ),
                    models.Index(
                        fields=["datetime"], name="trading_his_datetim_69256c_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "stock_code",
                        "exchange_code",
                        "product_type",
                        "expiry_date",
                        "strike_price",
                        "right",
                        "interval",
                        "datetime",
                    )
                },
            },
        ),
    ]
