# Generated by Django 4.2.7 on 2026-01-23 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0005_alter_autotradeconfig_strategy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalData",
        ),
    ]
