# Generated by Django 4.2.7 on 2026-01-27 09:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_apicredential"),
        ("positions", "0005_make_stop_loss_target_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trading", "0006_delete_historicaldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TakenTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("kotak_strangle", "Kotak Strangle"),
                            ("kotak_broken_iron_condor", "Kotak Broken Iron Condor"),
                            ("icici_futures", "ICICI Futures"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("OPTIONS", "Options"), ("FUTURES", "Futures")],
                        max_length=10,
                    ),
                ),
                ("instrument", models.CharField(max_length=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("LONG", "Long"),
                            ("SHORT", "Short"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Entry price or premium collected",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Exit price or premium paid to close",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, help_text="Number of lots"),
                ),
                (
                    "lot_size",
                    models.IntegerField(
                        default=25, help_text="Lot size for the instrument"
                    ),
                ),
                (
                    "call_strike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "put_strike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "call_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Broker order ID for call leg",
                        max_length=100,
                    ),
                ),
                (
                    "put_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Broker order ID for put leg",
                        max_length=100,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "broker_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Broker order ID for futures",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_EXECUTION", "Pending Execution"),
                            ("EXECUTED", "Executed"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING_EXECUTION",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PROFIT", "Profit"),
                            ("LOSS", "Loss"),
                            ("BREAKEVEN", "Breakeven"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When user accepted the trade"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When trade was executed with broker",
                        null=True,
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="When trade was closed", null=True
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total brokerage and other charges",
                        max_digits=12,
                    ),
                ),
                (
                    "net_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L after charges",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "return_on_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Return on margin percentage",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "margin_used",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="User notes about the trade"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_trades",
                        to="accounts.brokeraccount",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to executed position",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taken_trade",
                        to="positions.position",
                    ),
                ),
                (
                    "suggestion",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to original trade suggestion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taken_trade",
                        to="trading.tradesuggestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken_trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Taken Trade",
                "verbose_name_plural": "Taken Trades",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="trading_tak_user_id_85e5d7_idx"
                    ),
                    models.Index(
                        fields=["account", "status"],
                        name="trading_tak_account_8ffcd8_idx",
                    ),
                    models.Index(
                        fields=["strategy", "outcome"],
                        name="trading_tak_strateg_259aa5_idx",
                    ),
                    models.Index(
                        fields=["taken_at"], name="trading_tak_taken_a_02d054_idx"
                    ),
                    models.Index(
                        fields=["closed_at"], name="trading_tak_closed__035a3b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="takentrade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("suggestion__isnull", False)),
                fields=("user", "suggestion"),
                name="unique_user_suggestion",
            ),
        ),
    ]
