# Generated by Django 3.1.7 on 2026-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_takentrade_takentrade_unique_user_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesuggestion',
            name='source',
            field=models.CharField(choices=[('auto', 'Automated'), ('manual', 'Manual')], db_index=True, default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='autotradeconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderexecutioncontrol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='positionsize',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='takentrade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tradesuggestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tradesuggestionlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
