# Generated by Django 4.2.7 on 2026-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0009_alter_autotradeconfig_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradesuggestion",
            name="confirmation_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When confirmation was requested via Telegram",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="confirmation_timeout_minutes",
            field=models.IntegerField(
                default=5,
                help_text="Minutes to wait before revalidating the suggestion",
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="revalidation_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether a revalidation message was sent after timeout",
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="telegram_message_id",
            field=models.CharField(
                blank=True,
                help_text="Telegram message ID for confirmation request",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradesuggestion",
            name="user_modified_lots",
            field=models.IntegerField(
                blank=True,
                help_text="User-modified lot count (if different from recommended)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tradesuggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUGGESTED", "Suggested"),
                    ("PENDING_CONFIRMATION", "Pending Confirmation"),
                    ("TAKEN", "Taken"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("SUCCESSFUL", "Successful"),
                    ("LOSS", "Loss"),
                    ("BREAKEVEN", "Breakeven"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SUGGESTED",
                max_length=20,
            ),
        ),
    ]
