# Generated by Django 4.2.7 on 2026-03-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0010_tradesuggestion_confirmation_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradesuggestion",
            name="escalated",
            field=models.BooleanField(
                default=False,
                help_text="Whether a CRITICAL escalation alert was sent due to prolonged pending state",
            ),
        ),
    ]
