# Generated by Django 4.2.7 on 2026-07-15 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_create_paper_account"),
        (
            "brokers",
            "0022_alter_brokerlimit_broker_alter_brokerposition_broker_and_more",
        ),
        ("positions", "0012_alter_position_options_alter_position_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HedgePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("breeze", "ICICI Breeze"), ("neo", "Kotak Neo")],
                        db_index=True,
                        help_text="Broker the FUTURES position (and therefore the hedge orders) executes on",
                        max_length=10,
                    ),
                ),
                ("underlying_symbol", models.CharField(db_index=True, max_length=100)),
                ("futures_expiry_date", models.DateField(db_index=True)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("COVERED_CALL", "Covered Call"),
                            ("PROTECTIVE_PUT", "Protective Put"),
                            ("COLLAR", "Collar"),
                            ("COVERED_STRANGLE", "Covered Strangle"),
                            ("WHEEL", "Wheel"),
                        ],
                        db_index=True,
                        default="COVERED_CALL",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ROLLED", "Rolled"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "futures_direction",
                    models.CharField(
                        choices=[
                            ("LONG", "Long"),
                            ("SHORT", "Short"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="LONG",
                        help_text="Direction of the underlying futures position being hedged. Always LONG for a covered call; kept generic for future strategies.",
                        max_length=10,
                    ),
                ),
                (
                    "futures_lots_covered",
                    models.PositiveIntegerField(
                        help_text="Futures lots this campaign was sized against at creation time. Active HedgeLeg quantity can never exceed this."
                    ),
                ),
                (
                    "futures_lot_size",
                    models.PositiveIntegerField(
                        help_text="Lot size of the futures contract, snapshotted at hedge-open time."
                    ),
                ),
                (
                    "futures_avg_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weighted-average futures price at the time this hedge was opened.",
                        max_digits=15,
                    ),
                ),
                (
                    "net_premium_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Running total: sold premium minus buy-back cost, across all legs/rolls.",
                        max_digits=15,
                    ),
                ),
                (
                    "effective_breakeven",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cached display value, always recomputable from futures_avg_price and net_premium_collected via payoff_engine.calculate_effective_breakeven.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "recommendation_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Recommendation-engine input/output at time of the most recent order action, kept for audit/backtest purposes.",
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Broker account this hedge is placed under",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hedge_positions",
                        to="accounts.brokeraccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hedge_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional cross-reference to a Position row, if one exists. Never required — the futures leg is identified by (broker, underlying_symbol, futures_expiry_date) instead.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hedges",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedge Position",
                "verbose_name_plural": "Hedge Positions",
                "db_table": "hedge_positions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HedgeLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "leg_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Call"),
                            ("PUT", "Put"),
                            ("FUTURE", "Future"),
                        ],
                        default="CALL",
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("SELL", "Sell"), ("BUY", "Buy")], max_length=4
                    ),
                ),
                (
                    "leg_role",
                    models.CharField(
                        choices=[
                            ("OPEN", "Initial Open"),
                            ("ROLL_CLOSE", "Roll Buy-Back"),
                            ("ROLL_OPEN", "Roll New Sell"),
                            ("MANUAL_CLOSE", "Manual Buy-Back / Expiry Close"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "option_trading_symbol",
                    models.CharField(
                        help_text="The broker-native symbol actually sent to the order API (post Neo/Breeze translation).",
                        max_length=100,
                    ),
                ),
                (
                    "breeze_source_symbol",
                    models.CharField(
                        blank=True,
                        help_text="The Breeze chain symbol this leg was priced off, kept even when executed on Neo, for audit trail purposes.",
                        max_length=100,
                    ),
                ),
                ("strike_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "option_type",
                    models.CharField(
                        choices=[("CE", "Call"), ("PE", "Put")],
                        default="CE",
                        max_length=2,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="The OPTION's own expiry — may be nearer than futures_expiry_date (e.g. a weekly call against a monthly future) but never after it."
                    ),
                ),
                ("lots", models.PositiveIntegerField()),
                (
                    "lot_size",
                    models.PositiveIntegerField(help_text="Snapshot at order time."),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("SL", "Stop-Loss"),
                        ],
                        default="MARKET",
                        max_length=10,
                    ),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "trigger_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "premium_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PLACED", "Placed"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                            ("EXPIRED_WORTHLESS", "Expired Worthless"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("greeks_at_entry", models.JSONField(blank=True, default=dict)),
                ("greeks_at_exit", models.JSONField(blank=True, default=dict)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hedge_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="hedging.hedgeposition",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generic broker Order row tracking status/fills for this leg.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hedge_legs",
                        to="brokers.order",
                    ),
                ),
                (
                    "rolled_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set on a ROLL_OPEN leg, pointing back to the leg it replaced.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rolled_to_set",
                        to="hedging.hedgeleg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedge Leg",
                "verbose_name_plural": "Hedge Legs",
                "db_table": "hedge_legs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HedgeAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Hedge Created"),
                            ("PREVIEWED", "Previewed"),
                            ("PLACED", "Order Placed"),
                            ("FILLED", "Order Filled"),
                            ("ROLL_INITIATED", "Roll Initiated"),
                            ("ROLL_COMPLETED", "Roll Completed"),
                            ("MANUAL_CLOSE", "Manual Close"),
                            ("EXPIRED_WORTHLESS", "Expired Worthless"),
                            ("CANCELLED", "Cancelled"),
                            ("VALIDATION_BLOCKED", "Blocked by Validation"),
                        ],
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request payload + validator result for this specific action.",
                    ),
                ),
                (
                    "hedge_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="hedging.hedgeposition",
                    ),
                ),
                (
                    "leg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="hedging.hedgeleg",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hedge Audit Log",
                "verbose_name_plural": "Hedge Audit Logs",
                "db_table": "hedge_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hedgeposition",
            index=models.Index(
                fields=["broker", "underlying_symbol", "futures_expiry_date", "status"],
                name="hedge_pos_lookup_idx",
            ),
        ),
    ]
