"""
Django settings for mcube_ai project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

Configuration:
    - Uses django-environ for environment variable management
    - Loads settings from .env file in project root
    - See .env.example for required environment variables
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # Set default values and casting
    DEBUG=(bool, False),  # Default to False for production safety
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
)

# Read .env file
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)
else:
    # In production, environment variables should be set externally
    # This warning helps catch configuration issues
    import warnings
    warnings.warn(
        "No .env file found. Using environment variables or defaults. "
        "For local development, copy .env.example to .env",
        UserWarning
    )


# SECURITY WARNING: keep the secret key used in production secret!
# In production, this MUST be set via environment variable
SECRET_KEY = env('SECRET_KEY', default='django-insecure-1kl+i4u(*w@#_l5&spm2t$jft9_&fuy&0k)_gs59ueri*(+8u2')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production .env file
DEBUG = env('DEBUG')

# Allowed hosts - configure in .env file
# Example in .env: ALLOWED_HOSTS=example.com,www.example.com,api.example.com
ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'background_task',  # Django background tasks (simpler than Celery)

    # mCube Trading System Apps
    'apps.core.apps.CoreConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.positions.apps.PositionsConfig',
    'apps.strategies.apps.StrategiesConfig',
    'apps.risk.apps.RiskConfig',
    'apps.data.apps.DataConfig',
    'apps.llm.apps.LlmConfig',
    'apps.analytics.apps.AnalyticsConfig',
    'apps.alerts.apps.AlertsConfig',
    'apps.brokers.apps.BrokersConfig',
    'apps.trading.apps.TradingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middleware
    'apps.core.middleware.URLLoggingMiddleware',
    'apps.core.middleware.ErrorHandlingMiddleware',
    'apps.core.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'mcube_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcube_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # Indian Standard Time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/brokers/login/'  # Use broker login page
LOGIN_REDIRECT_URL = '/'  # Redirect to home page after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to home page after logout


# =============================================================================
# CELERY CONFIGURATION
# =============================================================================

# Celery broker URL (Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Celery result backend (Redis)
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'

# Celery task serialization
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Celery timezone settings
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = False

# Celery task settings
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes max (hard limit)
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes (soft limit - raises exception)
CELERY_TASK_ACKS_LATE = True  # Acknowledge task after execution (not before)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Reject task if worker dies

# Celery result settings
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour

# Celery worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Prefetch 4 tasks per worker
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after 1000 tasks (prevent memory leaks)

# Celery Beat schedule is defined in mcube_ai/celery.py
# This keeps the schedule configuration centralized


# =============================================================================
# TELEGRAM BOT CONFIGURATION
# =============================================================================

# Telegram Bot API settings (for alerts and notifications)
# These should be moved to environment variables in production
TELEGRAM_BOT_TOKEN = '6386769117:AAHt_4krbiU0KlBdCLhhVgC-TCQVUnzvywo'  # @dmcube_bot
TELEGRAM_CHAT_ID = '788423838'  # Will be auto-detected on first message


# =============================================================================
# LLM CONFIGURATION
# =============================================================================

# Ollama LLM settings
OLLAMA_BASE_URL = 'http://localhost:11434'  # Default Ollama URL
OLLAMA_MODEL = 'deepseek-r1:7b'  # DeepSeek R1 7B model

# LLM models directory (for downloaded GGUF files)
LLM_MODELS_DIR = BASE_DIR / 'llm_models'


# =============================================================================
# MARKET DATA CONFIGURATION
# =============================================================================

# Trendlyne API settings
TRENDLYNE_API_KEY = ''  # TODO: Add your Trendlyne API key

# Market hours (IST)
MARKET_OPEN_TIME = '09:15'
MARKET_CLOSE_TIME = '15:30'

# Data refresh intervals (in seconds)
LIVE_DATA_REFRESH_INTERVAL = 300  # 5 minutes
PRE_MARKET_REFRESH_INTERVAL = 600  # 10 minutes


# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'mcube_ai.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
