"""
Position models for mCube Trading System

Unified model for:
- Broker positions (synced from Kotak/Breeze)
- System suggestions (generated by learning engine)
- Manual entries

Status lifecycle: SUGGESTED -> APPROVED -> OPEN -> CLOSED
                           -> REJECTED (if not approved)
"""

from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator

from apps.core.models import TimeStampedModel
from apps.core.constants import (
    DIRECTION_CHOICES,
    POSITION_STATUS_CHOICES,
    POSITION_STATUS_OPEN,
    POSITION_STATUS_CLOSED,
    POSITION_STATUS_SUGGESTED,
    POSITION_STATUS_APPROVED,
    POSITION_SOURCE_CHOICES,
    POSITION_SOURCE_BROKER,
)


class Position(TimeStampedModel):
    """
    Unified Position model for trades and suggestions.

    Supports:
    - Broker synced positions (source=BROKER)
    - System suggestions (source=SYSTEM)
    - Manual entries (source=MANUAL)

    Status Flow:
    - SUGGESTED: Awaiting user approval
    - APPROVED: Approved, pending execution
    - OPEN: Currently active position
    - CLOSED: Position exited
    - REJECTED: User rejected suggestion
    - EXPIRED: Suggestion expired
    """

    # ==========================================================================
    # CORE FIELDS
    # ==========================================================================

    account = models.ForeignKey(
        'accounts.BrokerAccount',
        on_delete=models.CASCADE,
        related_name='positions',
        null=True,
        blank=True,
        help_text="Associated broker account (null for suggestions)"
    )

    instrument = models.CharField(
        max_length=100,
        db_index=True,
        help_text="Original broker symbol used for order placement"
    )

    display_name = models.CharField(
        max_length=100,
        blank=True,
        help_text="Human-friendly name, e.g. HDFCBANK26MARFUT (auto-generated)"
    )

    direction = models.CharField(
        max_length=10,
        choices=DIRECTION_CHOICES,
        help_text="LONG, SHORT, or NEUTRAL"
    )

    quantity = models.IntegerField(
        validators=[MinValueValidator(1)],
        help_text="Total units (e.g. lots × lot_size)"
    )

    lot_size = models.IntegerField(
        default=1,
        help_text="Lot size for the instrument"
    )

    @property
    def lots(self):
        """Number of lots (quantity / lot_size)."""
        ls = self.lot_size or 1
        return self.quantity // ls if ls > 1 else self.quantity

    @property
    def label(self):
        """Display-friendly name; falls back to instrument if not set."""
        return self.display_name or self.instrument

    # ==========================================================================
    # STATUS & SOURCE TRACKING
    # ==========================================================================

    status = models.CharField(
        max_length=20,
        default=POSITION_STATUS_OPEN,
        choices=POSITION_STATUS_CHOICES,
        db_index=True,
        help_text="Position lifecycle status"
    )

    source = models.CharField(
        max_length=20,
        default=POSITION_SOURCE_BROKER,
        choices=POSITION_SOURCE_CHOICES,
        db_index=True,
        help_text="Where this position originated"
    )

    strategy_type = models.CharField(
        max_length=50,
        blank=True,
        help_text="Strategy type (LLM_VALIDATED_FUTURES, WEEKLY_STRANGLE, etc.)"
    )

    # ==========================================================================
    # PRICING
    # ==========================================================================

    entry_price = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        help_text="Entry/suggested price"
    )

    current_price = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="Current market price (LTP)"
    )

    exit_price = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Exit price (when closed)"
    )

    stop_loss = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Stop-loss price"
    )

    target = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Target price"
    )

    # ==========================================================================
    # P&L TRACKING
    # ==========================================================================

    unrealized_pnl = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="Current unrealized P&L"
    )

    realized_pnl = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="Realized P&L (after closing)"
    )

    entry_value = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="Total entry value"
    )

    margin_used = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="Margin blocked"
    )

    # ==========================================================================
    # TIMESTAMPS
    # ==========================================================================

    entry_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When position was opened"
    )

    exit_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When position was closed"
    )

    expiry_date = models.DateField(
        null=True,
        blank=True,
        help_text="Contract expiry date"
    )

    exit_reason = models.CharField(
        max_length=100,
        blank=True,
        help_text="Reason for exit (TARGET, STOP_LOSS, MANUAL, etc.)"
    )

    # ==========================================================================
    # SUGGESTION FIELDS (for SYSTEM source)
    # ==========================================================================

    confidence = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="System confidence score (0-100)"
    )

    suggestion_reason = models.TextField(
        blank=True,
        help_text="Why this trade was suggested"
    )

    supporting_data = models.JSONField(
        null=True,
        blank=True,
        help_text="Technical indicators, patterns, etc."
    )

    reviewed_by = models.ForeignKey(
        'auth.User',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_positions',
        help_text="User who approved/rejected"
    )

    reviewed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When suggestion was reviewed"
    )

    rejection_reason = models.TextField(
        blank=True,
        help_text="Why suggestion was rejected"
    )

    # ==========================================================================
    # BROKER SYNC FIELDS
    # ==========================================================================

    broker_position_id = models.CharField(
        max_length=100,
        blank=True,
        help_text="Position ID from broker API"
    )

    exchange_segment = models.CharField(
        max_length=20,
        blank=True,
        help_text="Exchange segment (nse_fo, nse_cm, etc.)"
    )

    product_type = models.CharField(
        max_length=20,
        blank=True,
        help_text="Product type (NRML, MIS, CNC)"
    )

    last_synced_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Last sync from broker"
    )

    # ==========================================================================
    # OPTIONS-SPECIFIC FIELDS
    # ==========================================================================

    call_strike = models.DecimalField(
        max_digits=15, decimal_places=2, null=True, blank=True
    )
    put_strike = models.DecimalField(
        max_digits=15, decimal_places=2, null=True, blank=True
    )
    call_premium = models.DecimalField(
        max_digits=15, decimal_places=2, null=True, blank=True
    )
    put_premium = models.DecimalField(
        max_digits=15, decimal_places=2, null=True, blank=True
    )
    premium_collected = models.DecimalField(
        max_digits=15, decimal_places=2, default=Decimal('0.00')
    )
    current_delta = models.DecimalField(
        max_digits=10, decimal_places=4, default=Decimal('0.0000')
    )

    # ==========================================================================
    # AVERAGING FIELDS
    # ==========================================================================

    averaging_count = models.IntegerField(default=0)
    original_entry_price = models.DecimalField(
        max_digits=15, decimal_places=2, null=True, blank=True
    )
    partial_booked = models.BooleanField(default=False)
    partial_quantity = models.IntegerField(default=0)

    # ==========================================================================
    # METADATA
    # ==========================================================================

    notes = models.TextField(blank=True)

    class Meta:
        db_table = 'positions'
        verbose_name = 'Position'
        verbose_name_plural = 'Positions'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['status', 'source']),
            models.Index(fields=['account', 'status']),
            models.Index(fields=['instrument', 'status']),
            models.Index(fields=['status', 'expiry_date']),
        ]

    def __str__(self):
        return f"{self.label} {self.direction} ({self.get_status_display()})"

    # ==========================================================================
    # CLASS METHODS
    # ==========================================================================

    @classmethod
    def get_open_positions(cls, account=None):
        """Get all open positions, optionally filtered by account."""
        qs = cls.objects.filter(status=POSITION_STATUS_OPEN)
        if account:
            qs = qs.filter(account=account)
        return qs

    @classmethod
    def get_suggestions(cls, status=None):
        """Get system suggestions."""
        from apps.core.constants import POSITION_SOURCE_SYSTEM
        qs = cls.objects.filter(source=POSITION_SOURCE_SYSTEM)
        if status:
            qs = qs.filter(status=status)
        return qs

    @classmethod
    def get_pending_suggestions(cls):
        """Get suggestions awaiting approval."""
        return cls.get_suggestions(status=POSITION_STATUS_SUGGESTED)

    @classmethod
    def has_open_position(cls, account) -> bool:
        """Check if account has any open position."""
        return cls.objects.filter(
            account=account,
            status=POSITION_STATUS_OPEN
        ).exists()

    # Legacy alias
    @classmethod
    def has_active_position(cls, account) -> bool:
        return cls.has_open_position(account)

    @classmethod
    def get_active_position(cls, account):
        return cls.objects.filter(
            account=account,
            status=POSITION_STATUS_OPEN
        ).first()

    # ==========================================================================
    # INSTANCE METHODS
    # ==========================================================================

    def approve(self, user):
        """Approve a suggestion."""
        from django.utils import timezone
        if self.status != POSITION_STATUS_SUGGESTED:
            raise ValueError("Only SUGGESTED positions can be approved")
        self.status = POSITION_STATUS_APPROVED
        self.reviewed_by = user
        self.reviewed_at = timezone.now()
        self.save()

    def reject(self, user, reason=''):
        """Reject a suggestion."""
        from django.utils import timezone
        from apps.core.constants import POSITION_STATUS_REJECTED
        if self.status != POSITION_STATUS_SUGGESTED:
            raise ValueError("Only SUGGESTED positions can be rejected")
        self.status = POSITION_STATUS_REJECTED
        self.reviewed_by = user
        self.reviewed_at = timezone.now()
        self.rejection_reason = reason
        self.save()

    def open_position(self, entry_price=None):
        """Mark position as opened."""
        from django.utils import timezone
        if self.status not in [POSITION_STATUS_APPROVED, POSITION_STATUS_SUGGESTED]:
            raise ValueError("Position must be APPROVED or SUGGESTED to open")
        self.status = POSITION_STATUS_OPEN
        self.entry_time = timezone.now()
        if entry_price:
            self.entry_price = entry_price
        self.save()

    def close_position(self, exit_price: Decimal, exit_reason: str = "MANUAL"):
        """Close the position."""
        from django.utils import timezone
        self.exit_price = exit_price
        self.exit_time = timezone.now()
        self.exit_reason = exit_reason
        self.status = POSITION_STATUS_CLOSED
        self.realized_pnl = self.calculate_pnl(exit_price)
        self.unrealized_pnl = Decimal('0.00')
        self.save()

    def calculate_pnl(self, price=None) -> Decimal:
        """Calculate P&L at given price.

        Note: quantity stores total shares (not lots), so lot_size is NOT
        multiplied again.  E.g. 305 lots of HDFCBANK (lot_size=550) is
        stored as quantity=167750.
        """
        price = price or self.current_price
        if self.direction == 'LONG':
            pnl_per_unit = price - self.entry_price
        elif self.direction == 'SHORT':
            pnl_per_unit = self.entry_price - price
        else:  # NEUTRAL
            pnl_per_unit = self.premium_collected - price
        return pnl_per_unit * self.quantity

    def update_price(self, price: Decimal):
        """Update current price and unrealized P&L."""
        self.current_price = price
        if self.status == POSITION_STATUS_OPEN:
            self.unrealized_pnl = self.calculate_pnl(price)
        self.save(update_fields=['current_price', 'unrealized_pnl', 'updated_at'])

    def is_stop_loss_hit(self) -> bool:
        if self.status != POSITION_STATUS_OPEN or not self.stop_loss:
            return False
        if self.direction == 'LONG':
            return self.current_price <= self.stop_loss
        elif self.direction == 'SHORT':
            return self.current_price >= self.stop_loss
        return self.current_price >= self.stop_loss

    def is_target_hit(self) -> bool:
        if self.status != POSITION_STATUS_OPEN or not self.target:
            return False
        if self.direction == 'LONG':
            return self.current_price >= self.target
        elif self.direction == 'SHORT':
            return self.current_price <= self.target
        return self.current_price <= self.target


class MonitorLog(TimeStampedModel):
    """Position monitoring log for alerts and checks."""

    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        related_name='monitor_logs'
    )
    check_type = models.CharField(max_length=50)
    result = models.CharField(max_length=20)
    message = models.TextField()
    action_taken = models.CharField(max_length=100, blank=True)
    price_at_check = models.DecimalField(
        max_digits=15, decimal_places=2, null=True, blank=True
    )
    pnl_at_check = models.DecimalField(
        max_digits=15, decimal_places=2, null=True, blank=True
    )

    class Meta:
        db_table = 'monitor_logs'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.check_type} - {self.result}"


class PositionMonitorDashboard(TimeStampedModel):
    """
    Daily monitoring dashboard state for anti-spam Telegram updates.

    One record per trading day. The monitor task edits a single Telegram
    message instead of flooding the chat with per-minute updates.

    Stores:
    - The Telegram message_id so we can EDIT it each run
    - Day-start snapshot (first reading of the day)
    - Last 3 monitoring snapshots (rolling window, shows progression)
    - Last exit suggestion details (deduplication)
    """

    date = models.DateField(
        db_index=True,
        help_text="Trading date"
    )
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='monitor_dashboards',
        help_text="Position being monitored"
    )

    # Telegram message tracking
    telegram_message_id = models.BigIntegerField(
        null=True,
        blank=True,
        help_text="Message ID of the live monitoring dashboard message"
    )

    # Snapshots
    day_start = models.JSONField(
        null=True,
        blank=True,
        help_text="Snapshot at day start: {time, price, pnl, pnl_pct}"
    )
    snapshots = models.JSONField(
        default=list,
        help_text="Last 3 monitoring snapshots [{time, price, pnl, pnl_pct}]"
    )

    last_updated = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When dashboard was last refreshed"
    )

    # S/R exit engine intraday state
    sr_tracking = models.JSONField(
        null=True,
        blank=True,
        help_text=(
            "Intraday S/R engine state: "
            "{session_low, session_high, last_sr_computed_at, sr_cache, "
            "condition_b_met_at, gap_detected}"
        )
    )

    # Exit suggestion deduplication
    last_exit_msg_id = models.BigIntegerField(
        null=True,
        blank=True,
        help_text="Telegram message_id of last exit suggestion (for tracking)"
    )
    last_exit_reason = models.CharField(
        max_length=50,
        blank=True,
        help_text="Reason of last exit suggestion sent"
    )
    last_exit_sent_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When last exit suggestion was sent"
    )

    class Meta:
        db_table = 'position_monitor_dashboard'
        ordering = ['-date']
        unique_together = [('position', 'date')]

    def __str__(self):
        pos_str = self.position.label if self.position else 'No position'
        return f"Dashboard {self.date} | {pos_str}"


class PortfolioPnlTracker(TimeStampedModel):
    """
    Daily portfolio-level P&L snapshots for the Open Positions trend display.

    One row per trading day. Stores timestamped total P&L readings taken every
    auto-refresh cycle (~2 min). The web UI uses these to show P&L movement
    (Δ1, Δ5, Δ10, Day) across page refreshes and devices.

    Snapshots format: [{pnl: float, ts: epoch_ms}, ...]
    """

    date = models.DateField(
        unique=True,
        db_index=True,
        help_text="Trading date"
    )
    snapshots = models.JSONField(
        default=list,
        help_text="Timestamped P&L readings: [{pnl, ts}, ...]"
    )

    class Meta:
        db_table = 'portfolio_pnl_tracker'
        ordering = ['-date']

    def __str__(self):
        count = len(self.snapshots) if self.snapshots else 0
        return f"PnL Tracker {self.date} | {count} snapshots"
