# Generated by Django 3.1.7 on 2025-11-15 09:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('broker', models.CharField(choices=[('KOTAK', 'Kotak Securities'), ('ICICI', 'ICICI Securities')], help_text='Broker name (KOTAK or ICICI)', max_length=20)),
                ('fetched_at', models.DateTimeField(help_text='When this data was fetched from broker API')),
                ('bank_account', models.CharField(blank=True, help_text='Bank account number (Breeze)', max_length=50)),
                ('total_bank_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total bank balance (Breeze)', max_digits=15)),
                ('allocated_equity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allocated for equity trading (Breeze)', max_digits=15)),
                ('allocated_fno', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allocated for F&O trading (Breeze)', max_digits=15)),
                ('block_by_trade_fno', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Margin blocked by F&O trades (Breeze)', max_digits=15)),
                ('unallocated_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unallocated balance (Breeze)', max_digits=15)),
                ('category', models.CharField(blank=True, help_text='Account category (Neo)', max_length=100)),
                ('net_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net account balance (Neo)', max_digits=15)),
                ('collateral_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total collateral value (Neo)', max_digits=15)),
                ('margin_used_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of margin used (Neo)', max_digits=5)),
                ('margin_warning_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Margin warning percentage (Neo)', max_digits=5)),
                ('exposure_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exposure margin percentage (Neo)', max_digits=5)),
                ('span_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SPAN margin percentage (Neo)', max_digits=5)),
                ('board_lot_limit', models.IntegerField(default=0, help_text='Board lot limit (Neo)')),
                ('margin_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available margin for trading', max_digits=15)),
                ('margin_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Margin currently used', max_digits=15)),
            ],
            options={
                'verbose_name': 'Broker Limit',
                'verbose_name_plural': 'Broker Limits',
                'db_table': 'broker_limits',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('broker', models.CharField(choices=[('KOTAK', 'Kotak Securities'), ('ICICI', 'ICICI Securities')], help_text='Broker name (KOTAK or ICICI)', max_length=20)),
                ('fetched_at', models.DateTimeField(help_text='When this position was fetched from broker API')),
                ('symbol', models.CharField(help_text='Trading symbol (e.g., NIFTY25DEC2025025000CE)', max_length=100)),
                ('exchange_segment', models.CharField(blank=True, help_text='Exchange segment (e.g., nse_fo, bse_fo)', max_length=50)),
                ('product', models.CharField(blank=True, help_text='Product type (e.g., MIS, NRML, CNC)', max_length=50)),
                ('buy_qty', models.IntegerField(default=0, help_text='Total buy quantity')),
                ('sell_qty', models.IntegerField(default=0, help_text='Total sell quantity')),
                ('net_quantity', models.IntegerField(default=0, help_text='Net quantity (buy_qty - sell_qty)')),
                ('buy_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total buy amount', max_digits=15)),
                ('sell_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sell amount', max_digits=15)),
                ('ltp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Last traded price', max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average entry price', max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Realized profit/loss', max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unrealized profit/loss (MTM)', max_digits=15)),
            ],
            options={
                'verbose_name': 'Broker Position',
                'verbose_name_plural': 'Broker Positions',
                'db_table': 'broker_positions',
                'ordering': ['-fetched_at', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('datetime', models.DateTimeField(db_index=True, help_text='Candle timestamp')),
                ('stock_code', models.CharField(help_text='Stock/index code (e.g., NIFTY, ICICIBANK)', max_length=50)),
                ('exchange_code', models.CharField(help_text='Exchange code (NSE, NFO, BSE)', max_length=10)),
                ('product_type', models.CharField(help_text='Product type (cash, futures, options)', max_length=20)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (for futures/options)', null=True)),
                ('right', models.CharField(blank=True, help_text='Option right (call/put, empty for futures/cash)', max_length=10)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, help_text='Strike price (for options)', max_digits=10, null=True)),
                ('open', models.DecimalField(decimal_places=2, help_text='Open price', max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, help_text='High price', max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, help_text='Low price', max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, help_text='Close price', max_digits=15)),
                ('volume', models.BigIntegerField(default=0, help_text='Volume traded')),
                ('open_interest', models.BigIntegerField(default=0, help_text='Open interest (for derivatives)')),
            ],
            options={
                'verbose_name': 'Historical Price',
                'verbose_name_plural': 'Historical Prices',
                'db_table': 'historical_prices',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='OptionChainQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('exchange_code', models.CharField(help_text='Exchange code (e.g., NFO, NSE)', max_length=10)),
                ('product_type', models.CharField(help_text='Product type (options, futures)', max_length=20)),
                ('stock_code', models.CharField(help_text='Stock/index code (e.g., NIFTY, BANKNIFTY)', max_length=50)),
                ('expiry_date', models.DateField(help_text='Option expiry date')),
                ('right', models.CharField(help_text='Option right (call or put)', max_length=10)),
                ('strike_price', models.DecimalField(decimal_places=2, help_text='Strike price', max_digits=10)),
                ('ltp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Last traded price', max_digits=15)),
                ('best_bid_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Best bid price', max_digits=15)),
                ('best_offer_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Best offer price', max_digits=15)),
                ('open', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening price', max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='High price', max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Low price', max_digits=15)),
                ('previous_close', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Previous close price', max_digits=15)),
                ('open_interest', models.BigIntegerField(default=0, help_text='Open interest')),
                ('total_quantity_traded', models.BigIntegerField(default=0, help_text='Total quantity traded')),
                ('spot_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Underlying spot price at time of fetch', max_digits=15)),
            ],
            options={
                'verbose_name': 'Option Chain Quote',
                'verbose_name_plural': 'Option Chain Quotes',
                'db_table': 'option_chain_quotes',
                'ordering': ['-created_at', 'expiry_date', 'strike_price'],
            },
        ),
        migrations.AddIndex(
            model_name='optionchainquote',
            index=models.Index(fields=['stock_code', 'expiry_date', '-created_at'], name='option_chai_stock_c_22b4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='optionchainquote',
            index=models.Index(fields=['strike_price', 'right'], name='option_chai_strike__880fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalprice',
            index=models.Index(fields=['stock_code', 'product_type', '-datetime'], name='historical__stock_c_d7837e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalprice',
            index=models.Index(fields=['datetime'], name='historical__datetim_02f566_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalprice',
            unique_together={('datetime', 'stock_code', 'exchange_code', 'product_type', 'expiry_date', 'right', 'strike_price')},
        ),
        migrations.AddIndex(
            model_name='brokerposition',
            index=models.Index(fields=['broker', '-fetched_at'], name='broker_posi_broker_2f6672_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerposition',
            index=models.Index(fields=['symbol', '-fetched_at'], name='broker_posi_symbol_9c52f4_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerlimit',
            index=models.Index(fields=['broker', '-fetched_at'], name='broker_limi_broker_bf0cd8_idx'),
        ),
    ]
