# Generated by Django 4.2.7 on 2025-11-17 09:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_alter_brokerlimit_id_alter_brokerposition_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NiftyOptionChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("expiry_date", models.DateField(help_text="Option expiry date")),
                (
                    "strike_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Strike price", max_digits=10
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("CE", "Call"), ("PE", "Put")],
                        help_text="Option type (CE or PE)",
                        max_length=10,
                    ),
                ),
                (
                    "call_ltp",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Call LTP",
                        max_digits=15,
                    ),
                ),
                (
                    "call_bid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Call best bid price",
                        max_digits=15,
                    ),
                ),
                (
                    "call_ask",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Call best ask price",
                        max_digits=15,
                    ),
                ),
                (
                    "call_oi",
                    models.BigIntegerField(default=0, help_text="Call open interest"),
                ),
                (
                    "call_volume",
                    models.BigIntegerField(default=0, help_text="Call volume"),
                ),
                (
                    "put_ltp",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Put LTP",
                        max_digits=15,
                    ),
                ),
                (
                    "put_bid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Put best bid price",
                        max_digits=15,
                    ),
                ),
                (
                    "put_ask",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Put best ask price",
                        max_digits=15,
                    ),
                ),
                (
                    "put_oi",
                    models.BigIntegerField(default=0, help_text="Put open interest"),
                ),
                (
                    "put_volume",
                    models.BigIntegerField(default=0, help_text="Put volume"),
                ),
                (
                    "spot_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Nifty spot price at time of fetch",
                        max_digits=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nifty Option Chain",
                "verbose_name_plural": "Nifty Option Chains",
                "db_table": "nifty_option_chain",
                "ordering": ["-created_at", "expiry_date", "strike_price"],
                "indexes": [
                    models.Index(
                        fields=["expiry_date", "strike_price"],
                        name="nifty_optio_expiry__127a45_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="nifty_optio_created_c3b95a_idx"
                    ),
                ],
            },
        ),
    ]
