# Generated by Django 4.2.7 on 2025-11-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0003_niftyoptionchain"),
    ]

    operations = [
        migrations.AddField(
            model_name="niftyoptionchain",
            name="call_delta",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Call Delta (0 to 1)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="call_gamma",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Call Gamma",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="call_iv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Call Implied Volatility %",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="call_oi_change",
            field=models.BigIntegerField(
                default=0, help_text="Call OI change from previous day"
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="call_theta",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Call Theta",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="call_vega",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Call Vega",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="distance_from_spot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance from spot price (strike - spot)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="is_atm",
            field=models.BooleanField(
                default=False, help_text="True if this is ATM strike"
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="pcr_oi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="PCR based on OI (Put OI / Call OI)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="pcr_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="PCR based on volume (Put Vol / Call Vol)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="put_delta",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Put Delta (-1 to 0)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="put_gamma",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Put Gamma",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="put_iv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Put Implied Volatility %",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="put_oi_change",
            field=models.BigIntegerField(
                default=0, help_text="Put OI change from previous day"
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="put_theta",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Put Theta",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftyoptionchain",
            name="put_vega",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Put Vega",
                max_digits=8,
                null=True,
            ),
        ),
    ]
