# Generated by Django 4.2.7 on 2026-01-23 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_apicredential"),
        ("positions", "0005_make_stop_loss_target_optional"),
        ("brokers", "0005_order_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when the record was created",
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="exchange",
            field=models.CharField(
                blank=True, help_text="Exchange where executed", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="exchange_timestamp",
            field=models.DateTimeField(help_text="Execution timestamp from exchange"),
        ),
        migrations.AlterField(
            model_name="execution",
            name="execution_id",
            field=models.CharField(
                help_text="Unique execution ID from broker", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="order",
            field=models.ForeignKey(
                help_text="Associated order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="brokers.order",
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Execution price", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="quantity",
            field=models.IntegerField(
                help_text="Quantity filled in this execution",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="transaction_type",
            field=models.CharField(help_text="BUY or SELL", max_length=10),
        ),
        migrations.AlterField(
            model_name="execution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="account",
            field=models.ForeignKey(
                help_text="Associated broker account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.brokeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="average_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average execution price",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="broker_order_id",
            field=models.CharField(
                blank=True, help_text="Order ID from broker", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was cancelled", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when the record was created",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="direction",
            field=models.CharField(
                choices=[("LONG", "Long"), ("SHORT", "Short"), ("NEUTRAL", "Neutral")],
                help_text="Order direction (LONG or SHORT)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="exchange",
            field=models.CharField(
                default="NSE", help_text="Exchange (NSE, BSE, NFO)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="filled_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was fully filled", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="filled_quantity",
            field=models.IntegerField(default=0, help_text="Quantity filled"),
        ),
        migrations.AlterField(
            model_name="order",
            name="instrument",
            field=models.CharField(help_text="Instrument symbol", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="message",
            field=models.TextField(blank=True, help_text="Status message from broker"),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, help_text="Any additional notes"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("MARKET", "Market"),
                    ("LIMIT", "Limit"),
                    ("SL", "Stop Loss"),
                    ("SLM", "Stop Loss Market"),
                ],
                help_text="Order type (MARKET, LIMIT, SL, SLM)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="placed_at",
            field=models.DateTimeField(
                blank=True, help_text="When order was placed with broker", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated position (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="positions.position",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Order price (for LIMIT orders)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="purpose",
            field=models.CharField(
                blank=True,
                help_text="Purpose (ENTRY, EXIT, AVERAGING, ADJUSTMENT)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(
                help_text="Order quantity",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PLACED", "Placed"),
                    ("FILLED", "Filled"),
                    ("PARTIAL", "Partially Filled"),
                    ("CANCELLED", "Cancelled"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Order status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="trigger_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Trigger price (for SL orders)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        # NOTE: AddIndex operations removed - indexes already exist in database
        # migrations.AddIndex(model_name="execution", index=models.Index(fields=["order", "exchange_timestamp"], name="executions_order_i_5ef1c4_idx")),
        # migrations.AddIndex(model_name="order", index=models.Index(fields=["account", "status"], name="orders_account_ca00e7_idx")),
        # migrations.AddIndex(model_name="order", index=models.Index(fields=["broker_order_id"], name="orders_broker__a04e54_idx")),
    ]
