# Generated by Django 4.2.7 on 2026-01-23 06:10
# Modified: Use SeparateDatabaseAndState since indexes already exist in database

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "brokers",
            "0006_alter_execution_created_at_alter_execution_exchange_and_more",
        ),
    ]

    operations = [
        # Use SeparateDatabaseAndState to only update Django's state, not database
        # since these indexes already exist from previous migration attempts
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="execution",
                    index=models.Index(
                        fields=["order", "exchange_timestamp"],
                        name="executions_order_i_5ef1c4_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="order",
                    index=models.Index(
                        fields=["account", "status"],
                        name="orders_account_ca00e7_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="order",
                    index=models.Index(
                        fields=["broker_order_id"],
                        name="orders_broker__a04e54_idx",
                    ),
                ),
            ],
            database_operations=[],  # No database changes needed - indexes exist
        ),
    ]
