# Generated by Django 4.2.7 on 2026-01-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0007_execution_executions_order_i_5ef1c4_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="historicalprice",
            name="historical__stock_c_d7837e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="historicalprice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historicalprice",
            name="interval",
            field=models.CharField(
                default="1day",
                help_text="Candle interval (1minute, 5minute, 30minute, 1day)",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="historicalprice",
            unique_together={
                (
                    "datetime",
                    "stock_code",
                    "exchange_code",
                    "product_type",
                    "interval",
                    "expiry_date",
                    "right",
                    "strike_price",
                )
            },
        ),
        migrations.AddIndex(
            model_name="historicalprice",
            index=models.Index(
                fields=[
                    "stock_code",
                    "exchange_code",
                    "product_type",
                    "interval",
                    "-datetime",
                ],
                name="historical__stock_c_56efab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalprice",
            index=models.Index(
                fields=["stock_code", "expiry_date", "strike_price"],
                name="historical__stock_c_7856e3_idx",
            ),
        ),
    ]
