# Generated by Django 4.2.7 on 2026-01-27 09:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_apicredential"),
        (
            "brokers",
            "0008_remove_historicalprice_historical__stock_c_d7837e_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerTradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("KOTAK", "Kotak Neo"), ("ICICI", "ICICI Breeze")],
                        help_text="Broker name",
                        max_length=10,
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(help_text="Trade ID from broker", max_length=100),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True, help_text="Order ID from broker", max_length=100
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Base symbol (e.g., NIFTY, RELIANCE)", max_length=50
                    ),
                ),
                (
                    "trading_symbol",
                    models.CharField(
                        help_text="Full trading symbol (e.g., NIFTY25JAN23500CE)",
                        max_length=100,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("NFO", "NSE F&O"),
                            ("NSE", "NSE Cash"),
                            ("BSE", "BSE Cash"),
                            ("BFO", "BSE F&O"),
                        ],
                        default="NFO",
                        help_text="Exchange segment",
                        max_length=10,
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        help_text="Buy or Sell",
                        max_length=10,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("NRML", "Normal"),
                            ("MIS", "Intraday"),
                            ("CNC", "Delivery"),
                        ],
                        default="NRML",
                        help_text="Product type",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Trade quantity")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Trade price", max_digits=15
                    ),
                ),
                (
                    "trade_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total trade value (quantity * price)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("trade_date", models.DateField(help_text="Trade execution date")),
                (
                    "trade_time",
                    models.TimeField(
                        blank=True, help_text="Trade execution time", null=True
                    ),
                ),
                (
                    "trade_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Combined trade datetime", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Expiry date for F&O", null=True
                    ),
                ),
                (
                    "strike_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strike price for options",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        blank=True, help_text="CE or PE for options", max_length=5
                    ),
                ),
                (
                    "brokerage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Brokerage charges",
                        max_digits=12,
                    ),
                ),
                (
                    "stt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Securities Transaction Tax",
                        max_digits=12,
                    ),
                ),
                (
                    "exchange_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Exchange transaction charges",
                        max_digits=12,
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="GST on brokerage",
                        max_digits=12,
                    ),
                ),
                (
                    "stamp_duty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Stamp duty",
                        max_digits=12,
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total of all charges",
                        max_digits=12,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw response data from broker API",
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(
                        default=False, help_text="Whether matched with TakenTrade"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Associated broker account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_history",
                        to="accounts.brokeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker Trade History",
                "verbose_name_plural": "Broker Trade Histories",
                "db_table": "broker_trade_history",
                "ordering": ["-trade_date", "-trade_time"],
            },
        ),
    ]
