# Generated by Django 4.2.7 on 2026-01-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0009_brokertradehistory"),
        ("trading", "0007_takentrade_takentrade_unique_user_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokertradehistory",
            name="taken_trade",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked TakenTrade if reconciled",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broker_trades",
                to="trading.takentrade",
            ),
        ),
        migrations.AddIndex(
            model_name="brokertradehistory",
            index=models.Index(
                fields=["account", "trade_date"], name="broker_trad_account_76fde8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokertradehistory",
            index=models.Index(
                fields=["broker", "trade_date"], name="broker_trad_broker_6d0a24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokertradehistory",
            index=models.Index(
                fields=["symbol", "trade_date"], name="broker_trad_symbol_37e57e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokertradehistory",
            index=models.Index(
                fields=["is_reconciled"], name="broker_trad_is_reco_dffce0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brokertradehistory",
            constraint=models.UniqueConstraint(
                fields=("broker", "trade_id", "trade_date"), name="unique_broker_trade"
            ),
        ),
    ]
