# Generated by Django 4.2.7 on 2026-01-30 11:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brokers", "0010_brokertradehistory_taken_trade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "import_batch_id",
                    models.CharField(
                        help_text="Unique batch ID for grouping imports",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("KOTAK_FNO", "Kotak F&O Gain/Loss"),
                            ("BREEZE_FNO", "Breeze FNO Portfolio"),
                        ],
                        help_text="Type of CSV file imported",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename uploaded", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Import status",
                        max_length=20,
                    ),
                ),
                (
                    "records_created",
                    models.IntegerField(
                        default=0, help_text="Number of records created"
                    ),
                ),
                (
                    "records_updated",
                    models.IntegerField(
                        default=0, help_text="Number of records updated"
                    ),
                ),
                (
                    "records_skipped",
                    models.IntegerField(
                        default=0, help_text="Number of records skipped"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True, default=list, help_text="List of error messages"
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the import",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CSV Import Log",
                "verbose_name_plural": "CSV Import Logs",
                "db_table": "csv_import_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrokerContractPnL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("KOTAK", "Kotak Neo"), ("ICICI", "ICICI Breeze")],
                        help_text="Broker name",
                        max_length=10,
                    ),
                ),
                (
                    "import_batch_id",
                    models.CharField(
                        db_index=True,
                        help_text="Links to CSVImportLog batch",
                        max_length=50,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Base symbol (e.g., NIFTY, BANKNIFTY, HDFCBANK)",
                        max_length=50,
                    ),
                ),
                (
                    "trading_symbol",
                    models.CharField(
                        help_text="Full contract name from CSV", max_length=200
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[("FUTURES", "Futures"), ("OPTIONS", "Options")],
                        help_text="FUTURES or OPTIONS",
                        max_length=10,
                    ),
                ),
                (
                    "security_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FUTSTK", "Stock Futures"),
                            ("FUTIDX", "Index Futures"),
                            ("OPTSTK", "Stock Options"),
                            ("OPTIDX", "Index Options"),
                        ],
                        help_text="Detailed security type from Kotak CSV",
                        max_length=10,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Contract expiry date", null=True
                    ),
                ),
                (
                    "strike_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strike price for options",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        blank=True, help_text="CE or PE for options", max_length=5
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, help_text="Total traded quantity"),
                ),
                (
                    "buy_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total buy value",
                        max_digits=15,
                    ),
                ),
                (
                    "sell_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total sell value",
                        max_digits=15,
                    ),
                ),
                (
                    "gross_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross P&L before charges",
                        max_digits=15,
                    ),
                ),
                (
                    "net_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Net P&L after all charges",
                        max_digits=15,
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="GST charges",
                        max_digits=12,
                    ),
                ),
                (
                    "brokerage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Brokerage charges",
                        max_digits=12,
                    ),
                ),
                (
                    "stt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Securities Transaction Tax",
                        max_digits=12,
                    ),
                ),
                (
                    "misc_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Other miscellaneous charges",
                        max_digits=12,
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total of all charges",
                        max_digits=12,
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Realized P&L (Breeze)",
                        max_digits=15,
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Unrealized P&L (Breeze)",
                        max_digits=15,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Original CSV row as JSON"
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker Contract PnL",
                "verbose_name_plural": "Broker Contract PnL",
                "db_table": "broker_contract_pnl",
                "ordering": ["-created_at", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["broker", "import_batch_id"],
                        name="broker_cont_broker_872023_idx",
                    ),
                    models.Index(
                        fields=["symbol", "expiry_date"],
                        name="broker_cont_symbol_a6a20e_idx",
                    ),
                    models.Index(
                        fields=["segment"], name="broker_cont_segment_818468_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="brokercontractpnl",
            constraint=models.UniqueConstraint(
                fields=("broker", "import_batch_id", "trading_symbol"),
                name="unique_contract_per_import",
            ),
        ),
    ]
