# Generated by Django 4.2.7 on 2026-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0011_csv_import_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokercontractpnl",
            name="security_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FUTSTK", "Stock Futures"),
                    ("FUTIDX", "Index Futures"),
                    ("OPTSTK", "Stock Options"),
                    ("OPTIDX", "Index Options"),
                    ("EQUITY_STOCK", "Equity Stock"),
                    ("MUTUAL_FUND", "Mutual Fund"),
                    ("ETF", "ETF"),
                ],
                help_text="Detailed security type from Kotak CSV",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="brokercontractpnl",
            name="segment",
            field=models.CharField(
                choices=[
                    ("FUTURES", "Futures"),
                    ("OPTIONS", "Options"),
                    ("EQUITY", "Equity"),
                    ("MUTUAL_FUND", "Mutual Fund"),
                    ("ETF", "ETF"),
                ],
                help_text="FUTURES, OPTIONS, EQUITY, MUTUAL_FUND, or ETF",
                max_length=15,
            ),
        ),
    ]
