# Generated by Django 3.1.7 on 2026-01-31 09:40

from django.db import migrations, models


def merge_duplicate_contracts(apps, schema_editor):
    """
    Merge duplicate contracts (same broker + trading_symbol) before adding unique constraint.
    Keeps the record with the latest updated_at and deletes duplicates.
    """
    BrokerContractPnL = apps.get_model('brokers', 'BrokerContractPnL')

    # Find duplicates: group by broker + trading_symbol
    from django.db.models import Count

    duplicates = (
        BrokerContractPnL.objects
        .values('broker', 'trading_symbol')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        # Get all records for this broker + trading_symbol
        records = BrokerContractPnL.objects.filter(
            broker=dup['broker'],
            trading_symbol=dup['trading_symbol']
        ).order_by('-updated_at')  # Latest first

        # Keep the first (latest), delete the rest
        records_to_delete = list(records[1:].values_list('id', flat=True))
        if records_to_delete:
            BrokerContractPnL.objects.filter(id__in=records_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0012_alter_brokercontractpnl_security_type_and_more'),
    ]

    operations = [
        # First, remove the old constraint
        migrations.RemoveConstraint(
            model_name='brokercontractpnl',
            name='unique_contract_per_import',
        ),

        # Merge any duplicate records before adding new constraint
        migrations.RunPython(merge_duplicate_contracts, migrations.RunPython.noop),

        # Add new index for fast lookups
        migrations.AddIndex(
            model_name='brokercontractpnl',
            index=models.Index(fields=['broker', 'trading_symbol'], name='broker_cont_broker_1d1261_idx'),
        ),

        # Add new unique constraint
        migrations.AddConstraint(
            model_name='brokercontractpnl',
            constraint=models.UniqueConstraint(fields=('broker', 'trading_symbol'), name='unique_contract_per_broker'),
        ),
    ]
