# Generated by Django 3.1.7 on 2026-02-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0018_auto_20260205_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerposition',
            name='lot_size',
            field=models.IntegerField(default=1, help_text='Lot size from broker API (e.g., 65 for NIFTY)'),
        ),
    ]
