# Generated by Django 4.2.7 on 2026-02-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0020_alter_brokercontractpnl_id_alter_brokerlimit_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionAvgOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_symbol", models.CharField(max_length=100, unique=True)),
                (
                    "manual_avg_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Position Avg Override",
            },
        ),
    ]
