# Generated by Django 4.2.7 on 2026-04-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0012_alter_position_options_alter_position_managers_and_more"),
        ("accounts", "0004_alter_brokeraccount_broker"),
        ("brokers", "0021_add_position_avg_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerlimit",
            name="broker",
            field=models.CharField(
                choices=[
                    ("KOTAK", "Kotak Securities"),
                    ("ICICI", "ICICI Securities"),
                    ("PAPER", "Paper Trading"),
                ],
                help_text="Broker name (KOTAK or ICICI)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="brokerposition",
            name="broker",
            field=models.CharField(
                choices=[
                    ("KOTAK", "Kotak Securities"),
                    ("ICICI", "ICICI Securities"),
                    ("PAPER", "Paper Trading"),
                ],
                help_text="Broker name (KOTAK or ICICI)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaperOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        help_text="UUID-based paper order identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(help_text="B (Buy) or S (Sell)", max_length=5),
                ),
                ("quantity", models.IntegerField()),
                (
                    "order_type",
                    models.CharField(help_text="MKT, LIMIT, SL", max_length=10),
                ),
                (
                    "requested_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Limit / SL price requested (0 for market)",
                        max_digits=15,
                    ),
                ),
                (
                    "fill_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Simulated fill price after slippage",
                        max_digits=15,
                    ),
                ),
                (
                    "slippage_applied",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Slippage amount (in price terms)",
                        max_digits=15,
                    ),
                ),
                (
                    "ltp_at_fill",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Market LTP at time of simulated fill",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="FILLED",
                        help_text="FILLED, REJECTED, CANCELLED",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_orders",
                        to="accounts.brokeraccount",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paper_orders",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper Order",
                "verbose_name_plural": "Paper Orders",
                "db_table": "paper_orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
