# Generated by Django 4.2.7 on 2025-11-16 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("positions", "0004_alter_monitorlog_id_alter_position_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionMonitorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_time", models.DateTimeField()),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "unrealized_pnl_pct",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                (
                    "call_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "put_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("sl_hit", models.BooleanField(default=False)),
                ("target_hit", models.BooleanField(default=False)),
                ("action", models.CharField(default="HOLD", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_snapshots",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Position Monitor Snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptionsTestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nifty_spot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("india_vix", models.DecimalField(decimal_places=2, max_digits=8)),
                ("days_to_expiry", models.IntegerField()),
                (
                    "available_margin",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("active_positions", models.IntegerField(default=0)),
                ("adjusted_delta", models.DecimalField(decimal_places=4, max_digits=6)),
                ("call_strike", models.IntegerField()),
                ("put_strike", models.IntegerField()),
                (
                    "premium_collected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("filter_results", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "Passed All Filters"),
                            ("fail", "Failed Filter"),
                            ("error", "Calculation Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("decision", models.CharField(max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Options Test Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FuturesTestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "oi_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sector_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "technical_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "composite_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("factor_details", models.JSONField(default=dict)),
                (
                    "llm_confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("llm_recommendation", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("qualified", "Qualified"),
                            ("not_qualified", "Not Qualified"),
                            ("blocked", "Blocked"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decision", models.CharField(max_length=20)),
                ("position_size", models.IntegerField(default=0)),
                (
                    "margin_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Futures Test Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlgoTestScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("options", "Options - Kotak Strangle"),
                            ("futures", "Futures - ICICI"),
                            ("both", "Both Strategies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inputs", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_template", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Algo Test Scenarios",
                "ordering": ["-created_at"],
            },
        ),
    ]
