# Generated by Django 3.1.7 on 2025-11-15 07:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('strategy_type', models.CharField(help_text='Type of strategy (WEEKLY_NIFTY_STRANGLE, LLM_VALIDATED_FUTURES)', max_length=50)),
                ('instrument', models.CharField(help_text='Instrument name (NIFTY, BANKNIFTY, RELIANCE, etc.)', max_length=100)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('NEUTRAL', 'Neutral')], help_text='Position direction (LONG, SHORT, NEUTRAL)', max_length=10)),
                ('quantity', models.IntegerField(help_text='Lot quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('lot_size', models.IntegerField(default=1, help_text='Lot size for the instrument')),
                ('entry_price', models.DecimalField(decimal_places=2, help_text='Entry price', max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current market price', max_digits=15)),
                ('stop_loss', models.DecimalField(decimal_places=2, help_text='Stop-loss price', max_digits=15)),
                ('target', models.DecimalField(decimal_places=2, help_text='Target price', max_digits=15)),
                ('call_strike', models.DecimalField(blank=True, decimal_places=2, help_text='Call strike (for strangles)', max_digits=15, null=True)),
                ('put_strike', models.DecimalField(blank=True, decimal_places=2, help_text='Put strike (for strangles)', max_digits=15, null=True)),
                ('call_premium', models.DecimalField(blank=True, decimal_places=2, help_text='Call premium collected', max_digits=15, null=True)),
                ('put_premium', models.DecimalField(blank=True, decimal_places=2, help_text='Put premium collected', max_digits=15, null=True)),
                ('premium_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total premium collected (call + put)', max_digits=15)),
                ('current_delta', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Current net delta (for options)', max_digits=10)),
                ('expiry_date', models.DateField(help_text='Contract expiry date')),
                ('margin_used', models.DecimalField(decimal_places=2, help_text='Margin blocked for this position', max_digits=15)),
                ('entry_value', models.DecimalField(decimal_places=2, help_text='Total entry value (quantity * price * lot_size)', max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', help_text='Position status (ACTIVE or CLOSED)', max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True, help_text='When position was entered')),
                ('exit_time', models.DateTimeField(blank=True, help_text='When position was exited', null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Exit price', max_digits=15, null=True)),
                ('exit_reason', models.CharField(blank=True, help_text='Reason for exit (TARGET, STOP_LOSS, EOD, MANUAL, etc.)', max_length=100)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Realized P&L (after closing)', max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unrealized P&L (while active)', max_digits=15)),
                ('averaging_count', models.IntegerField(default=0, help_text='Number of times position was averaged')),
                ('original_entry_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original entry price before averaging', max_digits=15, null=True)),
                ('partial_booked', models.BooleanField(default=False, help_text='Whether partial profit was booked')),
                ('partial_quantity', models.IntegerField(default=0, help_text='Quantity booked in partial exit')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this position')),
                ('account', models.ForeignKey(help_text='Associated broker account', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.brokeraccount')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('check_type', models.CharField(help_text='Type of check (PRICE_UPDATE, SL_CHECK, TARGET_CHECK, DELTA_CHECK)', max_length=50)),
                ('result', models.CharField(help_text='Result (OK, WARNING, ALERT, ACTION_REQUIRED)', max_length=20)),
                ('message', models.TextField(help_text='Detailed message about the check')),
                ('action_taken', models.CharField(blank=True, help_text='Any action taken (ALERT_SENT, POSITION_CLOSED, etc.)', max_length=100)),
                ('price_at_check', models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of check', max_digits=15, null=True)),
                ('pnl_at_check', models.DecimalField(blank=True, decimal_places=2, help_text='P&L at time of check', max_digits=15, null=True)),
                ('position', models.ForeignKey(help_text='Associated position', on_delete=django.db.models.deletion.CASCADE, related_name='monitor_logs', to='positions.position')),
            ],
            options={
                'verbose_name': 'Monitor Log',
                'verbose_name_plural': 'Monitor Logs',
                'db_table': 'monitor_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['account', 'status'], name='positions_account_09f9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['status', 'expiry_date'], name='positions_status_13e62f_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorlog',
            index=models.Index(fields=['position', 'check_type'], name='monitor_log_positio_e35bab_idx'),
        ),
    ]
