# Generated by Django 3.1.7 on 2025-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_monitorlog_id_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
