# Generated by Django 4.2.7 on 2025-11-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0003_auto_20251115_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitorlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
