# Generated by Django 4.2.7 on 2025-11-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0004_alter_monitorlog_id_alter_position_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="stop_loss",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stop-loss price (optional)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="target",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target price (optional)",
                max_digits=15,
                null=True,
            ),
        ),
    ]
