# Generated by Django 4.2.7 on 2026-01-29 06:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_apicredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("positions", "0005_make_stop_loss_target_optional"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monitorlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.RemoveIndex(
            model_name="monitorlog",
            name="monitor_log_positio_e35bab_idx",
        ),
        migrations.AddField(
            model_name="position",
            name="broker_position_id",
            field=models.CharField(
                blank=True, help_text="Position ID from broker API", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="System confidence score (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="exchange_segment",
            field=models.CharField(
                blank=True,
                help_text="Exchange segment (nse_fo, nse_cm, etc.)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="Last sync from broker", null=True
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="product_type",
            field=models.CharField(
                blank=True, help_text="Product type (NRML, MIS, CNC)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Why suggestion was rejected"),
        ),
        migrations.AddField(
            model_name="position",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When suggestion was reviewed", null=True
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved/rejected",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_positions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="source",
            field=models.CharField(
                choices=[
                    ("BROKER", "Broker Sync"),
                    ("SYSTEM", "System Generated"),
                    ("MANUAL", "Manual Entry"),
                ],
                db_index=True,
                default="BROKER",
                help_text="Where this position originated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="suggestion_reason",
            field=models.TextField(
                blank=True, help_text="Why this trade was suggested"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="supporting_data",
            field=models.JSONField(
                blank=True, help_text="Technical indicators, patterns, etc.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="action_taken",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="check_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="pnl_at_check",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitor_logs",
                to="positions.position",
            ),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="price_at_check",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="monitorlog",
            name="result",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="position",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated broker account (null for suggestions)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="accounts.brokeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="averaging_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="position",
            name="call_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="call_strike",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="current_delta",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="current_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current market price (LTP)",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="direction",
            field=models.CharField(
                choices=[("LONG", "Long"), ("SHORT", "Short"), ("NEUTRAL", "Neutral")],
                help_text="LONG, SHORT, or NEUTRAL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="entry_price",
            field=models.DecimalField(
                decimal_places=2, help_text="Entry/suggested price", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="entry_time",
            field=models.DateTimeField(
                blank=True, help_text="When position was opened", null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="entry_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total entry value",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="exit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Exit price (when closed)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="exit_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for exit (TARGET, STOP_LOSS, MANUAL, etc.)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="exit_time",
            field=models.DateTimeField(
                blank=True, help_text="When position was closed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="Contract expiry date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="instrument",
            field=models.CharField(
                db_index=True,
                help_text="Trading symbol (NIFTY, RELIANCE, etc.)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="margin_used",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Margin blocked",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="original_entry_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="partial_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="position",
            name="partial_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="position",
            name="premium_collected",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="put_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="put_strike",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="quantity",
            field=models.IntegerField(
                help_text="Number of lots",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUGGESTED", "Suggested"),
                    ("APPROVED", "Approved"),
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                db_index=True,
                default="OPEN",
                help_text="Position lifecycle status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="stop_loss",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stop-loss price",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="strategy_type",
            field=models.CharField(
                blank=True,
                help_text="Strategy type (LLM_VALIDATED_FUTURES, WEEKLY_STRANGLE, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="target",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target price",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="unrealized_pnl",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current unrealized P&L",
                max_digits=15,
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["status", "source"], name="positions_status_f81cc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["instrument", "status"], name="positions_instrum_fe4487_idx"
            ),
        ),
    ]
