# Generated by Django 4.2.7 on 2026-03-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0006_alter_monitorlog_options_alter_position_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionMonitorDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Trading date (one dashboard per day)",
                        unique=True,
                    ),
                ),
                (
                    "telegram_message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Message ID of the live monitoring dashboard message",
                        null=True,
                    ),
                ),
                (
                    "day_start",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot at day start: {time, price, pnl, pnl_pct}",
                        null=True,
                    ),
                ),
                (
                    "snapshots",
                    models.JSONField(
                        default=list,
                        help_text="Last 3 monitoring snapshots [{time, price, pnl, pnl_pct}]",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When dashboard was last refreshed",
                        null=True,
                    ),
                ),
                (
                    "last_exit_msg_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Telegram message_id of last exit suggestion (for tracking)",
                        null=True,
                    ),
                ),
                (
                    "last_exit_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason of last exit suggestion sent",
                        max_length=50,
                    ),
                ),
                (
                    "last_exit_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last exit suggestion was sent",
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Active position being monitored this day",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitor_dashboards",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "db_table": "position_monitor_dashboard",
                "ordering": ["-date"],
            },
        ),
    ]
