# Generated by Django 4.2.7 on 2026-03-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0007_add_position_monitor_dashboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionmonitordashboard",
            name="date",
            field=models.DateField(db_index=True, help_text="Trading date"),
        ),
        migrations.AlterField(
            model_name="positionmonitordashboard",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="Position being monitored",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitor_dashboards",
                to="positions.position",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="positionmonitordashboard",
            unique_together={("position", "date")},
        ),
    ]
