# Generated by Django 4.2.7 on 2026-03-06 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0008_fix_monitor_dashboard_per_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly name, e.g. HDFCBANK26MARFUT (auto-generated)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="instrument",
            field=models.CharField(
                db_index=True,
                help_text="Original broker symbol used for order placement",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="quantity",
            field=models.IntegerField(
                help_text="Total units (e.g. lots × lot_size)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
