# Generated by Django 4.2.7 on 2026-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0010_positionmonitordashboard_sr_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioPnlTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Trading date", unique=True
                    ),
                ),
                (
                    "snapshots",
                    models.JSONField(
                        default=list,
                        help_text="Timestamped P&L readings: [{pnl, ts}, ...]",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_pnl_tracker",
                "ordering": ["-date"],
            },
        ),
    ]
