# Generated by Django 4.2.7 on 2026-04-10 04:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0011_add_portfolio_pnl_tracker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "default_manager_name": "all_objects",
                "ordering": ["-created_at"],
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.AlterModelManagers(
            name="position",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="position",
            name="is_paper",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Paper (simulated) trade — not a real broker position",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="source",
            field=models.CharField(
                choices=[
                    ("BROKER", "Broker Sync"),
                    ("SYSTEM", "System Generated"),
                    ("MANUAL", "Manual Entry"),
                    ("PAPER", "Paper Trade"),
                ],
                db_index=True,
                default="BROKER",
                help_text="Where this position originated",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["is_paper", "status"], name="positions_is_pape_022d78_idx"
            ),
        ),
    ]
