# Generated by Django 4.2.7 on 2026-07-20 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("positions", "0012_alter_position_options_alter_position_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeVerificationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "data_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Aggregated technical/OI/news/analyst data at snapshot time",
                    ),
                ),
                ("llm_provider", models.CharField(blank=True, max_length=20)),
                ("llm_verdict", models.JSONField(blank=True, null=True)),
                ("llm_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Open position this snapshot was taken for, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_snapshots",
                        to="positions.position",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Verification Snapshot",
                "verbose_name_plural": "Trade Verification Snapshots",
                "db_table": "llmskill_trade_verification_snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-created_at"],
                        name="llmskill_tr_symbol_0c920c_idx",
                    )
                ],
            },
        ),
    ]
