# Generated by Django 3.1.7 on 2025-11-15 07:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('strategy_type', models.CharField(help_text='Type of strategy', max_length=50)),
                ('pattern_name', models.CharField(help_text='Unique pattern identifier', max_length=100)),
                ('pattern_description', models.TextField(help_text='Description of what this pattern represents')),
                ('entry_conditions', models.JSONField(default=dict, help_text='Entry conditions that define this pattern')),
                ('market_conditions', models.JSONField(default=dict, help_text='Market conditions when pattern occurs')),
                ('times_occurred', models.IntegerField(default=0, help_text='Number of times this pattern occurred')),
                ('times_profitable', models.IntegerField(default=0, help_text='Number of times pattern resulted in profit')),
                ('avg_profit_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Average profit percentage', max_digits=10)),
                ('avg_loss_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Average loss percentage', max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Win rate percentage', max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Profit factor (gross profit / gross loss)', max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total profit from this pattern', max_digits=15)),
                ('total_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total loss from this pattern', max_digits=15)),
                ('insights', models.TextField(blank=True, help_text='LLM-generated insights about this pattern')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for trading this pattern')),
                ('is_reliable', models.BooleanField(default=False, help_text='Whether this pattern is statistically reliable (>30 occurrences)')),
                ('last_occurrence', models.DateTimeField(blank=True, help_text='Last time this pattern occurred', null=True)),
            ],
            options={
                'verbose_name': 'Strategy Learning',
                'verbose_name_plural': 'Strategy Learning Records',
                'db_table': 'strategy_learning',
                'ordering': ['-win_rate', '-profit_factor'],
                'unique_together': {('strategy_type', 'pattern_name')},
            },
        ),
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('strategy_type', models.CharField(choices=[('WEEKLY_NIFTY_STRANGLE', 'Weekly Nifty Strangle'), ('LLM_VALIDATED_FUTURES', 'LLM Validated Futures')], help_text='Type of strategy', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this strategy is currently active')),
                ('initial_margin_usage_pct', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Use 50% margin for first trade (reserve 50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('min_profit_pct_to_exit', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Only exit EOD if profit >= this %', max_digits=5)),
                ('base_delta_pct', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Base delta % for strike selection (Strangle)', max_digits=5)),
                ('min_days_to_expiry', models.IntegerField(default=1, help_text='Minimum days to expiry for options (skip if less)')),
                ('delta_rebalance_threshold', models.IntegerField(default=300, help_text='Alert when |net_delta| exceeds this (Strangle)')),
                ('min_days_to_future_expiry', models.IntegerField(default=15, help_text='Minimum days to expiry for futures (skip if less)')),
                ('allow_averaging', models.BooleanField(default=True, help_text='Whether averaging is allowed (Futures)')),
                ('max_average_attempts', models.IntegerField(default=2, help_text='Maximum averaging attempts (Futures)')),
                ('average_down_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Average when position down by this % (Futures)', max_digits=5)),
                ('default_stop_loss_pct', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Default stop-loss % (Futures)', max_digits=5)),
                ('default_target_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Default target % (Futures)', max_digits=5)),
                ('min_llm_confidence', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Minimum LLM confidence % required (Futures)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('require_human_approval', models.BooleanField(default=True, help_text='Require manual approval before entry (Futures)')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional strategy-specific parameters')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes')),
                ('account', models.ForeignKey(help_text='Associated broker account', on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='accounts.brokeraccount')),
            ],
            options={
                'verbose_name': 'Strategy Configuration',
                'verbose_name_plural': 'Strategy Configurations',
                'db_table': 'strategy_configs',
                'ordering': ['account', 'strategy_type'],
                'unique_together': {('account', 'strategy_type')},
            },
        ),
    ]
