# Generated by Django 4.2.7 on 2025-11-18 07:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0002_alter_strategyconfig_id_alter_strategylearning_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingScheduleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            ("PREMARKET", "Pre-Market Data Fetch"),
                            ("MARKET_OPEN", "Market Opening Validation"),
                            ("TRADE_START", "Trade Start Evaluation"),
                            ("TRADE_MONITOR", "Trade Monitoring"),
                            ("TRADE_STOP", "Trade Stop/Exit"),
                            ("DAY_CLOSE", "Day Close Reconciliation"),
                            ("ANALYZE_DAY", "Day Analysis & Learning"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Time to run this task (IST)"),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "interval_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Interval in minutes for recurring tasks",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Start time for recurring task", null=True
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="End time for recurring task", null=True
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="Days to run: [0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri]",
                    ),
                ),
                (
                    "task_parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Task-specific parameters as JSON",
                    ),
                ),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_status", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Trading Schedule Configuration",
                "verbose_name_plural": "Trading Schedule Configurations",
                "db_table": "trading_schedule_config",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="TradingInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("FILTER", "Filter Effectiveness"),
                            ("ENTRY", "Entry Timing"),
                            ("EXIT", "Exit Timing"),
                            ("STRIKE", "Strike Selection"),
                            ("SIZING", "Position Sizing"),
                            ("PATTERN", "Market Pattern"),
                            ("CORRELATION", "Market Correlation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("trading_date", models.DateField(db_index=True)),
                (
                    "insight_data",
                    models.JSONField(default=dict, help_text="Detailed insight data"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence in this insight (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "times_validated",
                    models.IntegerField(
                        default=0, help_text="How many times validated"
                    ),
                ),
                (
                    "times_contradicted",
                    models.IntegerField(
                        default=0, help_text="How many times contradicted"
                    ),
                ),
                (
                    "estimated_impact",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("action_recommended", models.TextField(blank=True)),
                ("action_taken", models.BooleanField(default=False)),
                ("action_taken_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "trading_insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-trading_date"], name="trading_ins_trading_58d5e4_idx"
                    ),
                    models.Index(
                        fields=["insight_type"], name="trading_ins_insight_126660_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="trading_ins_is_acti_f151dd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SGXNiftyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True, unique=True)),
                (
                    "sgx_open",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sgx_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sgx_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sgx_close",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sgx_last_traded",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sgx_change_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "sgx_change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "nifty_prev_close",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "implied_gap_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "implied_gap_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.CharField(default="Yahoo Finance", max_length=100),
                ),
            ],
            options={
                "db_table": "sgx_nifty_data",
                "ordering": ["-trading_date"],
                "indexes": [
                    models.Index(
                        fields=["-trading_date"], name="sgx_nifty_d_trading_777f8c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketOpeningState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True, unique=True)),
                ("prev_close", models.DecimalField(decimal_places=2, max_digits=15)),
                ("nifty_open", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "nifty_9_15_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("gap_points", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gap_percent", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "gap_type",
                    models.CharField(
                        choices=[
                            ("GAP_UP", "Gap Up"),
                            ("GAP_DOWN", "Gap Down"),
                            ("FLAT", "Flat Open"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "opening_sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("NEUTRAL", "Neutral"),
                            ("BEARISH", "Bearish"),
                            ("VOLATILE", "Volatile"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "vix_9_15",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("opening_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "volume_vs_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "nifty_9_30_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "movement_9_15_to_9_30_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "movement_9_15_to_9_30_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("is_substantial_movement", models.BooleanField(default=False)),
                ("is_trading_day", models.BooleanField(default=True)),
                ("is_expiry_day", models.BooleanField(default=False)),
                ("is_event_day", models.BooleanField(default=False)),
                (
                    "sgx_nifty_change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sgx_correlation_accurate",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "us_nasdaq_change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "us_dow_change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at_9_30", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "market_opening_state",
                "ordering": ["-trading_date"],
                "indexes": [
                    models.Index(
                        fields=["-trading_date"], name="market_open_trading_fc2442_idx"
                    ),
                    models.Index(
                        fields=["is_substantial_movement"],
                        name="market_open_is_subs_902fd4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyTradingAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True, unique=True)),
                ("nifty_open", models.DecimalField(decimal_places=2, max_digits=15)),
                ("nifty_high", models.DecimalField(decimal_places=2, max_digits=15)),
                ("nifty_low", models.DecimalField(decimal_places=2, max_digits=15)),
                ("nifty_close", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "nifty_change_percent",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "vix_open",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vix_close",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vix_change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("total_trades_entered", models.IntegerField(default=0)),
                ("total_trades_exited", models.IntegerField(default=0)),
                ("total_trades_open", models.IntegerField(default=0)),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "capital_deployed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "return_on_capital",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "filters_run",
                    models.JSONField(default=dict, help_text="Which filters were run"),
                ),
                (
                    "filters_passed",
                    models.JSONField(default=dict, help_text="Which filters passed"),
                ),
                (
                    "filters_failed",
                    models.JSONField(default=dict, help_text="Which filters failed"),
                ),
                (
                    "filter_accuracy",
                    models.JSONField(
                        default=dict, help_text="Filter accuracy analysis"
                    ),
                ),
                (
                    "entry_timing_analysis",
                    models.JSONField(
                        default=dict, help_text="Entry timing effectiveness"
                    ),
                ),
                (
                    "strike_selection_analysis",
                    models.JSONField(
                        default=dict, help_text="Strike selection performance"
                    ),
                ),
                (
                    "position_sizing_analysis",
                    models.JSONField(
                        default=dict, help_text="Position sizing effectiveness"
                    ),
                ),
                (
                    "exit_timing_analysis",
                    models.JSONField(
                        default=dict, help_text="Exit timing effectiveness"
                    ),
                ),
                (
                    "exit_reasons",
                    models.JSONField(default=dict, help_text="Exit reasons breakdown"),
                ),
                (
                    "market_regime",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRENDING_UP", "Trending Up"),
                            ("TRENDING_DOWN", "Trending Down"),
                            ("RANGE_BOUND", "Range Bound"),
                            ("VOLATILE", "Volatile"),
                            ("QUIET", "Quiet"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "successful_patterns",
                    models.JSONField(
                        default=list, help_text="Patterns that led to success"
                    ),
                ),
                (
                    "failed_patterns",
                    models.JSONField(
                        default=list, help_text="Patterns that led to failure"
                    ),
                ),
                (
                    "key_learnings",
                    models.JSONField(
                        default=list, help_text="Key insights from the day"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Recommendations for future"
                    ),
                ),
                (
                    "parameter_adjustments",
                    models.JSONField(
                        default=dict, help_text="Suggested parameter changes"
                    ),
                ),
                (
                    "overall_strategy_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "sgx_prediction_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="How accurate was SGX in predicting Indian market",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("analysis_completed_at", models.DateTimeField(blank=True, null=True)),
                ("analysis_version", models.CharField(default="1.0", max_length=20)),
                ("notification_sent", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "daily_trading_analysis",
                "ordering": ["-trading_date"],
                "indexes": [
                    models.Index(
                        fields=["-trading_date"], name="daily_tradi_trading_46fce2_idx"
                    ),
                    models.Index(
                        fields=["market_regime"], name="daily_tradi_market__e51068_idx"
                    ),
                    models.Index(
                        fields=["win_rate"], name="daily_tradi_win_rat_55698a_idx"
                    ),
                ],
            },
        ),
    ]
