# Generated by Django 4.2.7 on 2025-11-18 07:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "strategies",
            "0003_tradingscheduleconfig_tradinginsight_sgxniftydata_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NiftyMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "data_timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "spot_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current Nifty spot price",
                        max_digits=10,
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Today's open", max_digits=10
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Today's high", max_digits=10
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Today's low", max_digits=10
                    ),
                ),
                (
                    "prev_close",
                    models.DecimalField(
                        decimal_places=2, help_text="Previous day close", max_digits=10
                    ),
                ),
                (
                    "change_points",
                    models.DecimalField(
                        decimal_places=2, help_text="Change in points", max_digits=10
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=2, help_text="Change in percentage", max_digits=5
                    ),
                ),
                (
                    "sgx_nifty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="SGX Nifty",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dow_jones",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dow Jones",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "nasdaq",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nasdaq",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "sp500",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="S&P 500",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "gift_nifty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GIFT Nifty",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "india_vix",
                    models.DecimalField(
                        decimal_places=2, help_text="India VIX", max_digits=6
                    ),
                ),
                (
                    "vix_change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dma_5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="5-day moving average",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dma_10",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="10-day moving average",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dma_20",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="20-day moving average",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dma_50",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="50-day moving average",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dma_200",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="200-day moving average",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_volume",
                    models.BigIntegerField(
                        blank=True, help_text="Total volume traded", null=True
                    ),
                ),
                (
                    "total_turnover",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total turnover in crores",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "advances",
                    models.IntegerField(
                        blank=True, help_text="Number of advancing stocks", null=True
                    ),
                ),
                (
                    "declines",
                    models.IntegerField(
                        blank=True, help_text="Number of declining stocks", null=True
                    ),
                ),
                (
                    "unchanged",
                    models.IntegerField(
                        blank=True, help_text="Number of unchanged stocks", null=True
                    ),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        default=False, help_text="True if data is > 5 minutes old"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="breeze",
                        help_text="Source: breeze, trendlyne, manual",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "strangle_market_data",
                "ordering": ["-data_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StrangleAlgorithmState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("DATA_COLLECTION", "Collecting Data"),
                            ("MARKET_ANALYSIS", "Analyzing Market"),
                            ("STRIKE_SELECTION", "Selecting Strikes"),
                            ("DELTA_CALCULATION", "Calculating Delta"),
                            ("PREMIUM_EVALUATION", "Evaluating Premiums"),
                            ("RISK_ASSESSMENT", "Assessing Risk"),
                            ("POSITION_READY", "Position Ready"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="INITIALIZED",
                        max_length=30,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1, help_text="Current step number (1-10)"
                    ),
                ),
                (
                    "total_steps",
                    models.IntegerField(
                        default=10, help_text="Total steps in algorithm"
                    ),
                ),
                (
                    "suggested_call_strike",
                    models.IntegerField(
                        blank=True, help_text="Suggested CE strike", null=True
                    ),
                ),
                (
                    "suggested_put_strike",
                    models.IntegerField(
                        blank=True, help_text="Suggested PE strike", null=True
                    ),
                ),
                (
                    "call_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "put_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "call_delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "put_delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "net_delta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Net position delta",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "delta_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("300"),
                        help_text="Target delta (usually 300)",
                        max_digits=6,
                    ),
                ),
                (
                    "max_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max potential loss",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "breakeven_upper",
                    models.IntegerField(
                        blank=True, help_text="Upper breakeven point", null=True
                    ),
                ),
                (
                    "breakeven_lower",
                    models.IntegerField(
                        blank=True, help_text="Lower breakeven point", null=True
                    ),
                ),
                (
                    "margin_required",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "step_1_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step 1: Market data collection",
                    ),
                ),
                (
                    "step_2_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step 2: Option chain analysis",
                    ),
                ),
                (
                    "step_3_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step 3: ATM strike identification",
                    ),
                ),
                (
                    "step_4_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step 4: Call strike selection",
                    ),
                ),
                (
                    "step_5_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step 5: Put strike selection",
                    ),
                ),
                (
                    "step_6_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Step 6: Delta calculation"
                    ),
                ),
                (
                    "step_7_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Step 7: Premium evaluation"
                    ),
                ),
                (
                    "step_8_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Step 8: Risk assessment"
                    ),
                ),
                (
                    "step_9_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Step 9: Final validation"
                    ),
                ),
                (
                    "step_10_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Step 10: Position summary"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Algorithm execution time", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if status=ERROR"
                    ),
                ),
                (
                    "market_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="algorithm_states",
                        to="strategies.niftymarketdata",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "strangle_algorithm_state",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="niftymarketdata",
            index=models.Index(
                fields=["-data_timestamp"], name="strangle_ma_data_ti_6674d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="niftymarketdata",
            index=models.Index(
                fields=["is_stale"], name="strangle_ma_is_stal_ca2a23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stranglealgorithmstate",
            index=models.Index(
                fields=["-created_at"], name="strangle_al_created_b6b20b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stranglealgorithmstate",
            index=models.Index(fields=["status"], name="strangle_al_status_2ac8aa_idx"),
        ),
    ]
