# Generated by Django 4.2.7 on 2025-11-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_apicredential_id_alter_brokeraccount_id"),
        ("strategies", "0004_niftymarketdata_stranglealgorithmstate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stranglealgorithmstate",
            name="triggered_by",
        ),
        migrations.AddField(
            model_name="stranglealgorithmstate",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Broker account for this strangle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.brokeraccount",
            ),
        ),
    ]
