# Generated by Django 4.2.7 on 2026-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0005_remove_stranglealgorithmstate_triggered_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategyconfig",
            name="strategy_type",
            field=models.CharField(
                choices=[
                    ("WEEKLY_NIFTY_STRANGLE", "Weekly Nifty Strangle"),
                    ("BROKEN_IRON_CONDOR", "Broken Iron Condor"),
                    ("LLM_VALIDATED_FUTURES", "LLM Validated Futures"),
                ],
                help_text="Type of strategy",
                max_length=50,
            ),
        ),
    ]
