# Generated by Django 4.2.7 on 2026-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0006_alter_strategyconfig_strategy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingscheduleconfig",
            name="is_enabled",
            field=models.BooleanField(
                default=False, help_text="Task is inactive by default"
            ),
        ),
    ]
