# Generated by Django 4.2.7 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0007_alter_tradingscheduleconfig_is_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingDaySetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True, unique=True)),
                ("setup_completed_at", models.DateTimeField(blank=True, null=True)),
                ("trendlyne_data_fresh", models.BooleanField(default=False)),
                ("news_data_fresh", models.BooleanField(default=False)),
                ("broker_connection_ok", models.BooleanField(default=False)),
                (
                    "is_trading_day",
                    models.BooleanField(default=True, help_text="Not a holiday"),
                ),
                ("is_expiry_day", models.BooleanField(default=False)),
                (
                    "is_major_event_day",
                    models.BooleanField(
                        default=False, help_text="RBI policy, budget, etc."
                    ),
                ),
                (
                    "us_market_change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "asian_market_change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sgx_nifty_change",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "overnight_risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("EXTREME", "Extreme Risk - No Trade"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "setup_tradable",
                    models.BooleanField(
                        default=False, help_text="Day cleared for trading in setup"
                    ),
                ),
                (
                    "setup_reason",
                    models.TextField(blank=True, help_text="Reason for setup decision"),
                ),
                ("start_validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "nifty_open",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "nifty_prev_close",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "gap_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vix_open",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "vix_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low (<15)"),
                            ("NORMAL", "Normal (15-20)"),
                            ("ELEVATED", "Elevated (20-25)"),
                            ("HIGH", "High (>25)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nifty_52w_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "distance_from_52w_high_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "near_52w_high",
                    models.BooleanField(
                        default=False, help_text="Within 2% of 52-week high"
                    ),
                ),
                ("major_news_detected", models.BooleanField(default=False)),
                (
                    "news_sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEUTRAL", "Neutral"),
                            ("NEGATIVE", "Negative"),
                            ("MIXED", "Mixed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("news_summary", models.TextField(blank=True)),
                (
                    "start_tradable",
                    models.BooleanField(
                        default=False, help_text="Day cleared for trading at start"
                    ),
                ),
                (
                    "start_reason",
                    models.TextField(blank=True, help_text="Reason for start decision"),
                ),
                (
                    "is_tradable",
                    models.BooleanField(
                        default=False, help_text="Final: Can we trade today?"
                    ),
                ),
                ("tradable_reason", models.TextField(blank=True)),
                ("futures_trading_allowed", models.BooleanField(default=False)),
                ("options_strangle_allowed", models.BooleanField(default=False)),
                ("options_iron_condor_allowed", models.BooleanField(default=False)),
                (
                    "recommended_strategy",
                    models.CharField(
                        choices=[
                            ("NONE", "No Trading Today"),
                            ("STRANGLE", "Weekly Nifty Strangle"),
                            ("IRON_CONDOR", "Broken Wing Iron Condor"),
                            ("FUTURES_ONLY", "Futures Only"),
                            ("ALL", "All Strategies Allowed"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                ("futures_screened", models.BooleanField(default=False)),
                ("futures_screened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "futures_suggestions",
                    models.JSONField(
                        default=list, help_text="Top 5 futures suggestions"
                    ),
                ),
                ("options_strategy_evaluated", models.BooleanField(default=False)),
                ("options_evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "options_strategy_selected",
                    models.CharField(blank=True, max_length=50),
                ),
                ("options_trade_started", models.BooleanField(default=False)),
                (
                    "options_trade_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("averaging_completed", models.BooleanField(default=False)),
                ("averaging_completed_at", models.DateTimeField(blank=True, null=True)),
                ("day_closed", models.BooleanField(default=False)),
                ("day_closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_summary", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "trading_day_setup",
                "ordering": ["-trading_date"],
                "indexes": [
                    models.Index(
                        fields=["-trading_date"], name="trading_day_trading_3069cd_idx"
                    ),
                    models.Index(
                        fields=["is_tradable"], name="trading_day_is_trad_8f261e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FuturesSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True)),
                ("rank", models.IntegerField(help_text="Rank 1-5")),
                ("symbol", models.CharField(max_length=50)),
                ("stock_name", models.CharField(blank=True, max_length=200)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=10
                    ),
                ),
                (
                    "volume_rank",
                    models.IntegerField(help_text="Volume rank among F&O stocks"),
                ),
                (
                    "volume_vs_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "composite_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "oi_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "technical_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sector_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("oi_buildup_type", models.CharField(blank=True, max_length=50)),
                (
                    "oi_change_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "suggested_entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "suggested_stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "suggested_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_executed", models.BooleanField(default=False)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("position_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "futures_suggestions",
                "ordering": ["-trading_date", "rank"],
                "indexes": [
                    models.Index(
                        fields=["-trading_date"], name="futures_sug_trading_e2b21c_idx"
                    ),
                    models.Index(
                        fields=["symbol"], name="futures_sug_symbol_095646_idx"
                    ),
                ],
                "unique_together": {("trading_date", "rank")},
            },
        ),
    ]
