# Generated by Django 4.2.7 on 2026-02-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0008_tradingdaysetup_futuressuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="niftymarketdata",
            name="news_analysis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full news analysis from NewsImpactAnalyzer",
            ),
        ),
        migrations.AddField(
            model_name="niftymarketdata",
            name="news_market_outlook",
            field=models.CharField(
                blank=True,
                help_text="BULLISH, BEARISH, NEUTRAL, or VOLATILE",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="niftymarketdata",
            name="news_sentiment_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="News sentiment score (-1.0 to 1.0)",
                max_digits=4,
                null=True,
            ),
        ),
    ]
