# Generated by Django 4.2.7 on 2026-02-25 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0009_niftymarketdata_news_analysis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stranglealgorithmstate",
            name="account",
        ),
        migrations.RemoveField(
            model_name="stranglealgorithmstate",
            name="market_data",
        ),
        migrations.DeleteModel(
            name="NiftyMarketData",
        ),
        migrations.DeleteModel(
            name="StrangleAlgorithmState",
        ),
    ]
