# Generated by Django 5.2.8 on 2025-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('service', models.CharField(choices=[('breeze', 'ICICI Breeze'), ('trendlyne', 'Trendlyne'), ('kotakneo', 'Kotak Neo'), ('other', 'Other')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=256, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('session_token', models.CharField(blank=True, max_length=512, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('neo_password', models.CharField(blank=True, max_length=100, null=True)),
                ('sid', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_session_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credential_store',
                'unique_together': {('service', 'name')},
            },
        ),
    ]
