# Generated by Django 4.2.7 on 2025-11-15 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Trading date (DD-MM-YY format stored as DateField)",
                        unique=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True, help_text="Day of the week", max_length=20
                    ),
                ),
                (
                    "num_legs",
                    models.IntegerField(
                        default=0, help_text="Number of option legs traded"
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Profit and Loss for the day",
                        max_digits=12,
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Whether all positions were closed"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="F&O expiry date traded", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "day_report",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NseFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        db_index=True,
                        help_text="Flag name (key)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Flag value (stored as string)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this flag represents"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nse_flag",
                "ordering": ["flag"],
            },
        ),
        migrations.CreateModel(
            name="TradingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Trading date", unique=True)),
                (
                    "open_time",
                    models.TimeField(
                        default=datetime.time(9, 15, 10),
                        help_text="Market open / setup task time",
                    ),
                ),
                (
                    "take_trade_time",
                    models.TimeField(
                        default=datetime.time(9, 30), help_text="Start taking trades"
                    ),
                ),
                (
                    "last_trade_time",
                    models.TimeField(
                        default=datetime.time(10, 15),
                        help_text="Last time to enter new trades",
                    ),
                ),
                (
                    "close_pos_time",
                    models.TimeField(
                        default=datetime.time(15, 25, 30),
                        help_text="Start closing positions",
                    ),
                ),
                (
                    "mkt_close_time",
                    models.TimeField(
                        default=datetime.time(15, 32), help_text="Market close time"
                    ),
                ),
                (
                    "close_day_time",
                    models.TimeField(
                        default=datetime.time(15, 45),
                        help_text="End-of-day analysis time",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Enable trading for this day"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Notes about this trading day",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "trading_schedule",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TodaysPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, help_text="Position date")),
                ("symbol", models.CharField(max_length=50)),
                ("instrument_name", models.CharField(max_length=100)),
                ("instrument_token", models.BigIntegerField()),
                ("exchange", models.CharField(default="NFO", max_length=10)),
                ("segment", models.CharField(default="FNO", max_length=10)),
                ("expiry_date", models.CharField(max_length=10)),
                ("option_type", models.CharField(max_length=10)),
                ("strike_price", models.IntegerField(default=0)),
                ("last_price", models.FloatField()),
                ("average_stock_price", models.FloatField()),
                ("buy_traded_qty_lot", models.IntegerField(default=0)),
                ("buy_traded_val", models.FloatField(default=0)),
                ("buy_trd_avg", models.FloatField(default=0)),
                ("buy_open_qty_lot", models.IntegerField(default=0)),
                ("buy_open_val", models.FloatField(default=0)),
                ("sell_traded_qty_lot", models.IntegerField(default=0)),
                ("sell_traded_val", models.FloatField(default=0)),
                ("sell_trd_avg", models.FloatField(default=0)),
                ("sell_open_qty_lot", models.IntegerField(default=0)),
                ("sell_open_val", models.FloatField(default=0)),
                ("net_trd_qty_lot", models.IntegerField(default=0)),
                ("net_trd_value", models.FloatField(default=0)),
                ("actual_net_trd_value", models.FloatField(default=0)),
                ("realized_pl", models.FloatField(default=0, help_text="Realized P&L")),
                ("net_change", models.FloatField(default=0)),
                ("percent_change", models.FloatField(default=0)),
                ("span_margin", models.FloatField(default=0)),
                ("span_margin_total", models.FloatField(default=0)),
                ("exposure_margin", models.FloatField(default=0)),
                ("exposure_margin_total", models.FloatField(default=0)),
                ("premium", models.FloatField(default=0)),
                ("market_lot", models.IntegerField(default=1)),
                ("multiplier", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "todays_position",
                "ordering": ["-date", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["-date", "symbol"], name="todays_posi_date_d6a76a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(help_text="Action/function name", max_length=100),
                ),
                ("message", models.TextField(help_text="Log message")),
                (
                    "background_task",
                    models.CharField(
                        blank=True, help_text="Background task name", max_length=100
                    ),
                ),
            ],
            options={
                "db_table": "bk_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "level"], name="bk_log_timesta_12f254_idx"
                    ),
                    models.Index(
                        fields=["background_task"], name="bk_log_backgro_e6c4d4_idx"
                    ),
                ],
            },
        ),
    ]
