# Generated by Django 4.2.7 on 2025-11-18 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_dayreport_nseflag_tradingschedule_todaysposition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("singleton_id", models.IntegerField(default=1, unique=True)),
                (
                    "trendlyne_fetch_hour",
                    models.IntegerField(
                        default=8,
                        help_text="Hour to fetch Trendlyne data (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "trendlyne_fetch_minute",
                    models.IntegerField(
                        default=30,
                        help_text="Minute to fetch Trendlyne data (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "trendlyne_import_hour",
                    models.IntegerField(
                        default=9,
                        help_text="Hour to import Trendlyne data (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "trendlyne_import_minute",
                    models.IntegerField(
                        default=0,
                        help_text="Minute to import Trendlyne data (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "premarket_update_hour",
                    models.IntegerField(
                        default=8,
                        help_text="Hour to update pre-market data (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "premarket_update_minute",
                    models.IntegerField(
                        default=30,
                        help_text="Minute to update pre-market data (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "live_data_interval_minutes",
                    models.IntegerField(
                        default=5,
                        help_text="Interval in minutes to update live market data during market hours",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "live_data_start_hour",
                    models.IntegerField(
                        default=9,
                        help_text="Start hour for live market data updates",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "live_data_end_hour",
                    models.IntegerField(
                        default=15,
                        help_text="End hour for live market data updates",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "postmarket_update_hour",
                    models.IntegerField(
                        default=15,
                        help_text="Hour to update post-market data (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "postmarket_update_minute",
                    models.IntegerField(
                        default=30,
                        help_text="Minute to update post-market data (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "futures_screening_interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Interval in minutes to screen for futures opportunities",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "futures_screening_start_hour",
                    models.IntegerField(
                        default=9,
                        help_text="Start hour for futures screening",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "futures_screening_end_hour",
                    models.IntegerField(
                        default=14,
                        help_text="End hour for futures screening",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "futures_averaging_interval_minutes",
                    models.IntegerField(
                        default=10,
                        help_text="Interval in minutes to check futures averaging",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "monitor_positions_interval_seconds",
                    models.IntegerField(
                        default=10,
                        help_text="Interval in seconds to monitor all positions",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "update_pnl_interval_seconds",
                    models.IntegerField(
                        default=15,
                        help_text="Interval in seconds to update position P&L",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "check_exit_interval_seconds",
                    models.IntegerField(
                        default=30,
                        help_text="Interval in seconds to check exit conditions",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "risk_check_interval_seconds",
                    models.IntegerField(
                        default=60,
                        help_text="Interval in seconds to check risk limits",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "circuit_breaker_interval_seconds",
                    models.IntegerField(
                        default=30,
                        help_text="Interval in seconds to monitor circuit breakers",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "daily_pnl_report_hour",
                    models.IntegerField(
                        default=16,
                        help_text="Hour to generate daily P&L report (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "daily_pnl_report_minute",
                    models.IntegerField(
                        default=0,
                        help_text="Minute to generate daily P&L report (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "learning_patterns_hour",
                    models.IntegerField(
                        default=17,
                        help_text="Hour to update learning patterns (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "learning_patterns_minute",
                    models.IntegerField(
                        default=0,
                        help_text="Minute to update learning patterns (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "weekly_summary_hour",
                    models.IntegerField(
                        default=18,
                        help_text="Hour to send weekly summary (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "weekly_summary_minute",
                    models.IntegerField(
                        default=0,
                        help_text="Minute to send weekly summary (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "weekly_summary_day_of_week",
                    models.IntegerField(
                        default=4,
                        help_text="Day of week for weekly summary (0=Monday, 6=Sunday)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "enable_market_data_tasks",
                    models.BooleanField(
                        default=True, help_text="Enable all market data fetching tasks"
                    ),
                ),
                (
                    "enable_strategy_tasks",
                    models.BooleanField(
                        default=True, help_text="Enable strategy execution tasks"
                    ),
                ),
                (
                    "enable_position_monitoring",
                    models.BooleanField(
                        default=True, help_text="Enable position monitoring tasks"
                    ),
                ),
                (
                    "enable_risk_monitoring",
                    models.BooleanField(
                        default=True, help_text="Enable risk management tasks"
                    ),
                ),
                (
                    "enable_reporting_tasks",
                    models.BooleanField(
                        default=True, help_text="Enable reporting and analytics tasks"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
        migrations.AddField(
            model_name="bklog",
            name="context_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional context data (symbols, counts, metrics, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="bklog",
            name="error_details",
            field=models.TextField(
                blank=True, help_text="Full error traceback if error occurred"
            ),
        ),
        migrations.AddField(
            model_name="bklog",
            name="execution_time_ms",
            field=models.IntegerField(
                blank=True, help_text="Execution time in milliseconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="bklog",
            name="success",
            field=models.BooleanField(
                default=True, help_text="Whether the task completed successfully"
            ),
        ),
        migrations.AddField(
            model_name="bklog",
            name="task_category",
            field=models.CharField(
                choices=[
                    ("data", "Market Data"),
                    ("strategy", "Strategy Execution"),
                    ("position", "Position Monitoring"),
                    ("risk", "Risk Management"),
                    ("analytics", "Analytics & Reports"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                help_text="Category of the task",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bklog",
            name="task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Celery task ID for correlation",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="credentialstore",
            name="service",
            field=models.CharField(
                choices=[
                    ("breeze", "ICICI Breeze"),
                    ("trendlyne", "Trendlyne"),
                    ("kotakneo", "Kotak Neo"),
                    ("telegram", "Telegram Bot"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="bklog",
            index=models.Index(
                fields=["task_category", "-timestamp"], name="bk_log_task_ca_43e48c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bklog",
            index=models.Index(
                fields=["success", "-timestamp"], name="bk_log_success_41bf56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bklog",
            index=models.Index(fields=["task_id"], name="bk_log_task_id_d39e73_idx"),
        ),
    ]
