# Generated by Django 4.2.7 on 2026-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_systemsettings_bklog_context_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialstore",
            name="service",
            field=models.CharField(
                choices=[
                    ("breeze", "ICICI Breeze"),
                    ("trendlyne", "Trendlyne"),
                    ("kotakneo", "Kotak Neo"),
                    ("telegram", "Telegram Bot"),
                    ("gnewsio", "GNews.io"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
