# Generated by Django 4.2.7 on 2026-01-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_credentialstore_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTaskState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "task_key",
                    models.CharField(
                        db_index=True,
                        help_text="Task key from beat_schedule (e.g., 'fetch-trendlyne-data-daily')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "task_path",
                    models.CharField(
                        blank=True,
                        help_text="Full task path (e.g., 'apps.data.tasks.fetch_trendlyne_data')",
                        max_length=200,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Human-readable task name", max_length=150
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this task should run"
                    ),
                ),
                (
                    "last_toggled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was last enabled/disabled",
                        null=True,
                    ),
                ),
                (
                    "last_toggled_by",
                    models.CharField(
                        blank=True,
                        help_text="User who last toggled this task",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Celery Task State",
                "verbose_name_plural": "Celery Task States",
                "db_table": "celery_task_state",
                "ordering": ["task_key"],
            },
        ),
    ]
