# Generated by Django 4.2.7 on 2026-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_celerytaskstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celerytaskstate",
            name="is_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this task should run (default: disabled)",
            ),
        ),
    ]
