# Generated by Django 3.1.7 on 2026-01-31 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_celerytaskstate_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytaskstate',
            name='category',
            field=models.CharField(blank=True, help_text='Task category for grouping (data, strategies, monitoring, risk, reports)', max_length=50),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Days of week to run (0=Mon, 1=Tue, ..., 6=Sun). Empty = all weekdays.'),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='description',
            field=models.TextField(blank=True, help_text='Task description'),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='interval_seconds',
            field=models.IntegerField(default=60, help_text='Interval in seconds for interval tasks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='recurring_end_hour',
            field=models.IntegerField(default=15, help_text='End hour for recurring window (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='recurring_end_minute',
            field=models.IntegerField(default=30, help_text='End minute for recurring window (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='recurring_interval_minutes',
            field=models.IntegerField(default=5, help_text='Interval in minutes within the recurring window', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='recurring_start_hour',
            field=models.IntegerField(default=9, help_text='Start hour for recurring window (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='recurring_start_minute',
            field=models.IntegerField(default=0, help_text='Start minute for recurring window (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='schedule_hour',
            field=models.IntegerField(default=9, help_text='Hour to run (0-23) for crontab tasks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='schedule_minute',
            field=models.IntegerField(default=0, help_text='Minute to run (0-59) for crontab tasks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='schedule_type',
            field=models.CharField(choices=[('crontab', 'Fixed Time (Crontab)'), ('interval', 'Interval'), ('recurring', 'Recurring Window')], default='crontab', help_text='Type of schedule: crontab (fixed time), interval, or recurring window', max_length=20),
        ),
        migrations.AddField(
            model_name='celerytaskstate',
            name='use_custom_schedule',
            field=models.BooleanField(default=False, help_text='Use custom schedule instead of system defaults'),
        ),
        migrations.AlterField(
            model_name='bklog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='celerytaskstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='credentialstore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dayreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nseflag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_market_data_tasks',
            field=models.BooleanField(default=False, help_text='Enable all market data fetching tasks'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_position_monitoring',
            field=models.BooleanField(default=False, help_text='Enable position monitoring tasks'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_reporting_tasks',
            field=models.BooleanField(default=False, help_text='Enable reporting and analytics tasks'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_risk_monitoring',
            field=models.BooleanField(default=False, help_text='Enable risk management tasks'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_strategy_tasks',
            field=models.BooleanField(default=False, help_text='Enable strategy execution tasks'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todaysposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tradingschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
