# Generated by Django 4.2.7 on 2026-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_bklog_id_alter_celerytaskstate_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bklog",
            name="task_category",
            field=models.CharField(
                choices=[
                    ("data", "Market Data"),
                    ("strategy", "Strategy Execution"),
                    ("transaction", "Transactions"),
                    ("position", "Position Monitoring"),
                    ("risk", "Risk Management"),
                    ("analytics", "Analytics & Reports"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                help_text="Category of the task",
                max_length=20,
            ),
        ),
    ]
