# Generated by Django 3.1.7 on 2026-02-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_neo_session_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytaskstate',
            name='task_params',
            field=models.JSONField(blank=True, default=dict, help_text="Task-specific parameters as JSON (e.g., {'top_contracts': 50})"),
        ),
    ]
