# Generated by Django 4.2.7 on 2026-02-06 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_bklog_id_alter_celerytaskstate_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingCoreConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("singleton_id", models.IntegerField(default=1, unique=True)),
                (
                    "options_strategy",
                    models.CharField(
                        choices=[
                            ("STRANGLE", "Short Strangle"),
                            ("BROKEN_IRON_CONDOR", "Broken Iron Condor"),
                            ("AUTO", "Auto (VIX-based decision)"),
                        ],
                        default="AUTO",
                        help_text="Options strategy to use: Strangle, Broken Iron Condor, or Auto (VIX-based)",
                        max_length=50,
                    ),
                ),
                (
                    "options_lots",
                    models.IntegerField(
                        default=1,
                        help_text="Number of lots for options trade",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "futures_lots",
                    models.IntegerField(
                        default=1,
                        help_text="Number of lots for futures trade",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "max_loss_per_trade",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Maximum loss allowed per trade in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "options_profit_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000,
                        help_text="Target profit for options positions in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "movement_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="Max % movement since market open to allow entry (e.g., 0.5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                    ),
                ),
                (
                    "require_telegram_confirmation",
                    models.BooleanField(
                        default=True,
                        help_text="Require user confirmation via Telegram before placing orders",
                    ),
                ),
                (
                    "confirmation_timeout_minutes",
                    models.IntegerField(
                        default=5,
                        help_text="Minutes to wait for user confirmation before revalidating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "auto_close_on_target",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically close position when profit target is hit",
                    ),
                ),
                (
                    "auto_close_on_stoploss",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically close position when stop-loss is hit",
                    ),
                ),
                (
                    "options_carry_forward_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000,
                        help_text="Close same day if profit >= this amount, else carry forward",
                        max_digits=10,
                    ),
                ),
                (
                    "vix_high_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="VIX above this = prefer Iron Condor (more protection)",
                        max_digits=5,
                    ),
                ),
                (
                    "vix_low_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=14.0,
                        help_text="VIX below this = prefer Strangle (more premium)",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Core Configuration",
                "verbose_name_plural": "Trading Core Configuration",
                "db_table": "trading_core_config",
            },
        ),
    ]
