# Generated by Django 4.2.7 on 2026-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_tradingcoreconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="enable_futures_trading",
            field=models.BooleanField(
                default=True, help_text="Enable futures trading algorithm"
            ),
        ),
        migrations.AlterField(
            model_name="tradingcoreconfig",
            name="options_strategy",
            field=models.CharField(
                choices=[
                    ("STRANGLE", "Short Strangle"),
                    ("BROKEN_IRON_CONDOR", "Broken Iron Condor"),
                    ("AUTO", "Auto (VIX-based decision)"),
                    ("NONE", "Disabled - No Options Trading"),
                ],
                default="AUTO",
                help_text="Options strategy: Strangle, Iron Condor, Auto, or None (disabled)",
                max_length=50,
            ),
        ),
    ]
