# Generated by Django 4.2.7 on 2026-02-06 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_tradingcoreconfig_enable_futures_trading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="manual_futures_lots",
            field=models.IntegerField(
                default=1,
                help_text="Fixed lots for futures (Manual mode)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="manual_options_lots",
            field=models.IntegerField(
                default=1,
                help_text="Fixed lots for options (Manual mode)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="margin_utilization_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="% of available margin to use (Auto mode)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="notification_level",
            field=models.CharField(
                choices=[
                    ("FULL_CONTROL", "Full Control - Confirm Everything"),
                    ("SUPERVISED", "Supervised - Confirm Major Actions"),
                    ("AUTONOMOUS", "Autonomous - Notifications Only"),
                ],
                default="FULL_CONTROL",
                help_text="Level of user control: Full Control (confirm all), Supervised (confirm major), Autonomous (auto-execute)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="position_sizing_mode",
            field=models.CharField(
                choices=[
                    ("TEST", "Test Mode (1 Lot Each)"),
                    ("MANUAL", "Manual (Fixed Lots)"),
                    ("AUTO", "Auto (Margin-Based)"),
                    ("SIMULATED", "Simulated (Paper Trade)"),
                ],
                default="TEST",
                help_text="How to determine position sizes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="simulated_futures_lots",
            field=models.IntegerField(
                default=30,
                help_text="Hypothetical lots for futures (Simulated mode)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="simulated_options_lots",
            field=models.IntegerField(
                default=100,
                help_text="Hypothetical lots for options (Simulated mode)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tradingcoreconfig",
            name="auto_close_on_stoploss",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED: Use notification_level=AUTONOMOUS instead",
            ),
        ),
        migrations.AlterField(
            model_name="tradingcoreconfig",
            name="auto_close_on_target",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED: Use notification_level=AUTONOMOUS instead",
            ),
        ),
        migrations.AlterField(
            model_name="tradingcoreconfig",
            name="futures_lots",
            field=models.IntegerField(
                default=1,
                help_text="DEPRECATED: Use manual_futures_lots instead",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tradingcoreconfig",
            name="options_lots",
            field=models.IntegerField(
                default=1,
                help_text="DEPRECATED: Use manual_options_lots instead",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tradingcoreconfig",
            name="require_telegram_confirmation",
            field=models.BooleanField(
                default=True, help_text="DEPRECATED: Use notification_level instead"
            ),
        ),
    ]
