# Generated by Django 4.2.7 on 2026-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_add_position_sizing_and_notification_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialstore",
            name="auto_login_date",
            field=models.DateField(
                blank=True,
                help_text="Date of last auto-login attempt (resets daily)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credentialstore",
            name="auto_login_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("in_progress", "In Progress"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="none",
                help_text="Today's auto-login status: none|in_progress|success|failed",
                max_length=20,
            ),
        ),
    ]
