# Generated by Django 4.2.7 on 2026-02-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_add_auto_login_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialstore",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile number with country code (e.g., +919999999999)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credentialstore",
            name="neo_base_url",
            field=models.URLField(
                blank=True,
                help_text="Dynamic base URL from v2 totp_validate()",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credentialstore",
            name="neo_data_center",
            field=models.CharField(
                blank=True,
                help_text="Data center from v2 totp_validate()",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credentialstore",
            name="totp_secret",
            field=models.CharField(
                blank=True,
                help_text="TOTP secret key for automated login",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="credentialstore",
            name="ucc",
            field=models.CharField(
                blank=True,
                help_text="Unique Client Code for Kotak Neo v2",
                max_length=50,
                null=True,
            ),
        ),
    ]
