# Generated by Django 4.2.7 on 2026-02-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_neo_v2_credential_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_builtin", models.BooleanField(default=False)),
                (
                    "task_states",
                    models.JSONField(
                        default=dict, help_text="Map of task_key -> bool (enabled)"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_builtin", "name"],
            },
        ),
    ]
