# Generated by Django 4.2.7 on 2026-03-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_add_task_preset_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_key",
                    models.CharField(
                        db_index=True,
                        help_text="Beat schedule key, e.g. 'monitor-and-manage-positions'",
                        max_length=120,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Wall-clock duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Condensed return value from the task function",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Exception message on FAILURE; empty on SUCCESS/SKIPPED",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["task_key", "started_at"],
                        name="core_taskex_task_ke_782646_idx",
                    ),
                    models.Index(
                        fields=["status", "started_at"],
                        name="core_taskex_status_480c18_idx",
                    ),
                ],
            },
        ),
    ]
