# Generated by Django 4.2.7 on 2026-04-10 04:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_task_execution_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="enable_paper_trading",
            field=models.BooleanField(
                default=False,
                help_text="Enable paper trading mode (simulates trades without real orders)",
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="paper_brokerage_pct",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0003"),
                help_text="Simulated brokerage percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="paper_futures_lots",
            field=models.IntegerField(
                default=30,
                help_text="Lots for paper futures trades",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="paper_initial_capital",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10000000"),
                help_text="Starting capital for paper trading (INR)",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="paper_options_lots",
            field=models.IntegerField(
                default=100,
                help_text="Lots for paper options trades",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="paper_slippage_pct",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0005"),
                help_text="Simulated adverse slippage percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="paper_trade_futures",
            field=models.BooleanField(
                default=True, help_text="Include futures in paper trading"
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="paper_trade_options",
            field=models.BooleanField(
                default=True, help_text="Include options in paper trading"
            ),
        ),
    ]
