# Generated by Django 4.2.7 on 2026-06-18 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_tradingcoreconfig_enable_paper_trading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="news_hard_block_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, raises HardRejectError instead of a soft warning when average market sentiment falls below news_hard_block_threshold.",
            ),
        ),
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="news_hard_block_threshold",
            field=models.FloatField(
                default=-0.5,
                help_text="Average market sentiment below which hard block triggers (default -0.5).",
                validators=[
                    django.core.validators.MinValueValidator(-1.0),
                    django.core.validators.MaxValueValidator(0.0),
                ],
            ),
        ),
    ]
