# Generated by Django 4.2.7 on 2026-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_news_intelligence_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialstore",
            name="neo_fin_key",
            field=models.CharField(
                blank=True,
                help_text="Kotak Neo fin key (alphabetical only, e.g. neotradeapi). Leave blank to use default.",
                max_length=100,
                null=True,
            ),
        ),
    ]
