# Generated by Django 4.2.7 on 2026-07-17 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_add_neo_fin_key_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingcoreconfig",
            name="default_batch_delay_seconds",
            field=models.IntegerField(
                default=15,
                help_text="Default seconds to wait between order batches (e.g. 10-lot blocks). The wait always happens regardless of whether the previous batch fully filled, partially filled, or failed — never retried early. Used by Cover Position and automated futures execution; the manual Verify Trade and Strangle forms let the user override this per order.",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
    ]
