"""
Parser for MF Central CAS PDFs generated by Stimulsoft Reports.

These PDFs are distributed with .xlsx extensions by MF Central but are
real PDF documents. casparser cannot parse them; we use pdfplumber instead.

Layout per page:
  AMC Name line              e.g. "Kotak Mutual Fund"
  FOLIO NO: <n> KYC : OK
  <Scheme Name> (Advisor: ...) ISIN: <ISIN>Opening Unit Balance: <n>
  [transaction rows: DD-MMM-YYYY  <desc>  <amount>  <units>  <nav>  <balance>]
  [--- No Transaction during this statement period ---]
  Closing Unit Balance: <n> Nav as on <date>: INR <nav> Valuation on <date> : INR <val>
"""

from __future__ import annotations
import re
import logging
from datetime import datetime
from .base import CASData, AccountInfo, HoldingEntry, TransactionEntry

logger = logging.getLogger('apps.investments')

_PAN_RE     = re.compile(r'PAN:\s*([A-Z]{5}[0-9]{4}[A-Z])')
_PERIOD_RE  = re.compile(r'From Date\s*:\s*(\d{2}-[A-Za-z]{3}-\d{4}).*?To Date\s*:\s*(\d{2}-[A-Za-z]{3}-\d{4})')
_FOLIO_RE   = re.compile(r'FOLIO NO:\s*(\S+)')
_ISIN_RE    = re.compile(r'ISIN:\s*(IN[A-Z0-9]{10})')
_ISIN_LOOSE = re.compile(r'IN[A-Z0-9]{10}')           # fallback when "ISIN:" tag is mangled
_OPENING_RE = re.compile(r'[Oo]pening Unit Balance:\s*([\d,\.]+)')
_SCHEME_LINE_RE = re.compile(r'[Oo]pening Unit Balance:')
_CLOSING_RE = re.compile(
    r'Closing Unit Balance:\s*([\d,\.]+)\s+Nav as on\s+[\w\-]+:\s*INR\s+([\d,\.]+)\s+Valuation on[^:]+:\s*INR\s*([\d,\.]+)'
)
_TXN_RE = re.compile(
    r'^(\d{2}-[A-Za-z]{3}-\d{4})\s+(.+?)\s+([\d,\.]+)\s+([\d,\.]+)\s+([\d,\.]+)\s+([\d,\.]+)\s*$'
)
_AMC_RE = re.compile(
    r'^([A-Z][A-Za-z &\-\.]+(?:Mutual Fund|Asset Management(?:\s+Co\.?(?:\s+Ltd\.?)?)?|AMC|Investments?))\s*$'
)
_DATE_FMT = '%d-%b-%Y'


def _num(s: str) -> float:
    try:
        return float(str(s).replace(',', '').strip())
    except (ValueError, TypeError):
        return 0.0


def _txn_type(desc: str) -> str:
    d = desc.lower()
    if any(k in d for k in ('switch out', 'redemption', 'redeem')):
        return 'REDEMPTION'
    if 'switch in' in d:
        return 'SWITCH_IN'
    if 'dividend' in d:
        return 'DIVIDEND'
    if any(k in d for k in ('sip', 'purchase', 'lumpsum', 'installment', 'systematic')):
        return 'PURCHASE'
    return 'PURCHASE'


def parse_mfcentral_cas(pdf_path: str, password: str = '') -> CASData:
    """
    Parse an MF Central CAS PDF and return a CASData object.
    Raises ValueError if no holdings are found.
    """
    try:
        import pdfplumber
    except ImportError:
        raise RuntimeError('pdfplumber is required. Run: pip install pdfplumber')

    lines: list[str] = []
    with pdfplumber.open(pdf_path, password=password or '') as pdf:
        for page in pdf.pages:
            text = page.extract_text() or ''
            lines.extend(text.split('\n'))

    full_text = '\n'.join(lines)

    # ── Investor info ──────────────────────────────────────────────────
    pan = ''
    pan_m = _PAN_RE.search(full_text)
    if pan_m:
        pan = pan_m.group(1)

    stmt_month = stmt_year = None
    period_m = _PERIOD_RE.search(full_text)
    if period_m:
        try:
            to_date = datetime.strptime(period_m.group(2), _DATE_FMT)
            stmt_month = to_date.month
            stmt_year  = to_date.year
        except ValueError:
            pass

    # Investor name: appears on a line near PAN (before or after)
    name = ''
    for i, line in enumerate(lines):
        if pan and pan in line:
            # Check previous lines for a name (typical layout)
            for offset in range(1, 5):
                candidate = lines[i - offset].strip() if i >= offset else ''
                if candidate and not any(k in candidate for k in ('Statement', 'Date', 'Page', 'CAS', 'PAN')):
                    name = candidate
                    break
            break

    account_info = AccountInfo(
        holder_name=name,
        pan_masked=pan,
        statement_month=stmt_month,
        statement_year=stmt_year,
        depository='',
    )

    # ── Holdings & Transactions ────────────────────────────────────────
    holdings: list[HoldingEntry]     = []
    transactions: list[TransactionEntry] = []

    current_amc      = ''
    current_folio    = ''
    current_isin     = ''
    current_scheme   = ''
    current_opening  = 0.0
    awaiting_scheme  = False   # True immediately after a FOLIO line

    # Lines to skip when looking for the scheme line after FOLIO
    _SKIP_AFTER_FOLIO = re.compile(
        r'^(---|\(INR\)|Date\s+Transaction|SoA Holdings|Demat Holdings|Price$|'
        r'Consolidated Account|From Date|Page \d+|MFCentral)',
        re.IGNORECASE,
    )

    seen_folio_isin: set[tuple[str, str]] = set()

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        # ── AMC header ─────────────────────────────────────────────────
        amc_m = _AMC_RE.match(stripped)
        if amc_m:
            current_amc = amc_m.group(1).strip()
            awaiting_scheme = False
            continue

        # ── Folio ──────────────────────────────────────────────────────
        folio_m = _FOLIO_RE.search(stripped)
        if folio_m:
            current_folio   = folio_m.group(1)
            current_isin    = ''
            current_scheme  = ''
            current_opening = 0.0
            awaiting_scheme = True
            continue

        # ── Scheme line detection ───────────────────────────────────────
        # A line is a scheme line if:
        #   (a) It contains a parseable "ISIN: INxxxxxx" tag, OR
        #   (b) It contains "Opening Unit Balance:" (handles page-split case), OR
        #   (c) We're awaiting a scheme line after FOLIO and this isn't a skip-line
        has_isin    = bool(_ISIN_RE.search(stripped))
        has_opening = bool(_SCHEME_LINE_RE.search(stripped))
        is_folio_fallback = awaiting_scheme and not _SKIP_AFTER_FOLIO.match(stripped)

        if has_isin or has_opening or is_folio_fallback:
            awaiting_scheme = False

            # Extract ISIN (clean pattern first, loose fallback)
            isin_m = _ISIN_RE.search(stripped)
            if isin_m:
                current_isin = isin_m.group(1)
            elif not has_opening:
                # Loose: any IN + 10 uppercase alphanumeric
                loose_m = _ISIN_LOOSE.search(stripped)
                if loose_m:
                    current_isin = loose_m.group(0)

            # Extract scheme name (everything before the first annotation marker)
            scheme_raw = stripped
            for marker in ['ISIN:', '(Advisor:', '(formerly', '(Erstwhile', 'Opening Unit']:
                idx = stripped.find(marker)
                if idx > 5:           # avoid clipping very short strings
                    scheme_raw = stripped[:idx]
                    break
            scheme_raw = re.sub(r'\s*\([^)]*\)\s*$', '', scheme_raw).strip()
            if scheme_raw:
                current_scheme = scheme_raw

            open_m = _OPENING_RE.search(stripped)
            if open_m:
                current_opening = _num(open_m.group(1))
            continue

        # ── Closing balance line → emit holding ────────────────────────
        closing_m = _CLOSING_RE.search(stripped)
        if closing_m and (current_isin or current_scheme):
            closing_units = _num(closing_m.group(1))
            nav           = _num(closing_m.group(2))
            valuation     = _num(closing_m.group(3))

            # Dedup key: prefer ISIN, fall back to scheme name
            key = (current_isin or current_scheme, current_folio)
            if key not in seen_folio_isin:
                seen_folio_isin.add(key)
                if closing_units > 0 or valuation > 0:
                    holdings.append(HoldingEntry(
                        isin=current_isin,
                        security_name=current_scheme,
                        asset_class='M',
                        quantity=closing_units,
                        current_price=nav,
                        current_value=valuation,
                        extra_data={
                            'folio': current_folio,
                            'amc': current_amc,
                            'opening_units': current_opening,
                        },
                    ))

            # Reset scheme state (keep folio/AMC; next scheme on same folio is possible)
            current_isin   = ''
            current_scheme = ''
            current_opening = 0.0
            continue

        # ── Transaction line ────────────────────────────────────────────
        txn_m = _TXN_RE.match(stripped)
        if txn_m and current_isin:
            try:
                txn_date = datetime.strptime(txn_m.group(1), _DATE_FMT).date()
                desc     = txn_m.group(2).strip()
                amount   = _num(txn_m.group(3))
                units    = _num(txn_m.group(4))
                nav_t    = _num(txn_m.group(5))
                balance  = _num(txn_m.group(6))

                transactions.append(TransactionEntry(
                    isin=current_isin,
                    security_name=current_scheme,
                    transaction_date=txn_date,
                    order_no='',
                    description=desc,
                    transaction_type=_txn_type(desc),
                    opening_balance=0.0,
                    debit=0.0  if units >= 0 else abs(units),
                    credit=units if units >= 0 else 0.0,
                    closing_balance=balance,
                    amount=amount,
                    nav_at_transaction=nav_t,
                ))
            except (ValueError, IndexError):
                pass

    if not holdings:
        raise ValueError('No MF holdings found in this PDF — may not be an MF Central CAS')

    # Aggregate multiple folios of the same ISIN (sum units + values; collect folio list)
    from collections import defaultdict
    agg: dict[str, dict] = {}
    for h in holdings:
        if h.isin not in agg:
            agg[h.isin] = {
                'name': h.security_name, 'asset_class': h.asset_class,
                'units': 0.0, 'value': 0.0, 'price': h.current_price,
                'folios': [], 'amc': h.extra_data.get('amc', ''),
            }
        e = agg[h.isin]
        e['units'] += h.quantity
        e['value'] += h.current_value
        folio = h.extra_data.get('folio', '')
        if folio and folio not in e['folios']:
            e['folios'].append(folio)
        # Use the latest NAV (they should be identical across folios)
        if h.current_price:
            e['price'] = h.current_price

    aggregated = [
        HoldingEntry(
            isin=isin,
            security_name=e['name'],
            asset_class=e['asset_class'],
            quantity=round(e['units'], 3),
            current_price=e['price'],
            current_value=round(e['value'], 2),
            extra_data={'folios': e['folios'], 'amc': e['amc']},
        )
        for isin, e in agg.items()
    ]

    logger.info('MF Central CAS parsed: %d raw entries → %d unique ISINs, %d transactions, PAN=%s',
                len(holdings), len(aggregated), len(transactions), pan)
    return CASData(
        account_info=account_info,
        holdings=aggregated,
        transactions=transactions,
        cas_type='CAMS',
    )
