# Generated by Django 3.1.7 on 2025-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('event_date', models.DateField(db_index=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('country', models.CharField(default='IN', max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('actual', models.CharField(blank=True, max_length=50)),
                ('forecast', models.CharField(blank=True, max_length=50)),
                ('previous', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('exchange', models.CharField(default='NSE', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField(default=0)),
                ('open_interest', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'market_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OptionChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('underlying', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=15)),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('oi', models.BigIntegerField(default=0)),
                ('oi_change', models.BigIntegerField(default=0)),
                ('iv', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('theta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vega', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'option_chain',
                'ordering': ['underlying', 'expiry_date', 'strike'],
            },
        ),
        migrations.AddIndex(
            model_name='optionchain',
            index=models.Index(fields=['underlying', 'expiry_date', 'option_type'], name='option_chai_underly_795ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['symbol', '-timestamp'], name='market_data_symbol_119ced_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('symbol', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date', 'importance'], name='events_event_d_02722f_idx'),
        ),
    ]
