# Generated by Django 3.1.7 on 2025-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_contractstockdata_alter_event_id_alter_marketdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('company', models.CharField(max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('call_type', models.CharField(choices=[('EARNINGS', 'Earnings Call'), ('ANALYST', 'Analyst Meet'), ('INVESTOR', 'Investor Day'), ('CONFERENCE', 'Conference Call')], max_length=50)),
                ('call_date', models.DateField(db_index=True)),
                ('quarter', models.CharField(blank=True, help_text='Q1 FY24, etc.', max_length=10)),
                ('transcript', models.TextField(help_text='Full call transcript')),
                ('participants', models.JSONField(default=list, help_text='List of participants')),
                ('executive_summary', models.TextField(blank=True, help_text='LLM-generated summary')),
                ('key_highlights', models.JSONField(default=list, help_text='Key points')),
                ('financial_metrics', models.JSONField(default=dict, help_text='Extracted financial data')),
                ('management_tone', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=20, null=True)),
                ('outlook', models.TextField(blank=True, help_text='Future outlook/guidance')),
                ('concerns_raised', models.JSONField(default=list, help_text='Concerns/risks mentioned')),
                ('trading_signal', models.CharField(blank=True, choices=[('BULLISH', 'Bullish'), ('NEUTRAL', 'Neutral'), ('BEARISH', 'Bearish')], max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Signal confidence (0-1)', null=True)),
                ('embedding_stored', models.BooleanField(default=False)),
                ('embedding_id', models.CharField(blank=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investor_calls',
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('source_type', models.CharField(choices=[('NEWS', 'News Article'), ('CALL', 'Investor Call'), ('REPORT', 'Research Report'), ('MANUAL', 'Manual Entry')], max_length=50)),
                ('source_id', models.IntegerField(help_text='ID of source record')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('content_chunk', models.TextField(help_text='Processed text chunk')),
                ('chunk_index', models.IntegerField(default=0, help_text='Chunk position in document')),
                ('metadata', models.JSONField(default=dict, help_text='Additional context')),
                ('symbols', models.JSONField(default=list, help_text='Related symbols')),
                ('sectors', models.JSONField(default=list, help_text='Related sectors')),
                ('topics', models.JSONField(default=list, help_text='Topics covered')),
                ('embedding_id', models.CharField(help_text='ChromaDB ID', max_length=100, unique=True)),
                ('embedding_stored', models.BooleanField(default=True)),
                ('times_retrieved', models.IntegerField(default=0)),
                ('last_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('relevance_score', models.FloatField(default=0.0, help_text='Average relevance in retrievals')),
            ],
            options={
                'db_table': 'knowledge_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(help_text='News source (MoneyControl, ET, etc.)', max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('summary', models.TextField(help_text='Article summary/excerpt')),
                ('content', models.TextField(help_text='Full article content')),
                ('category', models.CharField(blank=True, help_text='Market, Economy, Corporate, etc.', max_length=50)),
                ('tags', models.JSONField(default=list, help_text='Article tags/keywords')),
                ('symbols_mentioned', models.JSONField(default=list, help_text='Stock symbols mentioned')),
                ('sectors_mentioned', models.JSONField(default=list, help_text='Sectors mentioned')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score (-1 to 1)', null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=20, null=True)),
                ('sentiment_confidence', models.FloatField(blank=True, help_text='Confidence (0-1)', null=True)),
                ('llm_summary', models.TextField(blank=True, help_text='LLM-generated summary')),
                ('key_insights', models.JSONField(default=list, help_text='Key insights extracted')),
                ('market_impact', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, null=True)),
                ('embedding_stored', models.BooleanField(default=False, help_text='Embedding stored in ChromaDB')),
                ('embedding_id', models.CharField(blank=True, help_text='ChromaDB document ID', max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractstockdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optionchain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tlstockdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['-published_at'], name='news_articl_publish_d1e015_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', '-published_at'], name='news_articl_source_6b9a79_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category', '-published_at'], name='news_articl_categor_ac5bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['source_type', 'source_id'], name='knowledge_b_source__d86d36_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['embedding_id'], name='knowledge_b_embeddi_dd6f84_idx'),
        ),
        migrations.AddIndex(
            model_name='investorcall',
            index=models.Index(fields=['symbol', '-call_date'], name='investor_ca_symbol_fad2da_idx'),
        ),
        migrations.AddIndex(
            model_name='investorcall',
            index=models.Index(fields=['call_type', '-call_date'], name='investor_ca_call_ty_063c95_idx'),
        ),
    ]
