# Generated by Django 4.2.7 on 2025-11-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_alter_contractdata_id_alter_contractstockdata_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionchain",
            name="spot_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Spot price at the time of data fetch",
                max_digits=15,
                null=True,
            ),
        ),
    ]
