# Generated by Django 4.2.7 on 2025-11-22 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0005_optionchain_spot_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepDiveAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("expiry", models.DateField()),
                (
                    "level1_score",
                    models.IntegerField(help_text="Level 1 composite score"),
                ),
                (
                    "level1_direction",
                    models.CharField(default="NEUTRAL", max_length=20),
                ),
                (
                    "report",
                    models.JSONField(help_text="Complete deep-dive analysis report"),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("EXECUTED", "Executed Trade"),
                            ("MODIFIED", "Modified Parameters"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending Decision"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, help_text="User notes on decision"),
                ),
                ("decision_timestamp", models.DateTimeField(blank=True, null=True)),
                ("trade_executed", models.BooleanField(default=False)),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("lot_size", models.IntegerField(blank=True, null=True)),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L in rupees",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "pnl_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "conviction_score",
                    models.IntegerField(
                        blank=True, help_text="Conviction score from report", null=True
                    ),
                ),
                ("risk_grade", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deep_dive_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deep_dive_analysis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "expiry"],
                        name="deep_dive_a_symbol_5f6173_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="deep_dive_a_user_id_913fcb_idx",
                    ),
                    models.Index(
                        fields=["decision"], name="deep_dive_a_decisio_4d756c_idx"
                    ),
                    models.Index(
                        fields=["trade_executed"], name="deep_dive_a_trade_e_202562_idx"
                    ),
                ],
            },
        ),
    ]
