# Generated by Django 4.2.7 on 2025-12-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_deepdiveanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractdata",
            name="day_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="last_updated",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="lot_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="oi",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="oi_change",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="pct_day_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="pct_oi_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="pct_volume_shares_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="prev_close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="prev_day_oi",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="prev_day_vol",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="shares_traded",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="spot",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="traded_contracts",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contractdata",
            name="traded_contracts_change_pct",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
