# Generated by Django 4.2.7 on 2026-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_newsarticle_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="impact_analysis",
            field=models.JSONField(
                default=dict, help_text="Complete LLM impact analysis results"
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="impact_category",
            field=models.CharField(
                blank=True,
                help_text="Impact category (US_FED, GLOBAL_MARKETS, COMMODITIES, etc.)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="impact_reasoning",
            field=models.TextField(
                blank=True, help_text="LLM reasoning for impact assessment"
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="market_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BEARISH", "Bearish"),
                    ("NEUTRAL", "Neutral"),
                    ("BULLISH", "Bullish"),
                ],
                help_text="Market direction indicated by news",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="news_type",
            field=models.CharField(
                choices=[
                    ("STOCK", "Stock News"),
                    ("INDUSTRY", "Industry News"),
                    ("COMPETITOR", "Competitor News"),
                    ("MARKET", "Market News"),
                ],
                db_index=True,
                default="STOCK",
                help_text="Type of news article",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="relevance_score",
            field=models.FloatField(
                blank=True, help_text="Relevance to Indian markets (0-1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="search_keywords",
            field=models.JSONField(
                default=list, help_text="Keywords used to fetch this article"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["news_type", "-published_at"],
                name="news_articl_news_ty_be3071_idx",
            ),
        ),
    ]
