# Generated by Django 4.2.7 on 2026-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0009_add_news_impact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlstockdata",
            name="trendlyne_id",
            field=models.IntegerField(
                blank=True,
                help_text="Trendlyne internal stock ID extracted from URL",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AnalystReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("nse_code", models.CharField(db_index=True, max_length=20)),
                ("trendlyne_id", models.IntegerField(blank=True, null=True)),
                ("report_date", models.DateField(db_index=True)),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="Brokerage/analyst name", max_length=200
                    ),
                ),
                ("report_title", models.CharField(blank=True, max_length=500)),
                (
                    "ltp_at_report",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stock price when report was published",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "upside_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("STRONG_BUY", "Strong Buy"),
                            ("BUY", "Buy"),
                            ("HOLD", "Hold"),
                            ("SELL", "Sell"),
                            ("STRONG_SELL", "Strong Sell"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True, help_text="URL to PDF on Trendlyne", max_length=1000
                    ),
                ),
                (
                    "pdf_local_path",
                    models.CharField(
                        blank=True,
                        help_text="Local path to downloaded PDF",
                        max_length=500,
                    ),
                ),
                (
                    "pdf_content_text",
                    models.TextField(blank=True, help_text="Extracted text from PDF"),
                ),
                (
                    "llm_summary",
                    models.TextField(
                        blank=True, help_text="LLM-generated summary of report"
                    ),
                ),
                (
                    "key_insights",
                    models.JSONField(
                        default=list, help_text="Key insights extracted by LLM"
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment score from -1 (bearish) to 1 (bullish)",
                        null=True,
                    ),
                ),
                (
                    "trade_recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("NEUTRAL", "Neutral"),
                            ("BEARISH", "Bearish"),
                        ],
                        help_text="LLM-derived trade recommendation",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        default=list, help_text="Risk factors identified by LLM"
                    ),
                ),
                (
                    "catalysts",
                    models.JSONField(
                        default=list, help_text="Positive catalysts identified by LLM"
                    ),
                ),
                ("llm_processed", models.BooleanField(default=False)),
                ("llm_processed_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_download_success", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "analyst_reports",
                "ordering": ["-report_date"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-report_date"],
                        name="analyst_rep_symbol_57f8f9_idx",
                    ),
                    models.Index(
                        fields=["nse_code", "-report_date"],
                        name="analyst_rep_nse_cod_874c89_idx",
                    ),
                    models.Index(
                        fields=["recommendation_type", "-report_date"],
                        name="analyst_rep_recomme_e8598b_idx",
                    ),
                    models.Index(
                        fields=["llm_processed"], name="analyst_rep_llm_pro_943fe6_idx"
                    ),
                ],
                "unique_together": {("symbol", "report_date", "author")},
            },
        ),
        migrations.CreateModel(
            name="AnalystPriceTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("nse_code", models.CharField(db_index=True, max_length=20)),
                (
                    "trendlyne_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("stock_name", models.CharField(blank=True, max_length=100)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "upside_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage upside to average target price",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "analyst_count",
                    models.IntegerField(
                        default=0, help_text="Number of analysts covering"
                    ),
                ),
                ("strong_buy_count", models.IntegerField(default=0)),
                ("buy_count", models.IntegerField(default=0)),
                ("hold_count", models.IntegerField(default=0)),
                ("sell_count", models.IntegerField(default=0)),
                ("strong_sell_count", models.IntegerField(default=0)),
                ("fetch_timestamp", models.DateTimeField(auto_now=True)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("scrape_success", models.BooleanField(default=True)),
                (
                    "scrape_error",
                    models.TextField(
                        blank=True, help_text="Error message if scrape failed"
                    ),
                ),
            ],
            options={
                "db_table": "analyst_price_targets",
                "ordering": ["-fetch_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-fetch_timestamp"],
                        name="analyst_pri_symbol_eca72f_idx",
                    ),
                    models.Index(
                        fields=["nse_code", "-fetch_timestamp"],
                        name="analyst_pri_nse_cod_a721dc_idx",
                    ),
                ],
            },
        ),
    ]
