# Generated by Django 4.2.7 on 2026-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0010_tlstockdata_trendlyne_id_analystreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="already_priced_in",
            field=models.BooleanField(
                blank=True,
                help_text="LLM judgment: is this news already reflected in the current price?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="event_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LLM-classified event type: EARNINGS, GUIDANCE, ACQUISITION, REGULATORY, LEGAL, MACRO, SECTOR, OPINION, GENERAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="source_quality_score",
            field=models.FloatField(
                blank=True,
                default=0.6,
                help_text="Source authority weight (0.4–1.0). Set from NEWS_SOURCE_QUALITY lookup.",
                null=True,
            ),
        ),
    ]
