# Generated by Django 4.2.7 on 2026-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0011_news_intelligence_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OIIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("trading_date", models.DateField(db_index=True)),
                (
                    "buildup_type",
                    models.CharField(
                        choices=[
                            ("LONG_BUILDUP", "Long Build-up"),
                            ("SHORT_BUILDUP", "Short Build-up"),
                            ("LONG_UNWINDING", "Long Unwinding"),
                            ("SHORT_COVERING", "Short Covering"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("buildup_label", models.CharField(blank=True, max_length=60)),
                ("interpretation_text", models.TextField(blank=True)),
                ("consecutive_days", models.IntegerField(default=1)),
                (
                    "consecutive_type",
                    models.CharField(
                        choices=[
                            ("LONG_BUILDUP", "Long Build-up"),
                            ("SHORT_BUILDUP", "Short Build-up"),
                            ("LONG_UNWINDING", "Long Unwinding"),
                            ("SHORT_COVERING", "Short Covering"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                (
                    "pattern_detected",
                    models.CharField(
                        choices=[
                            ("ACCUMULATION", "Institutional Accumulation"),
                            ("DISTRIBUTION", "Distribution"),
                            ("CAPITULATION", "Capitulation"),
                            ("SHORT_SQUEEZE", "Short Squeeze Setup"),
                            ("LONG_UNWINDING", "Long Unwinding"),
                            ("TREND_REVERSAL", "Trend Reversal"),
                            ("HIGH_CONVICTION", "High Conviction Trend"),
                            ("WEAK_RALLY", "Weak Conviction Rally"),
                            ("TREND_EXHAUSTION", "Trend Exhaustion"),
                            ("NONE", "No Special Pattern"),
                        ],
                        default="NONE",
                        max_length=30,
                    ),
                ),
                ("pattern_description", models.TextField(blank=True)),
                (
                    "oi_momentum_score",
                    models.FloatField(
                        default=50.0,
                        help_text="0-100, higher = stronger bullish OI positioning",
                    ),
                ),
                (
                    "confidence_level",
                    models.FloatField(
                        default=50.0, help_text="0-100 confidence in the interpretation"
                    ),
                ),
                ("weekly_summary", models.TextField(blank=True)),
                ("monthly_summary", models.TextField(blank=True)),
                ("ai_narrative", models.TextField(blank=True)),
                ("last_20_bullish_count", models.IntegerField(default=0)),
                ("last_20_bearish_count", models.IntegerField(default=0)),
                ("last_5_buildup_types", models.JSONField(default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "oi_intelligence",
                "ordering": ["symbol", "-trading_date"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-trading_date"],
                        name="oi_intellig_symbol_c9cb1c_idx",
                    )
                ],
                "unique_together": {("symbol", "trading_date")},
            },
        ),
        migrations.CreateModel(
            name="OIHistorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                ("trading_date", models.DateField(db_index=True)),
                ("close_price", models.FloatField(blank=True, null=True)),
                ("price_change_pct", models.FloatField(blank=True, null=True)),
                ("futures_price", models.FloatField(blank=True, null=True)),
                ("oi", models.BigIntegerField(blank=True, null=True)),
                ("oi_change_pct", models.FloatField(blank=True, null=True)),
                ("total_fno_oi", models.BigIntegerField(blank=True, null=True)),
                ("pcr_oi", models.FloatField(blank=True, null=True)),
                ("mwpl_pct", models.FloatField(blank=True, null=True)),
                ("rollover_pct", models.FloatField(blank=True, null=True)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("traded_contracts", models.BigIntegerField(blank=True, null=True)),
                ("delivery_pct", models.FloatField(blank=True, null=True)),
                (
                    "buildup_type",
                    models.CharField(
                        choices=[
                            ("LONG_BUILDUP", "Long Build-up"),
                            ("SHORT_BUILDUP", "Short Build-up"),
                            ("LONG_UNWINDING", "Long Unwinding"),
                            ("SHORT_COVERING", "Short Covering"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                (
                    "oi_momentum_score",
                    models.FloatField(
                        blank=True,
                        help_text="0-100 OI momentum score at this snapshot",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="0-100 confidence in buildup classification",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "oi_history_snapshot",
                "ordering": ["symbol", "-trading_date"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-trading_date"],
                        name="oi_history__symbol_603edb_idx",
                    )
                ],
                "unique_together": {("symbol", "trading_date")},
            },
        ),
    ]
