# Generated by Django 3.1.7 on 2025-11-15 07:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('period_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('avg_capital_deployed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('strategy_performance', models.JSONField(default=dict, help_text='P&L by strategy')),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='accounts.brokeraccount')),
            ],
            options={
                'db_table': 'performance',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DailyPnL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(db_index=True)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('trades_count', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('starting_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ending_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_capital_deployed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('risk_limits_breached', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_pnls', to='accounts.brokeraccount')),
            ],
            options={
                'db_table': 'daily_pnl',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['account', 'period_type', '-period_end'], name='performance_account_174726_idx'),
        ),
        migrations.AddIndex(
            model_name='dailypnl',
            index=models.Index(fields=['account', '-date'], name='daily_pnl_account_bfde84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypnl',
            unique_together={('account', 'date')},
        ),
    ]
