# Generated by Django 3.1.7 on 2025-11-15 09:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('positions', '0003_auto_20251115_1512'),
        ('analytics', '0002_alter_dailypnl_id_alter_performance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Session name/description', max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='STOPPED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('min_trades_required', models.IntegerField(default=10, help_text='Minimum trades to start learning')),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Minimum confidence % to suggest changes', max_digits=5)),
                ('trades_analyzed', models.IntegerField(default=0)),
                ('patterns_discovered', models.IntegerField(default=0)),
                ('parameters_adjusted', models.IntegerField(default=0)),
                ('pre_learning_win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('post_learning_win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('improvement_pct', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Overall improvement percentage', max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'learning_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='dailypnl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TradePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('entry_conditions', models.JSONField(default=dict, help_text='Market conditions at entry: VIX, trends, indicators, etc.')),
                ('entry_score', models.DecimalField(decimal_places=2, help_text='Quality score of entry (0-100)', max_digits=5)),
                ('exit_conditions', models.JSONField(blank=True, default=dict)),
                ('exit_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quality score of exit (0-100)', max_digits=5, null=True)),
                ('max_favorable_excursion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum profit during trade', max_digits=15)),
                ('max_adverse_excursion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum loss during trade', max_digits=15)),
                ('hold_duration_minutes', models.IntegerField(default=0)),
                ('entry_time_quality', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')], default='AVERAGE', max_length=20)),
                ('what_worked', models.TextField(blank=True, help_text='What went well')),
                ('what_failed', models.TextField(blank=True, help_text="What didn't work")),
                ('lessons_learned', models.TextField(blank=True, help_text='Key takeaways')),
                ('similar_patterns_count', models.IntegerField(default=0, help_text='Number of similar historical trades')),
                ('pattern_success_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Success rate of this pattern', max_digits=5, null=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analysis', to='positions.position')),
            ],
            options={
                'db_table': 'trade_performance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('metric_type', models.CharField(choices=[('WIN_RATE', 'Win Rate'), ('PROFIT_FACTOR', 'Profit Factor'), ('AVG_PROFIT', 'Average Profit'), ('AVG_LOSS', 'Average Loss'), ('MAX_DRAWDOWN', 'Max Drawdown'), ('SHARPE_RATIO', 'Sharpe Ratio'), ('ENTRY_ACCURACY', 'Entry Accuracy'), ('EXIT_EFFICIENCY', 'Exit Efficiency'), ('RISK_REWARD', 'Risk/Reward Ratio')], max_length=30)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('strategy', models.CharField(blank=True, max_length=50)),
                ('time_period', models.CharField(blank=True, help_text="e.g., 'last_7_days'", max_length=50)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.learningsession')),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='ParameterAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('parameter_name', models.CharField(help_text="Parameter name (e.g., 'base_delta_pct')", max_length=100)),
                ('parameter_category', models.CharField(help_text='Category: strategy, risk, entry, exit, etc.', max_length=50)),
                ('current_value', models.CharField(max_length=100)),
                ('suggested_value', models.CharField(max_length=100)),
                ('reason', models.TextField(help_text='Why this adjustment is suggested')),
                ('supporting_data', models.JSONField(help_text='Data supporting this adjustment (patterns, statistics)')),
                ('expected_improvement_pct', models.DecimalField(decimal_places=4, help_text='Expected improvement in win rate or P&L', max_digits=10)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Confidence in this suggestion (0-100)', max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('TESTING', 'Testing')], default='SUGGESTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('test_start_date', models.DateField(blank=True, null=True)),
                ('test_end_date', models.DateField(blank=True, null=True)),
                ('actual_improvement_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Actual improvement observed during testing', max_digits=10, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='analytics.learningsession')),
            ],
            options={
                'db_table': 'parameter_adjustments',
                'ordering': ['-confidence', '-expected_improvement_pct'],
            },
        ),
        migrations.CreateModel(
            name='LearningPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('pattern_type', models.CharField(choices=[('ENTRY_TIMING', 'Entry Timing'), ('STRIKE_SELECTION', 'Strike Selection'), ('MARKET_CONDITION', 'Market Condition'), ('DELTA_BEHAVIOR', 'Delta Behavior'), ('EXIT_TIMING', 'Exit Timing'), ('VIX_PATTERN', 'VIX Pattern'), ('SECTOR_CORRELATION', 'Sector Correlation'), ('OTHER', 'Other')], max_length=30)),
                ('name', models.CharField(help_text='Pattern name/description', max_length=200)),
                ('description', models.TextField(help_text='Detailed pattern description')),
                ('conditions', models.JSONField(help_text='JSON of conditions that define this pattern')),
                ('occurrences', models.IntegerField(default=0, help_text='Times pattern observed')),
                ('profitable_occurrences', models.IntegerField(default=0)),
                ('unprofitable_occurrences', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, help_text='Success rate percentage', max_digits=5)),
                ('avg_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average profit when pattern occurs', max_digits=15)),
                ('avg_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average loss when pattern occurs', max_digits=15)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Statistical confidence in this pattern (0-100)', max_digits=5)),
                ('is_actionable', models.BooleanField(default=False, help_text='Whether this pattern should influence trading decisions')),
                ('recommendation', models.TextField(blank=True, help_text='Trading recommendation based on this pattern')),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('ACTIVE', 'Active'), ('TESTING', 'Testing'), ('INVALIDATED', 'Invalidated')], default='TESTING', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='analytics.learningsession')),
            ],
            options={
                'db_table': 'learning_patterns',
                'ordering': ['-confidence_score', '-success_rate'],
            },
        ),
        migrations.AddIndex(
            model_name='tradeperformance',
            index=models.Index(fields=['entry_score'], name='trade_perfo_entry_s_db6f21_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeperformance',
            index=models.Index(fields=['-created_at'], name='trade_perfo_created_f84cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['metric_type', '-calculation_date'], name='performance_metric__e8a913_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['session', 'metric_type'], name='performance_session_ac5722_idx'),
        ),
        migrations.AddIndex(
            model_name='parameteradjustment',
            index=models.Index(fields=['status', '-confidence'], name='parameter_a_status_4f888d_idx'),
        ),
        migrations.AddIndex(
            model_name='parameteradjustment',
            index=models.Index(fields=['parameter_category'], name='parameter_a_paramet_e9feb3_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpattern',
            index=models.Index(fields=['pattern_type', '-confidence_score'], name='learning_pa_pattern_76f20b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpattern',
            index=models.Index(fields=['is_actionable', '-success_rate'], name='learning_pa_is_acti_8ed4b4_idx'),
        ),
    ]
