# Generated by Django 4.2.7 on 2026-01-27 09:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_apicredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0004_alter_dailypnl_id_alter_learningpattern_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialYearSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("fy_start", models.DateField(help_text="FY start date (April 1)")),
                ("fy_end", models.DateField(help_text="FY end date (March 31)")),
                (
                    "fy_label",
                    models.CharField(
                        help_text="Display label like 'FY2024-25'", max_length=20
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "All Strategies"),
                            ("kotak_strangle", "Kotak Strangle"),
                            ("kotak_broken_iron_condor", "Kotak Broken Iron Condor"),
                            ("icici_futures", "ICICI Futures"),
                        ],
                        default="",
                        help_text="Filter by strategy or empty for all",
                        max_length=30,
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "All Types"),
                            ("OPTIONS", "Options"),
                            ("FUTURES", "Futures"),
                        ],
                        default="",
                        help_text="Filter by trade type or empty for all",
                        max_length=10,
                    ),
                ),
                (
                    "total_trades",
                    models.IntegerField(
                        default=0, help_text="Total number of closed trades"
                    ),
                ),
                (
                    "winning_trades",
                    models.IntegerField(
                        default=0, help_text="Number of profitable trades"
                    ),
                ),
                (
                    "losing_trades",
                    models.IntegerField(default=0, help_text="Number of losing trades"),
                ),
                (
                    "breakeven_trades",
                    models.IntegerField(
                        default=0, help_text="Number of breakeven trades"
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all profits",
                        max_digits=15,
                    ),
                ),
                (
                    "gross_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all losses (positive number)",
                        max_digits=15,
                    ),
                ),
                (
                    "net_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Net profit/loss",
                        max_digits=15,
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total brokerage and other charges",
                        max_digits=15,
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Win rate percentage",
                        max_digits=6,
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross profit / Gross loss",
                        max_digits=8,
                    ),
                ),
                (
                    "average_win",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average profit per winning trade",
                        max_digits=15,
                    ),
                ),
                (
                    "average_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average loss per losing trade",
                        max_digits=15,
                    ),
                ),
                (
                    "largest_win",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Largest single winning trade",
                        max_digits=15,
                    ),
                ),
                (
                    "largest_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Largest single losing trade",
                        max_digits=15,
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum drawdown in absolute terms",
                        max_digits=15,
                    ),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum drawdown as percentage",
                        max_digits=8,
                    ),
                ),
                (
                    "monthly_pnl",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Monthly P&L breakdown: {'Apr': 1000, 'May': -500, ...}",
                    ),
                ),
                (
                    "best_month",
                    models.CharField(
                        blank=True, help_text="Best performing month", max_length=20
                    ),
                ),
                (
                    "best_month_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "worst_month",
                    models.CharField(
                        blank=True, help_text="Worst performing month", max_length=20
                    ),
                ),
                (
                    "worst_month_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_trade_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average trade duration in hours",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "avg_margin_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average margin deployed per trade",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "avg_return_on_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average ROM percentage",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "last_computed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When summary was last computed"
                    ),
                ),
                (
                    "trades_included_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last trade included in this summary",
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific account or NULL for all accounts",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fy_summaries",
                        to="accounts.brokeraccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fy_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year Summary",
                "verbose_name_plural": "Financial Year Summaries",
                "db_table": "financial_year_summary",
                "ordering": ["-fy_start"],
                "indexes": [
                    models.Index(
                        fields=["user", "fy_start"],
                        name="financial_y_user_id_11ac97_idx",
                    ),
                    models.Index(
                        fields=["account", "fy_start"],
                        name="financial_y_account_3447a4_idx",
                    ),
                    models.Index(
                        fields=["fy_label"], name="financial_y_fy_labe_bcc795_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="financialyearsummary",
            constraint=models.UniqueConstraint(
                fields=("user", "account", "fy_start", "strategy", "trade_type"),
                name="unique_fy_summary",
            ),
        ),
    ]
