# Generated by Django 4.2.7 on 2026-01-30 09:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0007_takentrade_takentrade_unique_user_suggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_remove_apicredential"),
        ("analytics", "0005_financialyearsummary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountReturns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("FY", "Financial Year"),
                            ("YTD", "Year to Date"),
                            ("ALL_TIME", "All Time"),
                        ],
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_label",
                    models.CharField(
                        blank=True,
                        help_text="Display label like 'Jan 2025' or 'FY2024-25'",
                        max_length=30,
                    ),
                ),
                (
                    "starting_capital",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "ending_capital",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "avg_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "absolute_return",
                    models.DecimalField(
                        decimal_places=2, help_text="Absolute P&L", max_digits=15
                    ),
                ),
                (
                    "percentage_return",
                    models.DecimalField(
                        decimal_places=4, help_text="Return percentage", max_digits=10
                    ),
                ),
                (
                    "annualized_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Annualized return (CAGR)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "volatility",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Standard deviation of returns",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sortino_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "calmar_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Annualized return / Max drawdown",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "avg_win",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "avg_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_brokerage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_taxes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "strategy_returns",
                    models.JSONField(
                        default=dict,
                        help_text="Returns by strategy: {'kotak_strangle': {...}, ...}",
                    ),
                ),
            ],
            options={
                "db_table": "account_returns",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="BenchmarkData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "benchmark",
                    models.CharField(
                        choices=[
                            ("NIFTY50", "Nifty 50"),
                            ("BANKNIFTY", "Bank Nifty"),
                            ("NIFTYIT", "Nifty IT"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("open", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "daily_return_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "cumulative_return_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cumulative return from FY start",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "benchmark_data",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyEquityCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "opening_capital",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Capital at market open",
                        max_digits=15,
                    ),
                ),
                (
                    "closing_capital",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Capital at market close",
                        max_digits=15,
                    ),
                ),
                (
                    "high_capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peak capital during the day",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "low_capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lowest capital during the day",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cumulative_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total P&L since inception",
                        max_digits=15,
                    ),
                ),
                (
                    "cumulative_return_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Cumulative return percentage",
                        max_digits=10,
                    ),
                ),
                (
                    "peak_capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="All-time high capital (for drawdown calc)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "current_drawdown",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current drawdown from peak",
                        max_digits=15,
                    ),
                ),
                (
                    "drawdown_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Drawdown as percentage",
                        max_digits=10,
                    ),
                ),
                (
                    "nifty_close",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "nifty_return_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Nifty's return on this day",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "alpha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Daily alpha vs Nifty",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("trades_taken", models.IntegerField(default=0)),
                ("trades_closed", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "daily_equity_curve",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MarketContextSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "snapshot_timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Exact time of snapshot"
                    ),
                ),
                (
                    "nifty_spot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "banknifty_spot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "india_vix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "nifty_day_change_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "nifty_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRONG_UP", "Strong Uptrend"),
                            ("UP", "Uptrend"),
                            ("SIDEWAYS", "Sideways"),
                            ("DOWN", "Downtrend"),
                            ("STRONG_DOWN", "Strong Downtrend"),
                        ],
                        max_length=15,
                    ),
                ),
                ("total_call_oi", models.BigIntegerField(blank=True, null=True)),
                ("total_put_oi", models.BigIntegerField(blank=True, null=True)),
                (
                    "pcr_oi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Put/Call ratio by OI",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "max_pain",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "rsi_14",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "macd_signal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete raw market data snapshot",
                    ),
                ),
            ],
            options={
                "db_table": "market_context_snapshot",
                "ordering": ["-snapshot_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("MODIFY", "Modified"),
                            ("IGNORE", "Ignored"),
                            ("AUTO_APPROVE", "Auto-Approved"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "decision_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the decision was made"
                    ),
                ),
                (
                    "time_to_decision_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Time from suggestion creation to decision",
                        null=True,
                    ),
                ),
                (
                    "suggestion_viewed_count",
                    models.IntegerField(
                        default=1,
                        help_text="How many times user viewed before deciding",
                    ),
                ),
                (
                    "market_context",
                    models.JSONField(
                        default=dict,
                        help_text="Market state: spot, vix, oi, trend, pcr, etc.",
                    ),
                ),
                (
                    "algorithm_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Algorithm's confidence score (0-100)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "algorithm_signal_strength",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Signal strength from algorithm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "original_parameters",
                    models.JSONField(
                        default=dict, help_text="Original parameters from suggestion"
                    ),
                ),
                (
                    "modified_parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User-modified parameters (for MODIFY decisions)",
                    ),
                ),
                (
                    "final_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final P&L if trade was taken",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "final_outcome",
                    models.CharField(
                        choices=[
                            ("PROFIT", "Profit"),
                            ("LOSS", "Loss"),
                            ("BREAKEVEN", "Breakeven"),
                            ("N/A", "Not Applicable"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "outcome_linked_at",
                    models.DateTimeField(
                        blank=True, help_text="When outcome was linked back", null=True
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(
                        blank=True, help_text="User's reason for the decision"
                    ),
                ),
                (
                    "market_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_logs",
                        to="analytics.marketcontextsnapshot",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_logs",
                        to="trading.tradesuggestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_decision_log",
                "ordering": ["-decision_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("total_suggestions_received", models.IntegerField(default=0)),
                ("suggestions_approved", models.IntegerField(default=0)),
                ("suggestions_rejected", models.IntegerField(default=0)),
                ("suggestions_modified", models.IntegerField(default=0)),
                ("suggestions_ignored", models.IntegerField(default=0)),
                (
                    "approval_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of suggestions approved",
                        max_digits=6,
                    ),
                ),
                (
                    "modification_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of suggestions modified",
                        max_digits=6,
                    ),
                ),
                (
                    "avg_decision_time_seconds",
                    models.IntegerField(
                        default=0, help_text="Average time to make a decision"
                    ),
                ),
                (
                    "median_decision_time_seconds",
                    models.IntegerField(
                        default=0, help_text="Median time to make a decision"
                    ),
                ),
                (
                    "strategy_approval_rates",
                    models.JSONField(
                        default=dict,
                        help_text="Approval rate by strategy: {'kotak_strangle': 75.0, ...}",
                    ),
                ),
                (
                    "high_vix_approval_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approval rate when VIX > 18",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "low_vix_approval_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approval rate when VIX <= 18",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "approved_trades_win_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Win rate of trades user approved",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "rejected_trades_would_have_won_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate at which rejected trades would have been profitable",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "last_computed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When profile was last computed"
                    ),
                ),
                (
                    "decisions_included",
                    models.IntegerField(
                        default=0,
                        help_text="Number of decisions included in computation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Behavior Profile",
                "verbose_name_plural": "User Behavior Profiles",
                "db_table": "user_behavior_profile",
            },
        ),
        migrations.CreateModel(
            name="PortfolioBeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "benchmark",
                    models.CharField(
                        choices=[
                            ("NIFTY50", "Nifty 50"),
                            ("BANKNIFTY", "Bank Nifty"),
                            ("NIFTYIT", "Nifty IT"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("30D", "30 Days"),
                            ("60D", "60 Days"),
                            ("90D", "90 Days"),
                            ("180D", "180 Days"),
                            ("1Y", "1 Year"),
                            ("ALL", "All Time"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calculation_date", models.DateField()),
                (
                    "beta",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Portfolio beta vs benchmark",
                        max_digits=10,
                    ),
                ),
                (
                    "alpha",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Portfolio alpha (excess return)",
                        max_digits=10,
                    ),
                ),
                (
                    "r_squared",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="R-squared of regression",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "correlation",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "portfolio_return",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "benchmark_return",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("excess_return", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "risk_free_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.065"),
                        help_text="Risk-free rate used (default 6.5% T-bill)",
                        max_digits=6,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_betas",
                        to="accounts.brokeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_beta",
                "ordering": ["-calculation_date"],
            },
        ),
        migrations.CreateModel(
            name="MLFeatureStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "spot_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "vix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "vix_percentile_30d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="VIX percentile over last 30 days",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, help_text="0=Monday, 6=Sunday", null=True
                    ),
                ),
                ("hour_of_day", models.IntegerField(blank=True, null=True)),
                ("days_to_expiry", models.IntegerField(blank=True, null=True)),
                ("is_expiry_week", models.BooleanField(default=False)),
                ("is_monthly_expiry", models.BooleanField(default=False)),
                (
                    "spot_vs_sma20",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="(Spot - SMA20) / SMA20 * 100",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "spot_vs_sma50",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "rsi_14",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "macd_histogram",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "pcr_oi",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "pcr_volume",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "max_pain_distance_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Distance from max pain as percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "algo_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "algo_signal_strength",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("strategy_type", models.CharField(blank=True, max_length=30)),
                (
                    "user_historical_approval_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("user_avg_decision_time", models.IntegerField(blank=True, null=True)),
                (
                    "user_win_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "last_5_trades_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "last_5_trades_win_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Positive for win streak, negative for loss streak",
                    ),
                ),
                (
                    "current_day_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "label_1d_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L after 1 day (if closed)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "label_1d_outcome",
                    models.CharField(
                        blank=True,
                        help_text="1-day outcome: PROFIT/LOSS/OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "label_final_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "label_final_outcome",
                    models.CharField(
                        blank=True,
                        help_text="Final outcome: PROFIT/LOSS/BREAKEVEN",
                        max_length=15,
                    ),
                ),
                (
                    "feature_vector",
                    models.JSONField(
                        default=list, help_text="Ordered list of features for ML model"
                    ),
                ),
                (
                    "feature_version",
                    models.CharField(
                        default="v1",
                        help_text="Feature engineering version",
                        max_length=10,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False, help_text="Whether all features are computed"
                    ),
                ),
                (
                    "labels_computed",
                    models.BooleanField(
                        default=False, help_text="Whether outcome labels are computed"
                    ),
                ),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_features",
                        to="analytics.userdecisionlog",
                    ),
                ),
            ],
            options={
                "db_table": "ml_feature_store",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="marketcontextsnapshot",
            index=models.Index(
                fields=["-snapshot_timestamp"], name="market_cont_snapsho_2f278b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketcontextsnapshot",
            index=models.Index(
                fields=["nifty_trend", "-snapshot_timestamp"],
                name="market_cont_nifty_t_8ea9c7_idx",
            ),
        ),
        migrations.AddField(
            model_name="dailyequitycurve",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equity_curves",
                to="accounts.brokeraccount",
            ),
        ),
        migrations.AddIndex(
            model_name="benchmarkdata",
            index=models.Index(
                fields=["benchmark", "-date"], name="benchmark_d_benchma_520cfc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="benchmarkdata",
            unique_together={("benchmark", "date")},
        ),
        migrations.AddField(
            model_name="accountreturns",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_returns",
                to="accounts.brokeraccount",
            ),
        ),
        migrations.AddIndex(
            model_name="userdecisionlog",
            index=models.Index(
                fields=["user", "-decision_timestamp"],
                name="user_decisi_user_id_e89dc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userdecisionlog",
            index=models.Index(
                fields=["decision_type", "-decision_timestamp"],
                name="user_decisi_decisio_0c1844_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userdecisionlog",
            index=models.Index(
                fields=["final_outcome"], name="user_decisi_final_o_de377b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdecisionlog",
            index=models.Index(
                fields=["suggestion", "decision_type"],
                name="user_decisi_suggest_c6ebac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliobeta",
            index=models.Index(
                fields=["account", "benchmark", "-calculation_date"],
                name="portfolio_b_account_d3d76c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliobeta",
            constraint=models.UniqueConstraint(
                fields=("account", "benchmark", "period_type", "calculation_date"),
                name="unique_beta_calculation",
            ),
        ),
        migrations.AddIndex(
            model_name="mlfeaturestore",
            index=models.Index(
                fields=["is_complete", "labels_computed"],
                name="ml_feature__is_comp_9f5e96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mlfeaturestore",
            index=models.Index(
                fields=["strategy_type"], name="ml_feature__strateg_285146_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlfeaturestore",
            index=models.Index(
                fields=["-created_at"], name="ml_feature__created_fe2ee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyequitycurve",
            index=models.Index(
                fields=["account", "-date"], name="daily_equit_account_91b442_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyequitycurve",
            index=models.Index(fields=["-date"], name="daily_equit_date_c99020_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailyequitycurve",
            unique_together={("account", "date")},
        ),
        migrations.AddIndex(
            model_name="accountreturns",
            index=models.Index(
                fields=["account", "period_type", "-period_end"],
                name="account_ret_account_84b79e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountreturns",
            index=models.Index(
                fields=["period_type", "-period_end"],
                name="account_ret_period__10753b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountreturns",
            constraint=models.UniqueConstraint(
                fields=("account", "period_type", "period_start", "period_end"),
                name="unique_account_period",
            ),
        ),
    ]
