# Generated by Django 4.2.7 on 2026-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0006_accountreturns_benchmarkdata_dailyequitycurve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeperformance",
            name="averaging_helped",
            field=models.BooleanField(
                blank=True,
                help_text="Whether averaging improved the outcome",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradeperformance",
            name="exit_reason",
            field=models.CharField(
                choices=[
                    ("STOP_LOSS_HIT", "Stop Loss Hit"),
                    ("TARGET_HIT", "Target Hit"),
                    ("TIME_EXIT", "Time Exit"),
                    ("MANUAL", "Manual Close"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="Reason for exit",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tradeperformance",
            name="final_pnl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final realized P&L when position closed",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradeperformance",
            name="max_drawdown_during_trade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum unrealized loss during trade",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradeperformance",
            name="max_profit_during_trade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum unrealized profit during trade",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradeperformance",
            name="was_averaged",
            field=models.BooleanField(
                default=False, help_text="Whether averaging was used on this position"
            ),
        ),
    ]
