# Generated by Django 4.2.7 on 2026-04-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0011_add_portfolio_pnl_tracker"),
        ("analytics", "0007_tradeperformance_averaging_helped_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HindsightCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "offset_days",
                    models.IntegerField(
                        help_text="Trading days after exit: 0=EOD, 1, 3, 5, 7, 15"
                    ),
                ),
                (
                    "offset_label",
                    models.CharField(
                        help_text="Human label: 'Exit Day EOD', '+1 Day', etc.",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        db_index=True, help_text="Calendar date this checkpoint targets"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("COMPLETE", "Complete"),
                            ("EXPIRED", "Expired"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("instrument", models.CharField(max_length=100)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("direction", models.CharField(max_length=10)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("exit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Why the trade was closed: TARGET, STOP_LOSS, MANUAL, EOD_THURSDAY, EXPIRY_DAY, etc.",
                        max_length=100,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("lot_size", models.IntegerField(default=1)),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "hypothetical_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L if held until checkpoint close (calculated from entry_price)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "hypothetical_pnl_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Hypothetical P&L as % of entry value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "best_case_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L at day high (LONG) or day low (SHORT)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "worst_case_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L at day low (LONG) or day high (SHORT)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "actual_realized_pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual realized P&L from the closed position",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "opportunity_delta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="+ve = left money on table, -ve = right to exit when we did",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hindsight_checkpoints",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "db_table": "hindsight_checkpoint",
                "ordering": ["position", "offset_days"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_date"],
                        name="hindsight_c_status_8397f6_idx",
                    ),
                    models.Index(
                        fields=["instrument", "-scheduled_date"],
                        name="hindsight_c_instrum_324395_idx",
                    ),
                    models.Index(
                        fields=["exit_reason", "status"],
                        name="hindsight_c_exit_re_a69b68_idx",
                    ),
                ],
                "unique_together": {("position", "offset_days")},
            },
        ),
    ]
