# Generated by Django 3.1.7 on 2025-11-15 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(max_length=200)),
                ('template', models.TextField(help_text='Prompt template with placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('times_used', models.IntegerField(default=0)),
                ('avg_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'llm_prompts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('symbol', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=10)),
                ('prompt', models.TextField(help_text='Prompt sent to LLM')),
                ('context_data', models.JSONField(default=dict, help_text='Market data, OI, sector info')),
                ('raw_response', models.TextField(help_text='Raw LLM response')),
                ('parsed_response', models.JSONField(default=dict, help_text='Structured response')),
                ('recommendation', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('AVOID', 'Avoid')], help_text='LLM recommendation', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence score (0-100)', max_digits=5)),
                ('reasoning', models.TextField(blank=True, help_text='LLM reasoning')),
                ('risk_factors', models.JSONField(default=list, help_text='Identified risk factors')),
                ('model_used', models.CharField(default='deepseek-coder:33b', max_length=100)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('human_approved', models.BooleanField(blank=True, null=True)),
                ('human_notes', models.TextField(blank=True)),
                ('was_executed', models.BooleanField(default=False)),
                ('actual_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('outcome_correct', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'llm_validations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='llmvalidation',
            index=models.Index(fields=['symbol', '-created_at'], name='llm_validat_symbol_b1e9c8_idx'),
        ),
    ]
