# Generated by Django 4.2.7 on 2026-07-20 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("llm", "0002_alter_llmprompt_id_alter_llmvalidation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "active_provider",
                    models.CharField(
                        choices=[
                            ("vllm", "Local (self-hosted vLLM)"),
                            ("openai", "OpenAI (ChatGPT, cloud)"),
                        ],
                        default="vllm",
                        max_length=20,
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True, help_text="OpenAI API key", max_length=200
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(default="gpt-4o-mini", max_length=100),
                ),
                ("switched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "switched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Provider Config",
                "verbose_name_plural": "LLM Provider Config",
                "db_table": "llm_provider_config",
            },
        ),
    ]
