# Generated by Django 4.2.7 on 2026-07-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0003_llmproviderconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmproviderconfig",
            name="anthropic_api_key",
            field=models.CharField(
                blank=True, help_text="Anthropic (Claude) API key", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="anthropic_model",
            field=models.CharField(default="claude-opus-4-8", max_length=100),
        ),
        migrations.AlterField(
            model_name="llmproviderconfig",
            name="active_provider",
            field=models.CharField(
                choices=[
                    ("vllm", "Local (self-hosted vLLM)"),
                    ("openai", "OpenAI (ChatGPT, cloud)"),
                    ("anthropic", "Claude (Anthropic, cloud)"),
                ],
                default="vllm",
                max_length=20,
            ),
        ),
    ]
