# Generated by Django 4.2.7 on 2026-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_llmproviderconfig_anthropic_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmproviderconfig",
            name="active_provider",
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="evaluation_target",
            field=models.CharField(
                choices=[
                    ("local", "Local (self-hosted vLLM)"),
                    ("online", "Online (cloud)"),
                ],
                default="online",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="online_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI (ChatGPT)"),
                    ("anthropic", "Claude (Anthropic)"),
                ],
                default="openai",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="llmproviderconfig",
            name="understanding_target",
            field=models.CharField(
                choices=[
                    ("local", "Local (self-hosted vLLM)"),
                    ("online", "Online (cloud)"),
                ],
                default="local",
                max_length=10,
            ),
        ),
    ]
