# Generated by Django 3.1.7 on 2025-11-15 07:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('limit_type', models.CharField(help_text='Type of limit (DAILY_LOSS, WEEKLY_LOSS, POSITION_SIZE, etc.)', max_length=50)),
                ('limit_value', models.DecimalField(decimal_places=2, help_text='Maximum limit value', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current utilization', max_digits=15)),
                ('is_breached', models.BooleanField(db_index=True, default=False, help_text='Whether this limit is currently breached')),
                ('breach_timestamp', models.DateTimeField(blank=True, help_text='When the limit was breached', null=True)),
                ('period_start', models.DateField(help_text='Start of tracking period')),
                ('period_end', models.DateField(blank=True, help_text='End of tracking period', null=True)),
                ('warning_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Send warning when utilization reaches this % of limit', max_digits=5)),
                ('warning_sent', models.BooleanField(default=False, help_text='Whether warning alert was sent')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes')),
                ('account', models.ForeignKey(help_text='Associated broker account', on_delete=django.db.models.deletion.CASCADE, related_name='risk_limits', to='accounts.brokeraccount')),
            ],
            options={
                'verbose_name': 'Risk Limit',
                'verbose_name_plural': 'Risk Limits',
                'db_table': 'risk_limits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircuitBreaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('trigger_type', models.CharField(help_text='What triggered the circuit breaker (DAILY_LOSS, WEEKLY_LOSS, DRAWDOWN)', max_length=50)),
                ('trigger_value', models.DecimalField(decimal_places=2, help_text='Value that triggered the circuit breaker', max_digits=15)),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='Threshold value that was breached', max_digits=15)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='CRITICAL', help_text='Risk level', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether circuit breaker is currently active')),
                ('account_deactivated', models.BooleanField(default=False, help_text='Whether account was deactivated')),
                ('positions_closed', models.IntegerField(default=0, help_text='Number of positions auto-closed')),
                ('orders_cancelled', models.IntegerField(default=0, help_text='Number of pending orders cancelled')),
                ('reset_at', models.DateTimeField(blank=True, help_text='When circuit breaker was reset', null=True)),
                ('reset_by', models.CharField(blank=True, help_text='Who reset the circuit breaker', max_length=100)),
                ('cooldown_until', models.DateTimeField(blank=True, help_text='Account cannot trade until this time', null=True)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('actions_log', models.JSONField(default=list, help_text='Log of all actions taken')),
                ('account', models.ForeignKey(help_text='Associated broker account', on_delete=django.db.models.deletion.CASCADE, related_name='circuit_breakers', to='accounts.brokeraccount')),
            ],
            options={
                'verbose_name': 'Circuit Breaker',
                'verbose_name_plural': 'Circuit Breakers',
                'db_table': 'circuit_breakers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='risklimit',
            index=models.Index(fields=['account', 'is_breached'], name='risk_limits_account_cb9117_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='risklimit',
            unique_together={('account', 'limit_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='circuitbreaker',
            index=models.Index(fields=['account', 'is_active'], name='circuit_bre_account_802e63_idx'),
        ),
    ]
