from __future__ import annotations
import io
from datetime import date
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from apps.investments.models import InvestmentProduct


def generate_pdf_report(member=None, group=None, report_name='portfolio_snapshot') -> tuple[bytes, str]:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=2 * cm, leftMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('Title', parent=styles['Title'], alignment=TA_CENTER, fontSize=18, spaceAfter=12)
    header_style = ParagraphStyle('Header', parent=styles['Heading2'], fontSize=13, spaceAfter=6)
    normal = styles['Normal']
    right_style = ParagraphStyle('Right', parent=normal, alignment=TA_RIGHT)

    story = []

    # Header
    owner_name = (member.name if member else group.name) if (member or group) else 'All Members'
    story.append(Paragraph('Family Portfolio Intelligence', title_style))
    story.append(Paragraph(f'Portfolio Report — {owner_name}', styles['Heading3']))
    story.append(Paragraph(f'Generated: {date.today().strftime("%d %B %Y")}', normal))
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width='100%', color=colors.darkblue))
    story.append(Spacer(1, 0.5 * cm))

    # Fetch products
    if member:
        products = InvestmentProduct.objects.filter(
            investment_account__family_member=member, is_active=True
        ).select_related('investment_account')
    elif group:
        products = InvestmentProduct.objects.filter(
            investment_account__family_member__in=group.members.all(), is_active=True
        ).select_related('investment_account')
    else:
        products = InvestmentProduct.objects.none()

    total_invested = sum(float(p.invested_value) for p in products)
    total_current = sum(float(p.current_value) for p in products)
    gain = total_current - total_invested
    gain_pct = (gain / total_invested * 100) if total_invested else 0

    # Summary table
    story.append(Paragraph('Portfolio Summary', header_style))
    summary_data = [
        ['Metric', 'Value'],
        ['Total Invested', f'₹{total_invested:,.2f}'],
        ['Current Value', f'₹{total_current:,.2f}'],
        ['Gain / Loss', f'₹{gain:,.2f} ({gain_pct:.2f}%)'],
        ['Products', str(products.count())],
    ]
    summary_table = Table(summary_data, colWidths=[8 * cm, 8 * cm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.5 * cm))

    # Holdings table
    story.append(Paragraph('Holdings Detail', header_style))
    holdings_data = [['Name', 'Type', 'Invested (₹)', 'Current (₹)', 'Gain/Loss (₹)', 'XIRR %']]
    for p in products.order_by('-current_value')[:50]:
        xirr_str = f'{float(p.xirr) * 100:.1f}%' if p.xirr else '—'
        holdings_data.append([
            p.name[:35],
            p.product_type,
            f'{float(p.invested_value):,.0f}',
            f'{float(p.current_value):,.0f}',
            f'{float(p.gain_loss):,.0f}',
            xirr_str,
        ])

    col_widths = [5.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 1.5 * cm]
    holdings_table = Table(holdings_data, colWidths=col_widths)
    holdings_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
        ('GRID', (0, 0), (-1, -1), 0.3, colors.grey),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('PADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(holdings_table)

    # Footer
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width='100%', color=colors.grey))
    story.append(Paragraph(
        'Generated by Family Portfolio Intelligence | mCube-ai | For informational purposes only.',
        ParagraphStyle('footer', parent=normal, fontSize=7, textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    filename = f'portfolio_report_{owner_name.replace(" ", "_")}_{date.today().isoformat()}.pdf'
    return pdf_bytes, filename
